/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesIndexRouteImport } from './routes/templates/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as TemplatesVideoRouteImport } from './routes/templates/video'
import { Route as TemplatesSlidesRouteImport } from './routes/templates/slides'
import { Route as TemplatesContentRouteImport } from './routes/templates/content'
import { Route as TemplatesCalendarRouteImport } from './routes/templates/calendar'
import { Route as TemplatesBrandImageGeneratorRouteImport } from './routes/templates/brand-image-generator'
import { Route as TemplatesAnalyticsRouteImport } from './routes/templates/analytics'
import { Route as DocsServerRouteImport } from './routes/docs/server'
import { Route as DocsScriptsRouteImport } from './routes/docs/scripts'
import { Route as DocsKeyConceptsRouteImport } from './routes/docs/key-concepts'
import { Route as DocsHarnessesRouteImport } from './routes/docs/harnesses'
import { Route as DocsDatabaseAdaptersRouteImport } from './routes/docs/database-adapters'
import { Route as DocsCreatingTemplatesRouteImport } from './routes/docs/creating-templates'
import { Route as DocsClientRouteImport } from './routes/docs/client'
import { Route as DocsCliAdaptersRouteImport } from './routes/docs/cli-adapters'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TemplatesRoute,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesVideoRoute = TemplatesVideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => TemplatesRoute,
} as any)
const TemplatesSlidesRoute = TemplatesSlidesRouteImport.update({
  id: '/slides',
  path: '/slides',
  getParentRoute: () => TemplatesRoute,
} as any)
const TemplatesContentRoute = TemplatesContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => TemplatesRoute,
} as any)
const TemplatesCalendarRoute = TemplatesCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => TemplatesRoute,
} as any)
const TemplatesBrandImageGeneratorRoute =
  TemplatesBrandImageGeneratorRouteImport.update({
    id: '/brand-image-generator',
    path: '/brand-image-generator',
    getParentRoute: () => TemplatesRoute,
  } as any)
const TemplatesAnalyticsRoute = TemplatesAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => TemplatesRoute,
} as any)
const DocsServerRoute = DocsServerRouteImport.update({
  id: '/docs/server',
  path: '/docs/server',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsScriptsRoute = DocsScriptsRouteImport.update({
  id: '/docs/scripts',
  path: '/docs/scripts',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsKeyConceptsRoute = DocsKeyConceptsRouteImport.update({
  id: '/docs/key-concepts',
  path: '/docs/key-concepts',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsHarnessesRoute = DocsHarnessesRouteImport.update({
  id: '/docs/harnesses',
  path: '/docs/harnesses',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsDatabaseAdaptersRoute = DocsDatabaseAdaptersRouteImport.update({
  id: '/docs/database-adapters',
  path: '/docs/database-adapters',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsCreatingTemplatesRoute = DocsCreatingTemplatesRouteImport.update({
  id: '/docs/creating-templates',
  path: '/docs/creating-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsClientRoute = DocsClientRouteImport.update({
  id: '/docs/client',
  path: '/docs/client',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsCliAdaptersRoute = DocsCliAdaptersRouteImport.update({
  id: '/docs/cli-adapters',
  path: '/docs/cli-adapters',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/docs/cli-adapters': typeof DocsCliAdaptersRoute
  '/docs/client': typeof DocsClientRoute
  '/docs/creating-templates': typeof DocsCreatingTemplatesRoute
  '/docs/database-adapters': typeof DocsDatabaseAdaptersRoute
  '/docs/harnesses': typeof DocsHarnessesRoute
  '/docs/key-concepts': typeof DocsKeyConceptsRoute
  '/docs/scripts': typeof DocsScriptsRoute
  '/docs/server': typeof DocsServerRoute
  '/templates/analytics': typeof TemplatesAnalyticsRoute
  '/templates/brand-image-generator': typeof TemplatesBrandImageGeneratorRoute
  '/templates/calendar': typeof TemplatesCalendarRoute
  '/templates/content': typeof TemplatesContentRoute
  '/templates/slides': typeof TemplatesSlidesRoute
  '/templates/video': typeof TemplatesVideoRoute
  '/docs/': typeof DocsIndexRoute
  '/templates/': typeof TemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs/cli-adapters': typeof DocsCliAdaptersRoute
  '/docs/client': typeof DocsClientRoute
  '/docs/creating-templates': typeof DocsCreatingTemplatesRoute
  '/docs/database-adapters': typeof DocsDatabaseAdaptersRoute
  '/docs/harnesses': typeof DocsHarnessesRoute
  '/docs/key-concepts': typeof DocsKeyConceptsRoute
  '/docs/scripts': typeof DocsScriptsRoute
  '/docs/server': typeof DocsServerRoute
  '/templates/analytics': typeof TemplatesAnalyticsRoute
  '/templates/brand-image-generator': typeof TemplatesBrandImageGeneratorRoute
  '/templates/calendar': typeof TemplatesCalendarRoute
  '/templates/content': typeof TemplatesContentRoute
  '/templates/slides': typeof TemplatesSlidesRoute
  '/templates/video': typeof TemplatesVideoRoute
  '/docs': typeof DocsIndexRoute
  '/templates': typeof TemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/docs/cli-adapters': typeof DocsCliAdaptersRoute
  '/docs/client': typeof DocsClientRoute
  '/docs/creating-templates': typeof DocsCreatingTemplatesRoute
  '/docs/database-adapters': typeof DocsDatabaseAdaptersRoute
  '/docs/harnesses': typeof DocsHarnessesRoute
  '/docs/key-concepts': typeof DocsKeyConceptsRoute
  '/docs/scripts': typeof DocsScriptsRoute
  '/docs/server': typeof DocsServerRoute
  '/templates/analytics': typeof TemplatesAnalyticsRoute
  '/templates/brand-image-generator': typeof TemplatesBrandImageGeneratorRoute
  '/templates/calendar': typeof TemplatesCalendarRoute
  '/templates/content': typeof TemplatesContentRoute
  '/templates/slides': typeof TemplatesSlidesRoute
  '/templates/video': typeof TemplatesVideoRoute
  '/docs/': typeof DocsIndexRoute
  '/templates/': typeof TemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/templates'
    | '/docs/cli-adapters'
    | '/docs/client'
    | '/docs/creating-templates'
    | '/docs/database-adapters'
    | '/docs/harnesses'
    | '/docs/key-concepts'
    | '/docs/scripts'
    | '/docs/server'
    | '/templates/analytics'
    | '/templates/brand-image-generator'
    | '/templates/calendar'
    | '/templates/content'
    | '/templates/slides'
    | '/templates/video'
    | '/docs/'
    | '/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs/cli-adapters'
    | '/docs/client'
    | '/docs/creating-templates'
    | '/docs/database-adapters'
    | '/docs/harnesses'
    | '/docs/key-concepts'
    | '/docs/scripts'
    | '/docs/server'
    | '/templates/analytics'
    | '/templates/brand-image-generator'
    | '/templates/calendar'
    | '/templates/content'
    | '/templates/slides'
    | '/templates/video'
    | '/docs'
    | '/templates'
  id:
    | '__root__'
    | '/'
    | '/templates'
    | '/docs/cli-adapters'
    | '/docs/client'
    | '/docs/creating-templates'
    | '/docs/database-adapters'
    | '/docs/harnesses'
    | '/docs/key-concepts'
    | '/docs/scripts'
    | '/docs/server'
    | '/templates/analytics'
    | '/templates/brand-image-generator'
    | '/templates/calendar'
    | '/templates/content'
    | '/templates/slides'
    | '/templates/video'
    | '/docs/'
    | '/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TemplatesRoute: typeof TemplatesRouteWithChildren
  DocsCliAdaptersRoute: typeof DocsCliAdaptersRoute
  DocsClientRoute: typeof DocsClientRoute
  DocsCreatingTemplatesRoute: typeof DocsCreatingTemplatesRoute
  DocsDatabaseAdaptersRoute: typeof DocsDatabaseAdaptersRoute
  DocsHarnessesRoute: typeof DocsHarnessesRoute
  DocsKeyConceptsRoute: typeof DocsKeyConceptsRoute
  DocsScriptsRoute: typeof DocsScriptsRoute
  DocsServerRoute: typeof DocsServerRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/video': {
      id: '/templates/video'
      path: '/video'
      fullPath: '/templates/video'
      preLoaderRoute: typeof TemplatesVideoRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/templates/slides': {
      id: '/templates/slides'
      path: '/slides'
      fullPath: '/templates/slides'
      preLoaderRoute: typeof TemplatesSlidesRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/templates/content': {
      id: '/templates/content'
      path: '/content'
      fullPath: '/templates/content'
      preLoaderRoute: typeof TemplatesContentRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/templates/calendar': {
      id: '/templates/calendar'
      path: '/calendar'
      fullPath: '/templates/calendar'
      preLoaderRoute: typeof TemplatesCalendarRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/templates/brand-image-generator': {
      id: '/templates/brand-image-generator'
      path: '/brand-image-generator'
      fullPath: '/templates/brand-image-generator'
      preLoaderRoute: typeof TemplatesBrandImageGeneratorRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/templates/analytics': {
      id: '/templates/analytics'
      path: '/analytics'
      fullPath: '/templates/analytics'
      preLoaderRoute: typeof TemplatesAnalyticsRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/docs/server': {
      id: '/docs/server'
      path: '/docs/server'
      fullPath: '/docs/server'
      preLoaderRoute: typeof DocsServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/scripts': {
      id: '/docs/scripts'
      path: '/docs/scripts'
      fullPath: '/docs/scripts'
      preLoaderRoute: typeof DocsScriptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/key-concepts': {
      id: '/docs/key-concepts'
      path: '/docs/key-concepts'
      fullPath: '/docs/key-concepts'
      preLoaderRoute: typeof DocsKeyConceptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/harnesses': {
      id: '/docs/harnesses'
      path: '/docs/harnesses'
      fullPath: '/docs/harnesses'
      preLoaderRoute: typeof DocsHarnessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/database-adapters': {
      id: '/docs/database-adapters'
      path: '/docs/database-adapters'
      fullPath: '/docs/database-adapters'
      preLoaderRoute: typeof DocsDatabaseAdaptersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/creating-templates': {
      id: '/docs/creating-templates'
      path: '/docs/creating-templates'
      fullPath: '/docs/creating-templates'
      preLoaderRoute: typeof DocsCreatingTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/client': {
      id: '/docs/client'
      path: '/docs/client'
      fullPath: '/docs/client'
      preLoaderRoute: typeof DocsClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/cli-adapters': {
      id: '/docs/cli-adapters'
      path: '/docs/cli-adapters'
      fullPath: '/docs/cli-adapters'
      preLoaderRoute: typeof DocsCliAdaptersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TemplatesRouteChildren {
  TemplatesAnalyticsRoute: typeof TemplatesAnalyticsRoute
  TemplatesBrandImageGeneratorRoute: typeof TemplatesBrandImageGeneratorRoute
  TemplatesCalendarRoute: typeof TemplatesCalendarRoute
  TemplatesContentRoute: typeof TemplatesContentRoute
  TemplatesSlidesRoute: typeof TemplatesSlidesRoute
  TemplatesVideoRoute: typeof TemplatesVideoRoute
  TemplatesIndexRoute: typeof TemplatesIndexRoute
}

const TemplatesRouteChildren: TemplatesRouteChildren = {
  TemplatesAnalyticsRoute: TemplatesAnalyticsRoute,
  TemplatesBrandImageGeneratorRoute: TemplatesBrandImageGeneratorRoute,
  TemplatesCalendarRoute: TemplatesCalendarRoute,
  TemplatesContentRoute: TemplatesContentRoute,
  TemplatesSlidesRoute: TemplatesSlidesRoute,
  TemplatesVideoRoute: TemplatesVideoRoute,
  TemplatesIndexRoute: TemplatesIndexRoute,
}

const TemplatesRouteWithChildren = TemplatesRoute._addFileChildren(
  TemplatesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TemplatesRoute: TemplatesRouteWithChildren,
  DocsCliAdaptersRoute: DocsCliAdaptersRoute,
  DocsClientRoute: DocsClientRoute,
  DocsCreatingTemplatesRoute: DocsCreatingTemplatesRoute,
  DocsDatabaseAdaptersRoute: DocsDatabaseAdaptersRoute,
  DocsHarnessesRoute: DocsHarnessesRoute,
  DocsKeyConceptsRoute: DocsKeyConceptsRoute,
  DocsScriptsRoute: DocsScriptsRoute,
  DocsServerRoute: DocsServerRoute,
  DocsIndexRoute: DocsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
