/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsServerRouteImport } from './routes/docs/server'
import { Route as DocsScriptsRouteImport } from './routes/docs/scripts'
import { Route as DocsHarnessesRouteImport } from './routes/docs/harnesses'
import { Route as DocsClientRouteImport } from './routes/docs/client'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsServerRoute = DocsServerRouteImport.update({
  id: '/docs/server',
  path: '/docs/server',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsScriptsRoute = DocsScriptsRouteImport.update({
  id: '/docs/scripts',
  path: '/docs/scripts',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsHarnessesRoute = DocsHarnessesRouteImport.update({
  id: '/docs/harnesses',
  path: '/docs/harnesses',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsClientRoute = DocsClientRouteImport.update({
  id: '/docs/client',
  path: '/docs/client',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs/client': typeof DocsClientRoute
  '/docs/harnesses': typeof DocsHarnessesRoute
  '/docs/scripts': typeof DocsScriptsRoute
  '/docs/server': typeof DocsServerRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs/client': typeof DocsClientRoute
  '/docs/harnesses': typeof DocsHarnessesRoute
  '/docs/scripts': typeof DocsScriptsRoute
  '/docs/server': typeof DocsServerRoute
  '/docs': typeof DocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs/client': typeof DocsClientRoute
  '/docs/harnesses': typeof DocsHarnessesRoute
  '/docs/scripts': typeof DocsScriptsRoute
  '/docs/server': typeof DocsServerRoute
  '/docs/': typeof DocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs/client'
    | '/docs/harnesses'
    | '/docs/scripts'
    | '/docs/server'
    | '/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs/client'
    | '/docs/harnesses'
    | '/docs/scripts'
    | '/docs/server'
    | '/docs'
  id:
    | '__root__'
    | '/'
    | '/docs/client'
    | '/docs/harnesses'
    | '/docs/scripts'
    | '/docs/server'
    | '/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsClientRoute: typeof DocsClientRoute
  DocsHarnessesRoute: typeof DocsHarnessesRoute
  DocsScriptsRoute: typeof DocsScriptsRoute
  DocsServerRoute: typeof DocsServerRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/server': {
      id: '/docs/server'
      path: '/docs/server'
      fullPath: '/docs/server'
      preLoaderRoute: typeof DocsServerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/scripts': {
      id: '/docs/scripts'
      path: '/docs/scripts'
      fullPath: '/docs/scripts'
      preLoaderRoute: typeof DocsScriptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/harnesses': {
      id: '/docs/harnesses'
      path: '/docs/harnesses'
      fullPath: '/docs/harnesses'
      preLoaderRoute: typeof DocsHarnessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/client': {
      id: '/docs/client'
      path: '/docs/client'
      fullPath: '/docs/client'
      preLoaderRoute: typeof DocsClientRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsClientRoute: DocsClientRoute,
  DocsHarnessesRoute: DocsHarnessesRoute,
  DocsScriptsRoute: DocsScriptsRoute,
  DocsServerRoute: DocsServerRoute,
  DocsIndexRoute: DocsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
