// AUTO-GENERATED by bridge/codegen.ts — do not edit manually.
// Run: pnpm exec tsx app/components/design/bridge/codegen.ts

/** Compiled IIFE string for preview-theme.bridge.ts — inject into an iframe via srcdoc or a <script> tag. */
export const previewThemeBridgeScript: string = `"use strict";
(() => {
  // shared/preview-color-scheme.ts
  var FRAME_NAME_PREFIX = "agent-native:preview-color-scheme:";
  function parsePreviewColorSchemeFrameName(name) {
    if (!name || !name.startsWith(FRAME_NAME_PREFIX)) return null;
    const scheme = name.slice(FRAME_NAME_PREFIX.length);
    return scheme === "light" || scheme === "dark" ? scheme : null;
  }
  var PREFERS_COLOR_SCHEME_FEATURE = /\\(\\s*prefers-color-scheme\\s*(?::\\s*(light|dark)\\s*)?\\)/gi;
  var ALWAYS_TRUE_FEATURE = "(min-width: 0px)";
  var ALWAYS_FALSE_FEATURE = "(hover: hover) and (hover: none)";
  function mentionsPrefersColorScheme(mediaText) {
    PREFERS_COLOR_SCHEME_FEATURE.lastIndex = 0;
    return PREFERS_COLOR_SCHEME_FEATURE.test(mediaText);
  }
  function splitMediaQueryList(mediaText) {
    const queries = [];
    let depth = 0;
    let start = 0;
    for (let index = 0; index < mediaText.length; index += 1) {
      const char = mediaText[index];
      if (char === "(") depth += 1;
      else if (char === ")") depth = Math.max(0, depth - 1);
      else if (char === "," && depth === 0) {
        queries.push(mediaText.slice(start, index));
        start = index + 1;
      }
    }
    queries.push(mediaText.slice(start));
    return queries;
  }
  function rewriteMediaQuery(query, scheme) {
    PREFERS_COLOR_SCHEME_FEATURE.lastIndex = 0;
    const trimmed = query.trim();
    const only = /^\\(\\s*prefers-color-scheme\\s*(?::\\s*(light|dark)\\s*)?\\)$/i.exec(
      trimmed
    );
    if (only) {
      const wanted = only[1]?.toLowerCase();
      return !wanted || wanted === scheme ? "all" : "not all";
    }
    return query.replace(
      PREFERS_COLOR_SCHEME_FEATURE,
      (_match, wanted) => !wanted || wanted.toLowerCase() === scheme ? ALWAYS_TRUE_FEATURE : ALWAYS_FALSE_FEATURE
    );
  }
  function rewritePrefersColorSchemeMedia(mediaText, scheme) {
    if (!mentionsPrefersColorScheme(mediaText)) return null;
    return splitMediaQueryList(mediaText).map((query) => rewriteMediaQuery(query, scheme).trim()).join(", ");
  }
  var CSS_SIGNALS = [
    ["prefers-color-scheme", /prefers-color-scheme\\s*:\\s*dark/i],
    ["color-scheme", /color-scheme\\s*:[^;{}]*\\bdark\\b/i],
    ["light-dark", /\\blight-dark\\s*\\(/i],
    ["dark-class", /\\.dark(?![\\w-])/],
    [
      "dark-attribute",
      /\\[\\s*data-[\\w-]*(?:theme|mode|scheme)[\\w-]*\\s*[~|^$*]?=\\s*["']?dark(?![\\w-])/i
    ]
  ];
  var DARK_ATTRIBUTE_SELECTOR = /\\[\\s*(data-[\\w-]*(?:theme|mode|scheme)[\\w-]*)\\s*[~|^$*]?=\\s*["']?dark(?![\\w-])/gi;
  function findDarkAttributeNames(css) {
    const names = /* @__PURE__ */ new Set();
    const text = css.join("\\n");
    DARK_ATTRIBUTE_SELECTOR.lastIndex = 0;
    for (let match = DARK_ATTRIBUTE_SELECTOR.exec(text); match; match = DARK_ATTRIBUTE_SELECTOR.exec(text)) {
      names.add(match[1].toLowerCase());
    }
    return [...names];
  }
  var HREF_HOST = /^[a-z][a-z0-9+.-]*:\\/\\/([^/?#:]+)/i;
  var FONT_STYLESHEET_HOSTS = [
    "fonts.googleapis.com",
    "fonts.bunny.net",
    "use.typekit.net",
    "p.typekit.net"
  ];
  function isFontStylesheetHref(href) {
    const host = href ? HREF_HOST.exec(href)?.[1]?.toLowerCase() : void 0;
    return host !== void 0 && FONT_STYLESHEET_HOSTS.includes(host);
  }
  var CLASS_ATTRIBUTE = /\\bclass\\s*=\\s*(?:"([^"]*)"|'([^']*)')/gi;
  var DARK_VARIANT_TOKEN = /(?:^|:)dark:\\S/;
  function htmlHasDarkVariantClass(html) {
    CLASS_ATTRIBUTE.lastIndex = 0;
    for (let match = CLASS_ATTRIBUTE.exec(html); match; match = CLASS_ATTRIBUTE.exec(html)) {
      const value = match[1] ?? match[2] ?? "";
      if (value.split(/\\s+/).some((token) => DARK_VARIANT_TOKEN.test(token))) {
        return true;
      }
    }
    return false;
  }
  function detectDarkStyleSupport({
    css = [],
    html = "",
    unreadableStylesheets = 0,
    truncated = false
  }) {
    const text = css.join("\\n");
    const signals = [];
    for (const [signal, pattern] of CSS_SIGNALS) {
      if (pattern.test(text)) signals.push(signal);
    }
    if (html && htmlHasDarkVariantClass(html)) {
      signals.push("dark-variant-class");
    }
    if (signals.length > 0) return { support: "yes", signals };
    return {
      support: unreadableStylesheets > 0 || truncated ? "unknown" : "no",
      signals
    };
  }

  // app/components/design/bridge/preview-theme.bridge.ts
  (function() {
    if (window.__anPreviewTheme) return;
    window.__anPreviewTheme = true;
    var COLOR_SCHEME_MESSAGE = "agent-native:preview-color-scheme";
    var STATE_MESSAGE = "agent-native:preview-theme-state";
    var SCAN_CHAR_BUDGET = 2e6;
    var MAX_CLASS_SAMPLES = 50;
    var forced = parsePreviewColorSchemeFrameName(
      window.name
    );
    if (forced) window.name = "";
    var originalMedia = /* @__PURE__ */ new WeakMap();
    var rootBefore = null;
    var darkAttributeNames = [];
    var lastReport = "";
    var nativeMatchMedia = window.matchMedia ? window.matchMedia.bind(window) : null;
    function visitMediaList(list) {
      if (forced) {
        var original = originalMedia.get(list);
        var current = list.mediaText;
        var rewritten = rewritePrefersColorSchemeMedia(
          original !== void 0 ? original : current,
          forced
        );
        if (rewritten === null) return;
        if (original === void 0) originalMedia.set(list, current);
        if (rewritten !== current) list.mediaText = rewritten;
        return;
      }
      var saved = originalMedia.get(list);
      if (saved === void 0) return;
      if (list.mediaText !== saved) list.mediaText = saved;
      originalMedia.delete(list);
    }
    function visitRules(rules) {
      for (var index = 0; index < rules.length; index += 1) {
        var rule = rules[index];
        if (rule.media && typeof rule.media.mediaText === "string") {
          visitMediaList(rule.media);
        }
        if (rule.styleSheet) visitSheet(rule.styleSheet);
        else if (rule.cssRules) visitRules(rule.cssRules);
      }
    }
    var UNREADABLE = { unreadable: true };
    function readRules(sheet) {
      try {
        return sheet.cssRules;
      } catch (_err) {
        return UNREADABLE;
      }
    }
    function isUnreadable(rules) {
      return rules === UNREADABLE;
    }
    function visitSheet(sheet) {
      if (sheet.media) visitMediaList(sheet.media);
      var rules = readRules(sheet);
      if (!isUnreadable(rules)) visitRules(rules);
    }
    function allSheets() {
      var sheets = Array.prototype.slice.call(
        document.styleSheets
      );
      var adopted = document.adoptedStyleSheets;
      return adopted ? sheets.concat(Array.prototype.slice.call(adopted)) : sheets;
    }
    function rewriteStylesheets() {
      allSheets().forEach(visitSheet);
    }
    function scanStyles() {
      var css = [];
      var unreadable = 0;
      var budget = SCAN_CHAR_BUDGET;
      var truncated = false;
      function push(text) {
        if (budget <= 0) {
          truncated = true;
          return;
        }
        budget -= text.length;
        css.push(text);
      }
      function scanRules(rules) {
        for (var index = 0; index < rules.length && !truncated; index += 1) {
          var rule = rules[index];
          if (rule.media && typeof rule.media.mediaText === "string") {
            var mediaOriginal = originalMedia.get(rule.media);
            push(
              mediaOriginal !== void 0 ? mediaOriginal : rule.media.mediaText
            );
          }
          if (rule.styleSheet) scanSheet(rule.styleSheet);
          else if (typeof rule.selectorText === "string" && rule.style) {
            push(rule.selectorText + "{" + rule.style.cssText + "}");
          } else if (!rule.cssRules && !rule.media) {
            push(rule.cssText);
          }
          if (!rule.styleSheet && rule.cssRules) scanRules(rule.cssRules);
        }
      }
      function scanSheet(sheet) {
        if (sheet.media) {
          var sheetOriginal = originalMedia.get(sheet.media);
          push(
            sheetOriginal !== void 0 ? sheetOriginal : sheet.media.mediaText
          );
        }
        var rules = readRules(sheet);
        if (isUnreadable(rules)) {
          if (!isFontStylesheetHref(sheet.href)) unreadable += 1;
          return;
        }
        scanRules(rules);
      }
      allSheets().forEach(scanSheet);
      return { css, unreadable, truncated };
    }
    function classSample() {
      var nodes = document.querySelectorAll('[class*="dark:"]');
      var parts = [];
      for (var index = 0; index < nodes.length && index < MAX_CLASS_SAMPLES; index += 1) {
        parts.push('class="' + (nodes[index].getAttribute("class") || "") + '"');
      }
      return parts.join(" ");
    }
    function measureDarkStyles() {
      var scan = scanStyles();
      darkAttributeNames = findDarkAttributeNames(scan.css);
      var support = detectDarkStyleSupport({
        css: scan.css,
        html: classSample(),
        unreadableStylesheets: scan.unreadable,
        // Sheets that have not loaded yet are not in document.styleSheets, so
        // an empty result before the document settles proves nothing.
        truncated: scan.truncated || document.readyState !== "complete"
      }).support;
      return support;
    }
    function applyRoot() {
      var root = document.documentElement;
      if (!root) return;
      if (!forced) {
        if (!rootBefore) return;
        if (rootBefore.colorScheme) {
          root.style.setProperty("color-scheme", rootBefore.colorScheme);
        } else {
          root.style.removeProperty("color-scheme");
        }
        root.classList.toggle("dark", rootBefore.hadDark);
        Object.keys(rootBefore.attributes).forEach(function(name) {
          var before = rootBefore.attributes[name];
          if (before === null) root.removeAttribute(name);
          else root.setAttribute(name, before);
        });
        if (!root.getAttribute("style")) root.removeAttribute("style");
        rootBefore = null;
        return;
      }
      if (!rootBefore) {
        rootBefore = {
          colorScheme: root.style.getPropertyValue("color-scheme"),
          hadDark: root.classList.contains("dark"),
          attributes: {}
        };
      }
      root.style.setProperty("color-scheme", forced);
      root.classList.toggle("dark", forced === "dark");
      var names = darkAttributeNames.slice();
      ["data-theme"].forEach(function(name) {
        var value = root.getAttribute(name);
        if ((value === "light" || value === "dark") && names.indexOf(name) === -1) {
          names.push(name);
        }
      });
      names.forEach(function(name) {
        if (!(name in rootBefore.attributes)) {
          rootBefore.attributes[name] = root.getAttribute(name);
        }
        root.setAttribute(name, forced);
      });
    }
    var watchers = [];
    function evaluate(query) {
      if (!nativeMatchMedia) return false;
      var effective = forced === null ? query : rewritePrefersColorSchemeMedia(query, forced) ?? query;
      return nativeMatchMedia(effective).matches;
    }
    class ForcedMediaQueryList extends EventTarget {
      constructor(query) {
        super();
        this.onchange = null;
        this.nativeAttached = false;
        this.media = query;
        this.lastMatches = evaluate(query);
        this.nativeList = nativeMatchMedia ? nativeMatchMedia(query) : null;
      }
      get matches() {
        return evaluate(this.media);
      }
      addEventListener(type, callback, options) {
        super.addEventListener(type, callback, options);
        if (type !== "change" || this.nativeAttached) return;
        this.nativeAttached = true;
        watchers.push(new WeakRef(this));
        if (this.nativeList) {
          this.nativeList.addEventListener("change", () => {
            if (forced === null) this.refresh();
          });
        }
      }
      addListener(callback) {
        this.addEventListener("change", callback);
      }
      removeListener(callback) {
        this.removeEventListener("change", callback);
      }
      refresh() {
        var matches = this.matches;
        if (matches === this.lastMatches) return;
        this.lastMatches = matches;
        var event = new MediaQueryListEvent("change", {
          matches,
          media: this.media
        });
        if (this.onchange) this.onchange(event);
        this.dispatchEvent(event);
      }
    }
    function installMatchMedia() {
      if (!nativeMatchMedia) return;
      window.matchMedia = function(query) {
        if (!mentionsPrefersColorScheme(query)) {
          return nativeMatchMedia(query);
        }
        return new ForcedMediaQueryList(query);
      };
    }
    function notifyMatchMedia() {
      watchers = watchers.filter(function(ref) {
        var list = ref.deref();
        if (list) list.refresh();
        return Boolean(list);
      });
    }
    var pending = 0;
    function schedule() {
      if (pending) return;
      pending = window.setTimeout(function() {
        pending = 0;
        sync();
      }, 60);
    }
    function isStyleMutation(record) {
      function styleNode(node) {
        return node.nodeType === 1 && (node.tagName === "STYLE" || node.tagName === "LINK");
      }
      if (record.type === "characterData") {
        return Boolean(record.target.parentElement?.tagName === "STYLE");
      }
      if (record.target.nodeType === 1 && styleNode(record.target)) return true;
      for (var i = 0; i < record.addedNodes.length; i += 1) {
        if (styleNode(record.addedNodes[i])) return true;
      }
      for (var j = 0; j < record.removedNodes.length; j += 1) {
        if (styleNode(record.removedNodes[j])) return true;
      }
      return false;
    }
    var observer = null;
    function observe() {
      if (observer || typeof MutationObserver === "undefined") return;
      observer = new MutationObserver(function(records) {
        if (records.some(isStyleMutation)) schedule();
      });
      observer.observe(document.documentElement, {
        childList: true,
        subtree: true,
        characterData: true
      });
    }
    function patchInsertRule(prototype) {
      var host = prototype;
      if (!host || typeof host.insertRule !== "function") return;
      var original = host.insertRule;
      host.insertRule = function(...args) {
        var result = original.apply(this, args);
        if (forced) schedule();
        return result;
      };
    }
    function report() {
      var message = {
        type: STATE_MESSAGE,
        scheme: forced,
        darkStyles
      };
      var serialized = JSON.stringify(message);
      if (serialized === lastReport) return;
      lastReport = serialized;
      try {
        window.parent.postMessage(message, "*");
      } catch (_err) {
        lastReport = "";
      }
    }
    var darkStyles = "unknown";
    function sync() {
      rewriteStylesheets();
      darkStyles = measureDarkStyles();
      applyRoot();
      notifyMatchMedia();
      report();
    }
    function setScheme(next) {
      forced = next;
      if (next) observe();
      sync();
    }
    window.addEventListener("message", function(event) {
      if (event.source !== window.parent) return;
      var data = event.data;
      if (!data || data.type !== COLOR_SCHEME_MESSAGE) return;
      setScheme(
        data.scheme === "light" || data.scheme === "dark" ? data.scheme : null
      );
    });
    installMatchMedia();
    patchInsertRule(
      typeof CSSStyleSheet === "undefined" ? void 0 : CSSStyleSheet.prototype
    );
    patchInsertRule(
      typeof CSSGroupingRule === "undefined" ? void 0 : CSSGroupingRule.prototype
    );
    if (forced) observe();
    sync();
    document.addEventListener("DOMContentLoaded", schedule);
    window.addEventListener("load", schedule);
    document.addEventListener("load", schedule, true);
    window.setTimeout(schedule, 400);
    window.setTimeout(schedule, 1600);
  })();
})();
`;
