// AUTO-GENERATED by bridge/codegen.ts — do not edit manually.
// Run: pnpm exec tsx app/components/design/bridge/codegen.ts

/** Compiled IIFE string for shader-fill-preview.bridge.ts — inject into an iframe via srcdoc or a <script> tag. */
export const shaderFillPreviewBridgeScript: string = `"use strict";
(() => {
  // app/components/design/bridge/shader-fill-preview.bridge.ts
  (function() {
    var patchedEl = null;
    var originalBackground = "";
    function resolveTarget(selector, nodeId) {
      if (selector) {
        try {
          var hit = document.querySelector(selector);
          if (hit) return hit;
        } catch (_err) {
        }
      }
      if (nodeId) {
        var byId = document.querySelector(
          '[data-agent-native-node-id="' + nodeId.replace(/"/g, '\\\\"') + '"]'
        );
        if (byId) return byId;
      }
      return document.body;
    }
    function applyPreview(selector, nodeId, css) {
      clearPreview();
      var el = resolveTarget(selector, nodeId);
      if (!el) return;
      originalBackground = el.style.background || "";
      el.style.background = css || "";
      patchedEl = el;
    }
    function clearPreview() {
      if (!patchedEl) return;
      patchedEl.style.background = originalBackground;
      patchedEl = null;
      originalBackground = "";
    }
    function runtime() {
      var api = window.__anShaders;
      return api && api.version >= 1 ? api : null;
    }
    window.addEventListener("message", function(e) {
      if (e.source !== window.parent) return;
      if (!e.data || typeof e.data.type !== "string") return;
      if (e.data.type === "shader-fill-preview") {
        var selector = typeof e.data.selector === "string" ? e.data.selector : "";
        var nodeId = typeof e.data.nodeId === "string" ? e.data.nodeId : "";
        var css = typeof e.data.css === "string" ? e.data.css : "";
        applyPreview(selector, nodeId, css);
        return;
      }
      if (e.data.type === "shader-fill-preview-clear") {
        clearPreview();
        return;
      }
      if (e.data.type === "glsl-shader-preview") {
        var api = runtime();
        if (!api) return;
        var target = e.data.target && typeof e.data.target === "object" ? e.data.target : {};
        var shader = e.data.shader && typeof e.data.shader === "object" ? e.data.shader : null;
        if (!shader || typeof shader.glsl !== "string") return;
        api.applyPreview(
          { nodeId: target.nodeId, selector: target.selector },
          {
            id: shader.id,
            name: shader.name,
            glsl: shader.glsl,
            uniforms: shader.uniforms,
            values: e.data.values && typeof e.data.values === "object" ? e.data.values : void 0
          },
          e.data.mode === "effect" ? "effect" : "fill"
        );
        return;
      }
      if (e.data.type === "glsl-shader-set-uniform") {
        var api2 = runtime();
        if (!api2) return;
        if (typeof e.data.name !== "string") return;
        api2.setUniform(
          e.data.filter && typeof e.data.filter === "object" ? e.data.filter : {},
          e.data.name,
          e.data.value
        );
        return;
      }
      if (e.data.type === "glsl-shader-update") {
        var api3 = runtime();
        if (!api3) return;
        if (typeof e.data.id !== "string") return;
        api3.updateShader(e.data.id, {
          glsl: typeof e.data.glsl === "string" ? e.data.glsl : void 0,
          uniforms: e.data.uniforms && typeof e.data.uniforms === "object" ? e.data.uniforms : void 0
        });
        return;
      }
      if (e.data.type === "glsl-shader-preview-clear") {
        var api4 = runtime();
        if (api4) api4.clearPreview();
        return;
      }
      if (e.data.type === "glsl-shader-rescan") {
        var api5 = runtime();
        if (api5) api5.scan();
        return;
      }
    });
  })();
})();
`;
