// AUTO-GENERATED by bridge/codegen.ts — do not edit manually.
// Run: pnpm exec tsx app/components/design/bridge/codegen.ts

/** Compiled IIFE string for source-location.bridge.ts — inject into an iframe via srcdoc or a <script> tag. */
export const sourceLocationBridgeScript: string = `"use strict";
(() => {
  // app/components/design/bridge/source-location.bridge.ts
  (function() {
    var FIBER_KEY_PREFIXES = [
      "__reactFiber$",
      "__reactInternalInstance$",
      "__reactInternalFiberCurrent$",
      "__reactInternalFiber$"
    ];
    var NOISE_SEGMENTS = {
      node_modules: true,
      dist: true,
      build: true,
      ".next": true,
      public: true
    };
    function isNoisePath(path) {
      var segments = path.split("/");
      for (var i = 0; i < segments.length; i += 1) {
        if (NOISE_SEGMENTS[segments[i]]) return true;
        if (segments[i] === "_next" && segments[i + 1] === "static") return true;
      }
      return false;
    }
    function resolveFrameUrl(rawUrl) {
      if (rawUrl.indexOf("webpack-internal:///") === 0) {
        var wPath = rawUrl.slice("webpack-internal:///".length).replace(/^\\.\\//, "");
        return wPath || null;
      }
      try {
        var url = new URL(rawUrl);
        var path = decodeURIComponent(url.pathname);
        if (path.indexOf("/@fs/") === 0) {
          path = path.slice("/@fs".length);
        } else if (url.protocol !== "file:") {
          path = path.replace(/^\\/+/, "");
        }
        return path || null;
      } catch (_err) {
        return null;
      }
    }
    var STACK_FRAME_RE = /^\\s*at\\s+(?:([^\\s(]+)\\s+\\()?([^()\\s][^()]*?):(\\d+):(\\d+)\\)?\\s*$/;
    function parseStackFrame(line) {
      var match = STACK_FRAME_RE.exec(line);
      if (!match) return null;
      var functionName = match[1];
      var rawUrl = match[2];
      var sourceFile = resolveFrameUrl(rawUrl);
      if (!sourceFile || isNoisePath(sourceFile)) return null;
      var lineNumber = Number(match[3]);
      var column = Number(match[4]);
      if (!isFinite(lineNumber) || !isFinite(column)) return null;
      return {
        sourceFile,
        line: lineNumber,
        column,
        functionName: functionName || void 0
      };
    }
    function extractFromDebugStack(stack) {
      var lines = stack.split("\\n");
      for (var i = 0; i < lines.length; i += 1) {
        var parsed = parseStackFrame(lines[i]);
        if (parsed) return parsed;
      }
      return null;
    }
    function getFiberFromDom(node) {
      var keys = Object.keys(node);
      for (var i = 0; i < keys.length; i += 1) {
        for (var j = 0; j < FIBER_KEY_PREFIXES.length; j += 1) {
          if (keys[i].indexOf(FIBER_KEY_PREFIXES[j]) === 0) {
            return node[keys[i]];
          }
        }
      }
      return null;
    }
    function findNearestFiber(el) {
      var node = el;
      var attempts = 0;
      while (node && attempts < 8) {
        var fiber = getFiberFromDom(node);
        if (fiber) return fiber;
        node = node.parentElement;
        attempts += 1;
      }
      return null;
    }
    function debugSourceOf(fiber) {
      var source = fiber._debugSource || fiber._debugInfo && fiber._debugInfo.source || fiber.stateNode && fiber.stateNode._debugSource || fiber.elementType && fiber.elementType._debugSource;
      if (source && source.fileName) {
        return {
          sourceFile: source.fileName,
          line: source.lineNumber,
          column: source.columnNumber
        };
      }
      var stack = fiber._debugStack && fiber._debugStack.stack || fiber._debugInfo && fiber._debugInfo.stack || fiber.stateNode && fiber.stateNode._debugStack && fiber.stateNode._debugStack.stack;
      if (stack) {
        var parsed = extractFromDebugStack(String(stack));
        if (parsed) {
          return {
            sourceFile: parsed.sourceFile,
            line: parsed.line,
            column: parsed.column
          };
        }
      }
      return null;
    }
    function isComponentFiber(fiber) {
      return typeof fiber.type === "function";
    }
    function componentNameOf(fiber) {
      var type = fiber.type;
      return type && (type.displayName || type.name) || void 0;
    }
    function resolveFromDataAttributes(el) {
      var sourceFile = el.getAttribute("data-source-file");
      var lineAttr = el.getAttribute("data-source-line");
      var columnAttr = el.getAttribute("data-source-column");
      var component = el.getAttribute("data-component-name");
      var dataLoc = el.getAttribute("data-loc");
      if (!sourceFile && dataLoc) {
        var lastColon = dataLoc.lastIndexOf(":");
        var lastPart = lastColon >= 0 ? dataLoc.slice(lastColon + 1) : "";
        if (lastColon >= 0 && /^\\d+$/.test(lastPart)) {
          var before = dataLoc.slice(0, lastColon);
          var prevColon = before.lastIndexOf(":");
          var prevPart = prevColon >= 0 ? before.slice(prevColon + 1) : "";
          var hasColumn = /^\\d+$/.test(prevPart);
          sourceFile = hasColumn ? before.slice(0, prevColon) : before;
          lineAttr = hasColumn ? prevPart : lastPart;
          columnAttr = hasColumn ? lastPart : columnAttr;
        }
      }
      if (!sourceFile || !lineAttr) return null;
      var line = Number(lineAttr);
      if (!isFinite(line)) return null;
      var column = columnAttr ? Number(columnAttr) : void 0;
      return {
        status: "resolved",
        method: "data-attribute",
        sourceFile,
        line,
        column: isFinite(column) ? column : void 0,
        componentName: component || void 0
      };
    }
    function resolveFromFiber(el) {
      var leafFiber = findNearestFiber(el);
      if (!leafFiber) return { status: "unavailable", reason: "not-react" };
      var elementSource = null;
      var elementMethod = null;
      var componentFiber = null;
      var current = leafFiber;
      var depth = 0;
      while (current && depth < 12) {
        if (!elementSource) {
          var hasStructured = !!(current._debugSource || current._debugInfo && current._debugInfo.source || current.stateNode && current.stateNode._debugSource || current.elementType && current.elementType._debugSource);
          var found = debugSourceOf(current);
          if (found) {
            elementSource = found;
            elementMethod = hasStructured ? "debug-source" : "debug-stack";
          }
        }
        if (!componentFiber && current !== leafFiber && isComponentFiber(current)) {
          componentFiber = current;
        }
        if (elementSource && componentFiber) break;
        current = current.return || current.parent || current._debugOwner;
        depth += 1;
      }
      if (!elementSource || !elementMethod) {
        return { status: "unavailable", reason: "no-debug-info" };
      }
      var result = {
        status: "resolved",
        method: elementMethod,
        sourceFile: elementSource.sourceFile,
        line: elementSource.line,
        column: elementSource.column
      };
      if (componentFiber) {
        result.componentName = componentNameOf(componentFiber);
        var ownerSource = debugSourceOf(componentFiber);
        if (ownerSource) {
          result.ownerSourceFile = ownerSource.sourceFile;
          result.ownerLine = ownerSource.line;
          result.ownerColumn = ownerSource.column;
          result.ownerComponentName = result.componentName;
        }
        if (typeof componentFiber.key === "string" && componentFiber.key) {
          result.ownerKey = componentFiber.key;
        }
      }
      return result;
    }
    function resolveSourceLocation(el) {
      var fromAttributes = resolveFromDataAttributes(el);
      if (fromAttributes) return fromAttributes;
      return resolveFromFiber(el);
    }
    function findTarget(nodeId, selector) {
      if (nodeId) {
        var byId = document.querySelector(
          '[data-agent-native-node-id="' + nodeId.replace(/"/g, '\\\\"') + '"]'
        );
        if (byId) return byId;
      }
      if (selector) {
        try {
          return document.querySelector(selector);
        } catch (_err) {
          return null;
        }
      }
      return null;
    }
    window.addEventListener("message", function(e) {
      if (e.source !== window.parent) return;
      if (!e.data || e.data.type !== "agent-native:source-location-request")
        return;
      var correlationId = e.data.correlationId || "";
      var target = findTarget(e.data.nodeId, e.data.selector);
      var result = target ? resolveSourceLocation(target) : { status: "unavailable", reason: "element-not-found" };
      try {
        window.parent.postMessage(
          {
            type: "agent-native:source-location-result",
            correlationId,
            result
          },
          "*"
        );
      } catch (_err) {
      }
    });
  })();
})();
`;
