import {
  IconAdjustmentsHorizontal,
  IconApps,
  IconBell,
  IconBolt,
  IconBuilding,
  IconChartBar,
  IconClockPlay,
  IconCpu,
  IconFileText,
  IconFlask,
  IconFolder,
  IconHistory,
  IconKey,
  IconLibrary,
  IconLockAccess,
  IconMessages,
  IconNews,
  IconNotebook,
  IconPlugConnected,
  IconServer,
  IconServerBolt,
  IconShieldLock,
  IconTopologyRing2,
  IconUserCircle,
  IconUsers,
} from "@tabler/icons-react";
import { lazy } from "react";

import { SIGN_OUT_SEARCH_TERMS } from "../../sign-out.js";
import {
  canManageOrganizationPages,
  defineSettingsPage,
  type SettingsPageDefinition,
} from "./registry.js";

const label = (key: string) => `agentChat.settingsShell.page.${key}`;

/**
 * Core pages in spec order (§4.2). Each renders today's component for its
 * area until its page task swaps the file under `pages/`; ids and
 * `legacyTabIds` stay stable across that swap.
 */
export const CORE_SETTINGS_PAGES: readonly SettingsPageDefinition[] = [
  defineSettingsPage({
    id: "profile",
    group: "account",
    order: 10,
    labelKey: label("profile"),
    icon: IconUserCircle,
    component: lazy(() => import("./pages/profile.js")),
    legacyTabIds: ["account"],
    keywords: [
      "profile photo avatar identity signed in email name",
      ...SIGN_OUT_SEARCH_TERMS,
    ].join(" "),
  }),
  defineSettingsPage({
    id: "preferences",
    group: "account",
    order: 20,
    labelKey: label("preferences"),
    icon: IconAdjustmentsHorizontal,
    component: lazy(() => import("./pages/preferences.js")),
    legacyTabIds: ["language"],
    keywords: "language locale timezone voice transcription dictation",
  }),
  defineSettingsPage({
    id: "security",
    group: "account",
    order: 30,
    labelKey: label("security"),
    icon: IconShieldLock,
    component: lazy(() => import("./pages/security.js")),
    keywords: "password two-factor 2fa authenticator privacy data deletion",
  }),
  defineSettingsPage({
    id: "integrations",
    group: "connections",
    order: 10,
    labelKey: label("integrations"),
    icon: IconPlugConnected,
    component: lazy(() => import("./pages/integrations.js")),
    legacyTabIds: ["integrations", "connections", "browser"],
    keywords: "integrations connections mcp tools builder slack",
  }),
  defineSettingsPage({
    id: "api-keys",
    group: "connections",
    order: 20,
    labelKey: label("apiKeys"),
    icon: IconKey,
    component: lazy(() => import("./pages/api-keys.js")),
    legacyTabIds: ["keys", "secrets"],
    keywords: "api keys secrets credentials tokens vault",
  }),
  defineSettingsPage({
    id: "model",
    group: "agent",
    order: 10,
    labelKey: label("model"),
    icon: IconCpu,
    component: lazy(() => import("./pages/model.js")),
    legacyTabIds: ["agent", "agent:overview", "providers"],
    keywords: "model llm provider default model max iterations limits",
  }),
  defineSettingsPage({
    id: "instructions",
    group: "agent",
    order: 20,
    labelKey: label("instructions"),
    icon: IconFileText,
    component: lazy(() => import("./pages/instructions.js")),
    legacyTabIds: ["agent:resources:instructions"],
    keywords: "instructions agents md behavior",
  }),
  defineSettingsPage({
    id: "memory",
    group: "agent",
    order: 30,
    labelKey: label("memory"),
    icon: IconNotebook,
    component: lazy(() => import("./pages/memory.js")),
    legacyTabIds: ["agent:resources:memory", "agent:resources:learnings"],
    keywords: "memory learnings personalization",
    searchEntries: [
      {
        id: "learnings",
        labelKey: "agentChat.settingsShell.learnings",
        keywords: "learnings feedback memory",
        anchor: "learnings",
      },
    ],
  }),
  defineSettingsPage({
    id: "skills",
    group: "agent",
    order: 40,
    labelKey: label("skills"),
    icon: IconBolt,
    component: lazy(() => import("./pages/skills.js")),
    legacyTabIds: ["agent:resources:skills"],
    keywords: "skills capabilities",
  }),
  defineSettingsPage({
    id: "files",
    group: "agent",
    order: 50,
    labelKey: label("files"),
    icon: IconFolder,
    component: lazy(() => import("./pages/files.js")),
    legacyTabIds: ["agent:resources", "agent:resources:files"],
    keywords: "files uploads documents context resources",
  }),
  defineSettingsPage({
    id: "sub-agents",
    group: "agent",
    order: 60,
    labelKey: label("subAgents"),
    icon: IconTopologyRing2,
    component: lazy(() => import("./pages/sub-agents.js")),
    legacyTabIds: [
      "agent:agents",
      "agent:directory",
      "agent:resources:agents",
      "agent:resources:remote-agents",
    ],
    keywords: "sub-agents custom agents remote agents a2a directory delegate",
  }),
  defineSettingsPage({
    id: "org",
    group: "organization",
    order: 10,
    labelKey: label("orgGeneral"),
    icon: IconBuilding,
    component: lazy(() => import("./pages/org.js")),
    legacyTabIds: ["organization", "team"],
    keywords: "organization org team name",
  }),
  defineSettingsPage({
    id: "members",
    group: "organization",
    order: 20,
    labelKey: label("members"),
    icon: IconUsers,
    component: lazy(() => import("./pages/members.js")),
    keywords: "members invites roles people collaborators groups",
    searchEntries: [
      {
        id: "invite-members",
        labelKey: "org.inviteMembers",
        keywords: "invite add people email csv",
        anchor: "members",
      },
      {
        id: "member-roles",
        labelKey: "agentChat.settingsOrg.search.roles",
        keywords: "roles role admin owner member change remove",
        anchor: "members",
      },
      {
        id: "groups",
        labelKey: "org.groups",
        keywords: "groups teams app access",
        anchor: "groups",
      },
    ],
  }),
  defineSettingsPage({
    id: "usage",
    group: "organization",
    order: 30,
    labelKey: label("usage"),
    icon: IconChartBar,
    component: lazy(() => import("./pages/usage.js")),
    legacyTabIds: ["usage"],
    keywords: "usage tokens cost spend billing credits",
  }),
  defineSettingsPage({
    id: "auth",
    group: "organization",
    order: 40,
    labelKey: label("auth"),
    icon: IconLockAccess,
    visible: canManageOrganizationPages,
    component: lazy(() => import("./pages/auth.js")),
    keywords: "authentication sign-in sso saml oidc scim domain",
    searchEntries: [
      {
        id: "organization-sign-in",
        labelKey: "org.sso.signIn",
        keywords: "require enforce google sso provider",
        anchor: "organization-sign-in",
      },
      {
        id: "sso",
        labelKey: "org.sso.title",
        keywords: "sso saml oidc okta identity provider",
        anchor: "organization-sso",
      },
      {
        id: "scim",
        labelKey: "org.scim.title",
        keywords: "scim directory provisioning sync",
        anchor: "organization-scim",
      },
      {
        id: "email-domain",
        labelKey: "agentChat.settingsOrg.search.domainAutoJoin",
        keywords: "domain auto-join email join automatically",
        anchor: "email-domain",
      },
    ],
  }),
  defineSettingsPage({
    id: "apps",
    group: "organization",
    order: 50,
    labelKey: label("apps"),
    icon: IconApps,
    visible: canManageOrganizationPages,
    component: lazy(() => import("./pages/apps.js")),
    keywords: "apps access privacy workspace apps",
    searchEntries: [
      {
        id: "new-app-privacy",
        labelKey: "org.workspaceAppsDefaultPrivacy",
        keywords: "privacy creator only default visibility",
        anchor: "workspace-app-default-visibility",
      },
    ],
  }),
  defineSettingsPage({
    id: "infra",
    group: "organization",
    order: 60,
    labelKey: label("infra"),
    icon: IconServer,
    visible: canManageOrganizationPages,
    component: lazy(() => import("./pages/infra.js")),
    legacyTabIds: ["workspace"],
    keywords: "infrastructure hosting database storage uploads services",
  }),
  defineSettingsPage({
    id: "audit",
    group: "organization",
    order: 70,
    labelKey: label("audit"),
    icon: IconHistory,
    visible: canManageOrganizationPages,
    component: lazy(() => import("./pages/audit.js")),
    keywords: "audit log history changes",
  }),
  defineSettingsPage({
    id: "app",
    group: "app",
    order: 10,
    labelKey: label("appGeneral"),
    // The shell swaps in the app's own icon for this page.
    icon: IconApps,
    component: lazy(() => import("./pages/app.js")),
    legacyTabIds: ["general"],
  }),
  defineSettingsPage({
    id: "notifications",
    group: "app",
    order: 20,
    labelKey: label("notifications"),
    icon: IconBell,
    visible: (_context, bridge) => Boolean(bridge.tab("notifications")),
    component: lazy(() => import("./pages/notifications.js")),
    legacyTabIds: ["notifications"],
    keywords: "notifications email alerts",
  }),
  defineSettingsPage({
    id: "automations",
    group: "app",
    order: 30,
    labelKey: label("automations"),
    icon: IconClockPlay,
    component: lazy(() => import("./pages/automations.js")),
    legacyTabIds: ["agent:automations"],
    keywords: "automations scheduled events cron jobs tasks",
  }),
  defineSettingsPage({
    id: "channels",
    group: "app",
    order: 40,
    labelKey: label("channels"),
    icon: IconMessages,
    component: lazy(() => import("./pages/channels.js")),
    keywords: "channels slack telegram whatsapp google docs messaging",
  }),
  defineSettingsPage({
    id: "mcp",
    group: "app",
    order: 50,
    labelKey: label("mcp"),
    icon: IconServerBolt,
    component: lazy(() => import("./pages/mcp.js")),
    legacyTabIds: ["mcp"],
    keywords: "mcp server url claude chatgpt cursor codex a2a",
  }),
  defineSettingsPage({
    id: "creative-context",
    group: "app",
    order: 60,
    labelKey: label("creativeContext"),
    icon: IconLibrary,
    visible: (_context, bridge) => Boolean(bridge.tab("library")),
    component: lazy(() => import("./pages/creative-context.js")),
    legacyTabIds: ["library"],
    keywords: "creative context library sources packs brand",
  }),
  defineSettingsPage({
    id: "labs",
    group: "footer",
    order: 10,
    labelKey: label("labs"),
    icon: IconFlask,
    component: lazy(() => import("./pages/labs.js")),
    legacyTabIds: ["labs", "experiments"],
    keywords: "labs experimental unstable beta",
  }),
  defineSettingsPage({
    id: "whats-new",
    group: "footer",
    order: 20,
    labelKey: label("whatsNew"),
    icon: IconNews,
    visible: (_context, bridge) => bridge.whatsNew != null,
    component: lazy(() => import("./pages/whats-new.js")),
    legacyTabIds: ["whats-new", "changelog", "updates"],
    keywords: "whats new changelog updates releases",
  }),
];

export const BridgedTabSettingsPage = lazy(
  () => import("./pages/bridged-tab.js"),
);
