packages:
  - "packages/*"
  - "templates/*"
onlyBuiltDependencies: ["esbuild", "lightningcss", "electron", "@swc/core"]
catalog:
  "@tabler/icons-react": "^3.40.0"
  "@tailwindcss/vite": "^4.1.18"
  "@types/react": "^18.3.23"
  "@types/react-dom": "^18.3.7"
  "@vitejs/plugin-react": "^4.5.2"
  h3: "^1.14.0"
  listhen: "^1.9.1"
  react: "^18.3.1"
  react-dom: "^18.3.1"
  tailwindcss: "^4.1.18"
  tsx: "^4.20.3"
  typescript: "^5.9.2"
  vite: "^8.0.0"
