name = "agent-native-slides"
main = "templates/slides/dist/_worker.js/index.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat_v2"]

[vars]
GA_MEASUREMENT_ID = "G-ESF7FYXGN9"

[assets]
directory = "templates/slides/dist"

[[d1_databases]]
binding = "DB"
database_name = "agent-native-slides"
database_id = "dfa8936b-2ecd-460e-a6ac-2088cf12d701"
