name = "agent-native-starter"
main = "templates/starter/.output/server/index.mjs"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
find_additional_modules = true

[assets]
directory = "templates/starter/.output/public"

[vars]
GA_MEASUREMENT_ID = "G-ESF7FYXGN9"

[[d1_databases]]
binding = "DB"
database_name = "agent-native-starter"
database_id = "0871e970-55cf-482c-93a3-204725da8710"
