name = "agent-native-forms"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
GA_MEASUREMENT_ID = "G-ESF7FYXGN9"

[[d1_databases]]
binding = "DB"
database_name = "agent-native-forms"
database_id = "ea55ebda-4c45-4f15-88c3-379199504dda"
