name = "agent-native-content"
main = "templates/content/.output/server/index.mjs"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
find_additional_modules = true

[assets]
directory = "templates/content/.output/public"

[vars]
GA_MEASUREMENT_ID = "G-ESF7FYXGN9"

[[d1_databases]]
binding = "DB"
database_name = "agent-native-content"
database_id = "e9999bd0-a254-4d46-8f86-dae15228b1e0"
