name = "agent-native-analytics"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
GA_MEASUREMENT_ID = "G-ESF7FYXGN9"

[[d1_databases]]
binding = "DB"
database_name = "agent-native-analytics"
database_id = "a323fbbc-aad3-4f77-bc53-9f9b2673e38a"
