name = "agent-native-slides"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
GA_MEASUREMENT_ID = "G-ESF7FYXGN9"

[[d1_databases]]
binding = "DB"
database_name = "agent-native-slides"
database_id = "dfa8936b-2ecd-460e-a6ac-2088cf12d701"
