name = "agent-native-slides"
main = "templates/slides/.output/server/index.mjs"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
find_additional_modules = true

[assets]
directory = "templates/slides/.output/public"

[vars]
GA_MEASUREMENT_ID = "G-ESF7FYXGN9"

[[d1_databases]]
binding = "DB"
database_name = "agent-native-slides"
database_id = "dfa8936b-2ecd-460e-a6ac-2088cf12d701"
