name = "agent-native-mail"
main = "templates/mail/.output/server/index.mjs"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
no_bundle = true

[assets]
directory = "templates/mail/.output/public"

[vars]
GA_MEASUREMENT_ID = "G-ESF7FYXGN9"

[triggers]
crons = ["* * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "agent-native-mail"
database_id = "5cbb9720-f664-40f7-b38c-a24bfdba4fb8"
