name = "agent-native-videos"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
GA_MEASUREMENT_ID = "G-ESF7FYXGN9"

[[d1_databases]]
binding = "DB"
database_name = "agent-native-videos"
database_id = "a13415ec-0d2e-43da-8fce-5c616646fbce"
