name = "agent-native-starter"
main = "templates/starter/dist/_worker.js/index.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat_v2"]

[vars]
GA_MEASUREMENT_ID = "G-ESF7FYXGN9"

[assets]
directory = "templates/starter/dist"

[[d1_databases]]
binding = "DB"
database_name = "agent-native-starter"
database_id = "0871e970-55cf-482c-93a3-204725da8710"
