// Generated from @tabler/icons 3.44.0. Run node packages/toolkit/scripts/generate-tabler-catalog.ts.
import {
  IconKarate,
  IconKayak,
  IconKerning,
  IconKey,
  IconKeyFilled,
  IconKeyOff,
  IconKeyboard,
  IconKeyboardFilled,
  IconKeyboardHide,
  IconKeyboardOff,
  IconKeyboardShow,
  IconKeyframe,
  IconKeyframeAlignCenter,
  IconKeyframeAlignCenterFilled,
  IconKeyframeAlignHorizontal,
  IconKeyframeAlignHorizontalFilled,
  IconKeyframeAlignVertical,
  IconKeyframeAlignVerticalFilled,
  IconKeyframeFilled,
  IconKeyframes,
  IconKeyframesFilled,
} from "@tabler/icons-react";
export default {
  IconKarate,
  IconKayak,
  IconKerning,
  IconKey,
  IconKeyFilled,
  IconKeyOff,
  IconKeyboard,
  IconKeyboardFilled,
  IconKeyboardHide,
  IconKeyboardOff,
  IconKeyboardShow,
  IconKeyframe,
  IconKeyframeAlignCenter,
  IconKeyframeAlignCenterFilled,
  IconKeyframeAlignHorizontal,
  IconKeyframeAlignHorizontalFilled,
  IconKeyframeAlignVertical,
  IconKeyframeAlignVerticalFilled,
  IconKeyframeFilled,
  IconKeyframes,
  IconKeyframesFilled,
};
