[build]
  command = "pnpm install && NITRO_PRESET=netlify pnpm --filter clips build"
  publish = "templates/clips/dist"
  functions = "templates/clips/.netlify/functions-internal"

[build.environment]
  NITRO_PRESET = "netlify"
