/**
 * Local file sync for the no-login local mode.
 *
 * In local mode, created and updated plans are written to the repo as MDX so
 * that "synced to local files" is literally true and the plan is round-trippable
 * with `import-visual-plan-source` / `patch-visual-plan-source`.
 *
 * Layout (per plan), under the local plans directory:
 *
 *   <dir>/<planId>/plan.mdx
 *   <dir>/<planId>/canvas.mdx          (only when the plan has a canvas board)
 *   <dir>/<planId>/.plan-state.json    (only when present)
 *
 * The directory is, in priority order:
 *   1. `PLAN_LOCAL_DIR` env var (absolute or relative to cwd).
 *   2. `<cwd>/plans` (the running app/template directory in `agent-native dev`).
 *
 * Writes are idempotent: the same plan content always produces the same files.
 * Hosted behavior is unchanged — callers only invoke this when
 * `isLocalPlanRuntime()` is true, and any filesystem error is swallowed so a
 * read-only or sandboxed environment never breaks a plan mutation.
 */

import fs from "node:fs/promises";
import path from "node:path";
import { exportPlanContentToMdxFolder } from "../plan-mdx.js";
import type { PlanContent } from "../../shared/plan-content.js";

export interface LocalPlanWriteInput {
  planId: string;
  title: string;
  brief?: string | null;
  content: PlanContent | null | undefined;
  url?: string;
}

/** Absolute path to the local plans directory for this process. */
export function localPlansDir(): string {
  const configured = process.env.PLAN_LOCAL_DIR;
  if (configured && configured.trim().length > 0) {
    return path.resolve(process.cwd(), configured.trim());
  }
  return path.resolve(process.cwd(), "plans");
}

/** Absolute path to a single plan's local folder. */
export function localPlanFolder(planId: string): string {
  // planId is generated by `newId("plan")` (alphanumeric + underscore), so it
  // is filesystem-safe. Strip any path separators defensively regardless.
  const safeId = planId.replace(/[\\/]/g, "_");
  return path.join(localPlansDir(), safeId);
}

/**
 * Write a plan's MDX folder to the local filesystem. Idempotent and best-effort:
 * filesystem errors are caught and returned as `{ written: false }` so a plan
 * mutation never fails just because the local mirror could not be written.
 */
export async function writePlanLocalFiles(
  input: LocalPlanWriteInput,
): Promise<{ written: boolean; folder: string; files: string[] }> {
  const folder = localPlanFolder(input.planId);
  try {
    const mdx = await exportPlanContentToMdxFolder({
      content: input.content,
      title: input.title,
      brief: input.brief,
      planId: input.planId,
      url: input.url ?? `/plans/${encodeURIComponent(input.planId)}`,
    });

    await fs.mkdir(folder, { recursive: true });
    const written: string[] = [];

    // plan.mdx is always present.
    await fs.writeFile(path.join(folder, "plan.mdx"), mdx["plan.mdx"], "utf-8");
    written.push("plan.mdx");

    // canvas.mdx and .plan-state.json are optional.
    if (mdx["canvas.mdx"]) {
      await fs.writeFile(
        path.join(folder, "canvas.mdx"),
        mdx["canvas.mdx"],
        "utf-8",
      );
      written.push("canvas.mdx");
    } else {
      // Remove a stale canvas file if the plan no longer has a board, so the
      // mirror stays an accurate round-trip of the current content.
      await fs.rm(path.join(folder, "canvas.mdx"), { force: true });
    }

    if (mdx[".plan-state.json"]) {
      await fs.writeFile(
        path.join(folder, ".plan-state.json"),
        mdx[".plan-state.json"],
        "utf-8",
      );
      written.push(".plan-state.json");
    } else {
      await fs.rm(path.join(folder, ".plan-state.json"), { force: true });
    }

    return { written: true, folder, files: written };
  } catch {
    // Read-only FS, permissions, or a sandboxed runtime: never break the
    // underlying plan operation just because the local mirror failed.
    return { written: false, folder, files: [] };
  }
}
