import {
  DEFAULT_LOCALE,
  resolveLocaleFromCandidates,
  type LocaleCode,
} from "../localization/shared.js";

/**
 * The native sign-in surfaces use the same copy keys as the hosted onboarding
 * form. Keep this browser-safe subset here so Electron and mobile do not load
 * the server HTML renderer or grow a second auth vocabulary.
 */
export interface NativeAuthCopy {
  googleButton: string;
  dividerOr: string;
  email: string;
  emailPlaceholder: string;
  password: string;
  confirmPassword: string;
  enterPasswordPlaceholder: string;
  forgotPassword: string;
  sendMagicLink: string;
  magicLinkSent: string;
  magicLinkSentCopy: string;
  magicLinkFailed: string;
  usePasswordInstead: string;
  backToMagicLink: string;
  signIn: string;
  back: string;
  close: string;
  sending: string;
  signingIn: string;
  invalidEmail: string;
  invalidLogin: string;
  failedToConnect: string;
  googleNeverFinished: string;
  checking: string;
}

export const NATIVE_AUTH_COPY: Record<LocaleCode, NativeAuthCopy> = {
  "en-US": {
    googleButton: "Sign in with Google",
    dividerOr: "or",
    email: "Email",
    emailPlaceholder: "you@example.com",
    password: "Password",
    confirmPassword: "Confirm password",
    enterPasswordPlaceholder: "Enter password",
    forgotPassword: "Forgot password?",
    sendMagicLink: "Continue",
    magicLinkSent: "Check your email",
    magicLinkSentCopy: "We sent a secure sign-in link to",
    magicLinkFailed:
      "We couldn't send a sign-in link. Check your email and try again.",
    usePasswordInstead: "Use a password instead",
    backToMagicLink: "Use a sign-in link instead",
    signIn: "Sign in",
    back: "Back",
    close: "Close",
    sending: "Sending...",
    signingIn: "Signing in…",
    invalidEmail: "Enter a valid email address, like you@example.com.",
    invalidLogin: "The email or password is incorrect.",
    failedToConnect: "We couldn't connect. Please try again.",
    googleNeverFinished:
      "Google sign-in did not finish. Check the Google OAuth redirect URI and server logs for [agent-native][google-oauth].",
    checking: "Checking...",
  },
  "zh-CN": {
    googleButton: "使用 Google 登录",
    dividerOr: "或",
    email: "电子邮箱",
    emailPlaceholder: "you@example.com",
    password: "密码",
    confirmPassword: "确认密码",
    enterPasswordPlaceholder: "输入密码",
    forgotPassword: "忘记密码？",
    sendMagicLink: "继续",
    magicLinkSent: "检查你的邮箱",
    magicLinkSentCopy: "我们已向以下邮箱发送安全登录链接：",
    magicLinkFailed: "无法发送登录链接。",
    usePasswordInstead: "改用密码",
    backToMagicLink: "改用登录链接",
    signIn: "登录",
    back: "返回",
    close: "关闭",
    sending: "正在发送...",
    signingIn: "正在登录…",
    invalidEmail: "请输入有效邮箱地址，例如 you@example.com。",
    invalidLogin: "邮箱或密码无效",
    failedToConnect: "连接失败。请重试。",
    googleNeverFinished:
      "Google 登录未完成。请检查 Google OAuth 重定向 URI 和服务器日志中的 [agent-native][google-oauth]。",
    checking: "正在检查...",
  },
  "zh-TW": {
    googleButton: "使用 Google 登入",
    dividerOr: "或",
    email: "電子郵件",
    emailPlaceholder: "you@example.com",
    password: "密碼",
    confirmPassword: "確認密碼",
    enterPasswordPlaceholder: "輸入密碼",
    forgotPassword: "忘記密碼？",
    sendMagicLink: "繼續",
    magicLinkSent: "檢查你的電子郵件",
    magicLinkSentCopy: "我們已向以下電子郵件寄送安全登入連結：",
    magicLinkFailed: "無法寄送登入連結。",
    usePasswordInstead: "改用密碼",
    backToMagicLink: "改用登入連結",
    signIn: "登入",
    back: "返回",
    close: "關閉",
    sending: "正在寄送...",
    signingIn: "正在登入...",
    invalidEmail: "請輸入有效的電子郵件地址，例如 you@example.com。",
    invalidLogin: "電子郵件或密碼無效",
    failedToConnect: "連線失敗。請重試。",
    googleNeverFinished:
      "Google 登入未完成。請檢查 Google OAuth 重新導向 URI，以及伺服器記錄中的 [agent-native][google-oauth]。",
    checking: "正在檢查...",
  },
  "es-ES": {
    googleButton: "Iniciar sesión con Google",
    dividerOr: "o",
    email: "Email",
    emailPlaceholder: "you@example.com",
    password: "Contraseña",
    confirmPassword: "Confirmar contraseña",
    enterPasswordPlaceholder: "Introduce la contraseña",
    forgotPassword: "¿Olvidaste tu contraseña?",
    sendMagicLink: "Continuar",
    magicLinkSent: "Revisa tu email",
    magicLinkSentCopy: "Enviamos un enlace seguro a",
    magicLinkFailed: "No se pudo enviar el enlace de inicio de sesión.",
    usePasswordInstead: "Usar una contraseña",
    backToMagicLink: "Usar un enlace de inicio de sesión",
    signIn: "Iniciar sesión",
    back: "Volver",
    close: "Cerrar",
    sending: "Enviando...",
    signingIn: "Iniciando sesión…",
    invalidEmail: "Introduce un email válido, como you@example.com.",
    invalidLogin: "Email o contraseña no válidos",
    failedToConnect: "No se pudo conectar. Inténtalo de nuevo.",
    googleNeverFinished:
      "El inicio de sesión con Google no terminó. Comprueba el URI de redirección de Google OAuth y los logs del servidor para [agent-native][google-oauth].",
    checking: "Comprobando...",
  },
  "fr-FR": {
    googleButton: "Se connecter avec Google",
    dividerOr: "ou",
    email: "E-mail",
    emailPlaceholder: "you@example.com",
    password: "Mot de passe",
    confirmPassword: "Confirmer le mot de passe",
    enterPasswordPlaceholder: "Saisir le mot de passe",
    forgotPassword: "Mot de passe oublié ?",
    sendMagicLink: "Continuer",
    magicLinkSent: "Vérifiez votre e-mail",
    magicLinkSentCopy: "Nous avons envoyé un lien sécurisé à",
    magicLinkFailed: "Impossible d'envoyer le lien de connexion.",
    usePasswordInstead: "Utiliser un mot de passe",
    backToMagicLink: "Utiliser un lien de connexion",
    signIn: "Connexion",
    back: "Retour",
    close: "Fermer",
    sending: "Envoi...",
    signingIn: "Connexion…",
    invalidEmail: "Saisissez une adresse e-mail valide, comme you@example.com.",
    invalidLogin: "E-mail ou mot de passe invalide",
    failedToConnect: "Connexion impossible. Veuillez réessayer.",
    googleNeverFinished:
      "La connexion Google n'a pas abouti. Vérifiez l'URI de redirection Google OAuth et les logs serveur pour [agent-native][google-oauth].",
    checking: "Vérification...",
  },
  "de-DE": {
    googleButton: "Mit Google anmelden",
    dividerOr: "oder",
    email: "E-Mail",
    emailPlaceholder: "you@example.com",
    password: "Passwort",
    confirmPassword: "Passwort bestätigen",
    enterPasswordPlaceholder: "Passwort eingeben",
    forgotPassword: "Passwort vergessen?",
    sendMagicLink: "Weiter",
    magicLinkSent: "Prüfe deine E-Mail",
    magicLinkSentCopy: "Wir haben einen sicheren Anmeldelink gesendet an",
    magicLinkFailed: "Anmeldelink konnte nicht gesendet werden.",
    usePasswordInstead: "Stattdessen Passwort verwenden",
    backToMagicLink: "Stattdessen Anmeldelink verwenden",
    signIn: "Anmelden",
    back: "Zurück",
    close: "Schließen",
    sending: "Senden...",
    signingIn: "Anmeldung…",
    invalidEmail: "Gib eine gültige E-Mail-Adresse ein, z. B. you@example.com.",
    invalidLogin: "E-Mail oder Passwort ungültig",
    failedToConnect: "Verbindung fehlgeschlagen. Bitte erneut versuchen.",
    googleNeverFinished:
      "Die Google-Anmeldung wurde nicht abgeschlossen. Prüfe die Google-OAuth-Redirect-URI und Serverlogs für [agent-native][google-oauth].",
    checking: "Prüfen...",
  },
  "ja-JP": {
    googleButton: "Google でサインイン",
    dividerOr: "または",
    email: "メール",
    emailPlaceholder: "you@example.com",
    password: "パスワード",
    confirmPassword: "パスワードを確認",
    enterPasswordPlaceholder: "パスワードを入力",
    forgotPassword: "パスワードをお忘れですか？",
    sendMagicLink: "続行",
    magicLinkSent: "メールを確認してください",
    magicLinkSentCopy: "安全なサインインリンクを送信しました：",
    magicLinkFailed: "サインインリンクを送信できませんでした。",
    usePasswordInstead: "パスワードを使用する",
    backToMagicLink: "サインインリンクを使用する",
    signIn: "サインイン",
    back: "戻る",
    close: "閉じる",
    sending: "送信中...",
    signingIn: "サインイン中…",
    invalidEmail:
      "you@example.com のような有効なメールアドレスを入力してください。",
    invalidLogin: "メールまたはパスワードが正しくありません",
    failedToConnect: "接続できませんでした。もう一度お試しください。",
    googleNeverFinished:
      "Google サインインが完了しませんでした。Google OAuth リダイレクト URI と [agent-native][google-oauth] のサーバーログを確認してください。",
    checking: "確認中...",
  },
  "ko-KR": {
    googleButton: "Google로 로그인",
    dividerOr: "또는",
    email: "이메일",
    emailPlaceholder: "you@example.com",
    password: "비밀번호",
    confirmPassword: "비밀번호 확인",
    enterPasswordPlaceholder: "비밀번호 입력",
    forgotPassword: "비밀번호를 잊으셨나요?",
    sendMagicLink: "계속",
    magicLinkSent: "이메일을 확인하세요",
    magicLinkSentCopy: "안전한 로그인 링크를 보냈습니다:",
    magicLinkFailed: "로그인 링크를 보낼 수 없습니다.",
    usePasswordInstead: "비밀번호 사용",
    backToMagicLink: "로그인 링크 사용",
    signIn: "로그인",
    back: "뒤로",
    close: "닫기",
    sending: "보내는 중...",
    signingIn: "로그인 중…",
    invalidEmail: "you@example.com 같은 올바른 이메일 주소를 입력하세요.",
    invalidLogin: "이메일 또는 비밀번호가 올바르지 않습니다",
    failedToConnect: "연결하지 못했습니다. 다시 시도하세요.",
    googleNeverFinished:
      "Google 로그인이 완료되지 않았습니다. Google OAuth 리디렉션 URI와 [agent-native][google-oauth] 서버 로그를 확인하세요.",
    checking: "확인 중...",
  },
  "pt-BR": {
    googleButton: "Entrar com Google",
    dividerOr: "ou",
    email: "Email",
    emailPlaceholder: "you@example.com",
    password: "Senha",
    confirmPassword: "Confirmar senha",
    enterPasswordPlaceholder: "Digite a senha",
    forgotPassword: "Esqueceu a senha?",
    sendMagicLink: "Continuar",
    magicLinkSent: "Confira seu email",
    magicLinkSentCopy: "Enviamos um link seguro para",
    magicLinkFailed: "Não foi possível enviar o link de acesso.",
    usePasswordInstead: "Usar uma senha",
    backToMagicLink: "Usar um link de acesso",
    signIn: "Entrar",
    back: "Voltar",
    close: "Fechar",
    sending: "Enviando...",
    signingIn: "Entrando…",
    invalidEmail: "Digite um email válido, como you@example.com.",
    invalidLogin: "Email ou senha inválidos",
    failedToConnect: "Não foi possível conectar. Tente novamente.",
    googleNeverFinished:
      "O login com Google não terminou. Confira o URI de redirecionamento do Google OAuth e os logs do servidor para [agent-native][google-oauth].",
    checking: "Verificando...",
  },
  "hi-IN": {
    googleButton: "Google से साइन इन करें",
    dividerOr: "या",
    email: "ईमेल",
    emailPlaceholder: "you@example.com",
    password: "पासवर्ड",
    confirmPassword: "पासवर्ड की पुष्टि करें",
    enterPasswordPlaceholder: "पासवर्ड दर्ज करें",
    forgotPassword: "पासवर्ड भूल गए?",
    sendMagicLink: "जारी रखें",
    magicLinkSent: "अपना ईमेल देखें",
    magicLinkSentCopy: "हमने सुरक्षित साइन-इन लिंक यहां भेजा है:",
    magicLinkFailed: "साइन-इन लिंक नहीं भेजा जा सका।",
    usePasswordInstead: "पासवर्ड का उपयोग करें",
    backToMagicLink: "साइन-इन लिंक का उपयोग करें",
    signIn: "साइन इन",
    back: "वापस",
    close: "बंद करें",
    sending: "भेजा जा रहा है...",
    signingIn: "साइन इन हो रहा है…",
    invalidEmail: "एक मान्य ईमेल पता दर्ज करें, जैसे you@example.com.",
    invalidLogin: "ईमेल या पासवर्ड अमान्य है",
    failedToConnect: "कनेक्ट नहीं हो सका। कृपया फिर कोशिश करें।",
    googleNeverFinished:
      "Google साइन इन पूरा नहीं हुआ। Google OAuth redirect URI और [agent-native][google-oauth] के server logs देखें।",
    checking: "जांच हो रही है...",
  },
  "ar-SA": {
    googleButton: "تسجيل الدخول باستخدام Google",
    dividerOr: "أو",
    email: "البريد الإلكتروني",
    emailPlaceholder: "you@example.com",
    password: "كلمة المرور",
    confirmPassword: "تأكيد كلمة المرور",
    enterPasswordPlaceholder: "أدخل كلمة المرور",
    forgotPassword: "هل نسيت كلمة المرور؟",
    sendMagicLink: "متابعة",
    magicLinkSent: "تحقق من بريدك الإلكتروني",
    magicLinkSentCopy: "أرسلنا رابط تسجيل دخول آمنًا إلى",
    magicLinkFailed: "تعذر إرسال رابط تسجيل الدخول.",
    usePasswordInstead: "استخدام كلمة مرور بدلًا من ذلك",
    backToMagicLink: "استخدام رابط تسجيل الدخول بدلًا من ذلك",
    signIn: "تسجيل الدخول",
    back: "رجوع",
    close: "إغلاق",
    sending: "جارٍ الإرسال...",
    signingIn: "جارٍ تسجيل الدخول…",
    invalidEmail: "أدخل بريدًا إلكترونيًا صالحًا، مثل you@example.com.",
    invalidLogin: "البريد الإلكتروني أو كلمة المرور غير صحيحة",
    failedToConnect: "تعذر الاتصال. حاول مرة أخرى.",
    googleNeverFinished:
      "لم يكتمل تسجيل الدخول عبر Google. تحقق من URI إعادة التوجيه في Google OAuth وسجلات الخادم لـ [agent-native][google-oauth].",
    checking: "جارٍ التحقق...",
  },
};

export function resolveNativeAuthCopy(locale: unknown): NativeAuthCopy {
  const resolvedLocale = resolveLocaleFromCandidates([locale]);
  return NATIVE_AUTH_COPY[resolvedLocale] ?? NATIVE_AUTH_COPY[DEFAULT_LOCALE];
}
