export interface SearchEntry {
  page: string
  path: string
  section: string
  sectionId: string
  text: string
}

export const searchIndex: SearchEntry[] = [
  // Getting Started
  { page: 'Getting Started', path: '/docs', section: 'Installation', sectionId: 'installation', text: 'Create a new project: npx @agent-native/core create my-app' },
  { page: 'Getting Started', path: '/docs', section: 'Project Structure', sectionId: 'project-structure', text: 'Every agent-native app follows the same convention: client/ React frontend Vite SPA App.tsx entry point components UI components lib/utils.ts cn() utility server/ Express backend index.ts createAppServer() node-build.ts production entry point shared/ isomorphic code client and server scripts/ agent-callable scripts run.ts script dispatcher data/ app data files watched by SSE' },
  { page: 'Getting Started', path: '/docs', section: 'Vite Configuration', sectionId: 'vite-configuration', text: 'Two config files client SPA and server build. defineConfig() sets up React SWC path aliases @/ client/ @shared/ shared/ fs restrictions and the Express dev plugin. vite.config.ts vite.config.server.ts defineServerConfig' },
  { page: 'Getting Started', path: '/docs', section: 'TypeScript & Tailwind', sectionId: 'typescript-tailwind', text: 'tsconfig.json extends @agent-native/core/tsconfig.base.json tailwind.config.ts import preset from @agent-native/core/tailwind presets content client/**/*.{ts,tsx}' },
  { page: 'Getting Started', path: '/docs', section: 'Subpath Exports', sectionId: 'subpath-exports', text: '@agent-native/core exports createServer createFileWatcher createSSEHandler createProductionServer runScript parseArgs loadEnv fail agentChat sendToAgentChat useAgentChatGenerating useFileWatcher cn. @agent-native/core/vite exports defineConfig defineServerConfig. @agent-native/core/tailwind Tailwind preset HSL colors shadcn/ui tokens animations. @agent-native/core/adapters/firestore FileSync threeWayMerge loadSyncConfig' },
  { page: 'Getting Started', path: '/docs', section: 'Architecture Principles', sectionId: 'architecture-principles', text: 'Files as database all app state lives in files. Both UI and agent read/write the same files. All AI through agent chat no inline LLM calls. UI delegates to the AI via sendToAgentChat(). Scripts for agent ops pnpm script dispatches to callable script files. Bidirectional SSE events file watcher keeps UI in sync with agent changes in real-time. Agent can update code the agent modifies the app itself.' },

  // Server
  { page: 'Server', path: '/docs/server', section: 'createServer()', sectionId: 'createserver', text: 'Creates a pre-configured Express app with standard middleware. Includes cors json limit 50mb urlencoded /api/ping. Options: cors CorsOptions or false CORS config pass false to disable. jsonLimit string JSON body parser limit default 50mb. pingMessage string health check response default env PING_MESSAGE or pong. disablePing boolean disable /api/ping endpoint.' },
  { page: 'Server', path: '/docs/server', section: 'createFileWatcher()', sectionId: 'createfilewatcher', text: 'Creates a chokidar file watcher for real-time file change detection. createFileWatcher("./data") watcher emits all events eventName filePath. Options: ignored any glob patterns or regex to ignore. emitInitial boolean emit events for initial file scan default false.' },
  { page: 'Server', path: '/docs/server', section: 'createSSEHandler()', sectionId: 'createssehandler', text: 'Creates an Express route handler that streams file changes as Server-Sent Events. Each SSE message is JSON type change path data/file.json. Options: extraEmitters additional EventEmitters to stream. app.get("/api/events", createSSEHandler(watcher))' },
  { page: 'Server', path: '/docs/server', section: 'createProductionServer()', sectionId: 'createproductionserver', text: 'Starts a production server with SPA fallback and graceful shutdown. server/node-build.ts createProductionServer(createAppServer()). Options: port number or string listen port default env PORT or 3000. spaDir string built SPA directory default dist/spa. appName string name for log messages default Agent-Native.' },

  // Client
  { page: 'Client', path: '/docs/client', section: 'sendToAgentChat()', sectionId: 'sendtoagentchat', text: 'Send a message to the agent chat via postMessage. Used to delegate AI tasks from UI interactions. Auto-submit a prompt with hidden context. Prefill without submitting user reviews first. sendToAgentChat({ message, context, submit })' },
  { page: 'Client', path: '/docs/client', section: 'AgentChatMessage', sectionId: 'agentchatmessage', text: 'AgentChatMessage options: message string the visible prompt sent to the chat. context string hidden context appended not shown in chat UI. submit boolean true auto-submit false prefill only. projectSlug string optional project slug. preset string optional preset name. referenceImagePaths string array optional reference image paths.' },
  { page: 'Client', path: '/docs/client', section: 'useAgentChatGenerating()', sectionId: 'useagentchatgenerating', text: 'React hook that wraps sendToAgentChat with loading state tracking. isGenerating turns true on send false when the builder.fusion.chatRunning event fires with isRunning false.' },
  { page: 'Client', path: '/docs/client', section: 'useFileWatcher()', sectionId: 'usefilewatcher', text: 'React hook that connects to the SSE endpoint and invalidates react-query caches on file changes. Options: queryClient React-query client for cache invalidation. queryKeys string array query key prefixes to invalidate default file fileTree. eventsUrl string SSE endpoint URL default /api/events. onEvent callback for each SSE event.' },
  { page: 'Client', path: '/docs/client', section: 'cn()', sectionId: 'cn', text: 'Utility for merging class names clsx plus tailwind-merge. cn("px-4 py-2 rounded", isActive && "bg-primary text-primary-foreground", className)' },

  // Scripts
  { page: 'Scripts', path: '/docs/scripts', section: 'Script Dispatcher', sectionId: 'script-dispatcher', text: 'The script system lets you create scripts that agents can invoke via pnpm script name. Each script is a TypeScript file that exports a default async function. scripts/run.ts dispatcher one-time setup runScript(). scripts/hello.ts example script.' },
  { page: 'Scripts', path: '/docs/scripts', section: 'parseArgs()', sectionId: 'parseargs', text: 'Parse CLI arguments in --key value or --key=value format. parseArgs(["--name", "Steve", "--verbose", "--count=3"]) returns { name: "Steve", verbose: "true", count: "3" }' },
  { page: 'Scripts', path: '/docs/scripts', section: 'Shared Agent Chat', sectionId: 'shared-agent-chat', text: 'Isomorphic chat bridge that works in both browser and Node.js. agentChat.submit("Generate a report"). agentChat.prefill("Draft an email", contextData). agentChat.send({ message, context, submit }). In the browser messages are sent via window.postMessage(). In Node.js scripts they use the BUILDER_PARENT_MESSAGE stdout format.' },
  { page: 'Scripts', path: '/docs/scripts', section: 'Utility Functions', sectionId: 'utility-functions', text: 'loadEnv(path?) load .env from project root or custom path. camelCaseArgs(args) convert kebab-case keys to camelCase. isValidPath(p) validate relative path no traversal no absolute. isValidProjectPath(p) validate project slug. ensureDir(dir) mkdir -p helper. fail(message) print error to stderr and exit(1).' },
  { page: 'Scripts', path: '/docs/scripts', section: 'Firestore Adapter', sectionId: 'firestore-adapter', text: 'Bidirectional file sync across instances. import FileSync from @agent-native/core/adapters/firestore. Features startup sync real-time Firestore listeners chokidar file watchers three-way merge with LCS-based conflict resolution and .conflict sidecar files for unresolvable conflicts.' },

  // Harnesses
  { page: 'Harnesses', path: '/docs/harnesses', section: 'Claude Code Harness', sectionId: 'claude-code-harness', text: 'Open source ships with @agent-native/harness-claude-code. Runs locally xterm.js terminal on the left your app iframe on the right. Powered by Claude Code CLI via a real PTY node-pty. Settings panel for launch flags --dangerously-skip-permissions --resume --verbose custom flags. Restart button to relaunch with new settings. Auto-detects when Claude finishes generating and notifies the app. Best for solo development local testing open-source projects. Quick start pnpm dev:harness' },
  { page: 'Harnesses', path: '/docs/harnesses', section: 'Builder Harness', sectionId: 'builder-harness', text: 'Provided by Builder.io available at builder.io. Runs locally or in the cloud. Real-time collaboration multiple users can watch interact simultaneously. Visual editing capabilities alongside the AI agent. Parallel agent execution for faster iteration. Best for teams production deployments visual editing real-time collaboration.' },
  { page: 'Harnesses', path: '/docs/harnesses', section: 'Feature Comparison', sectionId: 'feature-comparison', text: 'Local development both yes. Cloud/remote Claude Code no Builder yes. Real-time collaboration Claude Code no Builder yes. Visual editing Claude Code no Builder yes. Parallel agents Claude Code no Builder yes. Agent chat bridge both yes. File watcher SSE both yes. Script system both yes. Open source Claude Code yes Builder no. Cost Claude Code free BYOK Builder Builder.io plan.' },
  { page: 'Harnesses', path: '/docs/harnesses', section: 'How It Works', sectionId: 'how-it-works', text: 'Both harnesses support the same core agent-native protocol. postMessage bridge app sends builder.submitChat messages up to the harness. Chat running events harness sends builder.fusion.chatRunning events down to the app. File watching SSE endpoint keeps UI in sync when the agent modifies files. Script system pnpm script dispatches to callable scripts. Your app code is identical regardless of which harness you use.' },
]
