[build]
  command = "pnpm install && NITRO_PRESET=netlify pnpm --filter forms build"
  publish = "templates/forms/dist"
  functions = "templates/forms/.netlify/functions-internal"

[build.environment]
  NITRO_PRESET = "netlify"
