[build]
  command = "pnpm install && pnpm --filter macros exec drizzle-kit push --force && NITRO_PRESET=netlify pnpm --filter macros build"
  publish = "templates/macros/dist"
  functions = "templates/macros/.netlify/functions-internal"

[build.environment]
  NITRO_PRESET = "netlify"
