import type { DesignSystemCreationLabels } from "./types.js";

export function designSystemCreationLabels(
  t: (key: string, values?: Record<string, string>) => string,
): DesignSystemCreationLabels {
  return {
    title: t("systemCreation.title"),
    sourcesTitle: t("systemCreation.sourcesTitle"),
    name: t("systemCreation.name"),
    startFrom: t("systemCreation.startFrom"),
    fresh: t("systemCreation.fresh"),
    freshDescription: t("systemCreation.freshDescription"),
    references: t("systemCreation.references"),
    referencesDescription: t("systemCreation.referencesDescription"),
    continue: t("systemCreation.continue"),
    back: t("systemCreation.back"),
    cancel: t("systemCreation.cancel"),
    create: t("systemCreation.create"),
    addToSystem: t("systemCreation.addToSystem"),
    add: t("systemCreation.add"),
    added: t("systemCreation.added"),
    website: t("systemCreation.website"),
    files: t("systemCreation.files"),
    figma: t("systemCreation.figma"),
    websiteUrl: t("systemCreation.websiteUrl"),
    figmaUrl: t("systemCreation.figmaUrl"),
    chooseFiles: t("systemCreation.chooseFiles"),
    fileTypes: t("systemCreation.fileTypes"),
    uploading: t("systemCreation.uploading"),
    pending: t("systemCreation.pending"),
    retry: t("systemCreation.retry"),
    submitting: t("systemCreation.submitting"),
    remove: (name) => t("systemCreation.remove", { name }),
    nameRequired: t("systemCreation.nameRequired"),
    sourceRequired: t("systemCreation.sourceRequired"),
    invalidWebsite: t("systemCreation.invalidWebsite"),
    invalidFigma: t("systemCreation.invalidFigma"),
    unsupportedFile: t("systemCreation.unsupportedFile"),
    emptyFile: t("systemCreation.emptyFile"),
    fileTooLarge: t("systemCreation.fileTooLarge"),
    uploadFailed: t("systemCreation.uploadFailed"),
    submitFailed: t("systemCreation.submitFailed"),
  };
}
