import type { Config } from "@react-router/dev/config";

export default {
  appDirectory: "app",
  ssr: true,
  routeDiscovery: { mode: "initial" },
  prerender: [
    "/",
    "/docs",
    "/docs/what-is-agent-native",
    "/docs/faq",
    "/docs/server",
    "/docs/client",
    "/docs/actions",
    "/docs/deployment",
    "/docs/file-sync",
    "/docs/key-concepts",
    "/docs/harnesses",
    "/docs/creating-templates",
    "/docs/cli-adapters",
    "/docs/database-adapters",
    "/download",
    "/templates",
    "/templates/analytics",
    "/templates/calendar",
    "/templates/content",
    "/templates/mail",
    "/templates/slides",
    "/templates/video",
  ],
} satisfies Config;
