import path from "node:path";

import { readFileSafe, relPosix, walk } from "./scan-utils.js";

export const STORE_REGISTRY_FILE = "src/db/store-registry.generated.ts";

const DEFINE_STORE_RE =
  /export\s+const\s+([A-Za-z_$][\w$]*)\s*=\s*defineStore\(\s*\{\s*id:\s*"([^"]+)"/g;
const SOURCE_EXTENSIONS = /\.(?:ts|tsx|mts|cts)$/i;
const TEST_FILE = /\.(?:spec|test)\.(?:ts|tsx|mts|cts)$/i;

export interface DiscoveredStore {
  id: string;
  exportName: string;
  file: string;
}

export function discoverStores(coreDir: string): DiscoveredStore[] {
  const stores: DiscoveredStore[] = [];
  for (const file of walk(path.join(coreDir, "src"))) {
    if (!SOURCE_EXTENSIONS.test(file) || TEST_FILE.test(file)) continue;
    const rel = relPosix(coreDir, file);
    if (rel === STORE_REGISTRY_FILE || rel.startsWith("src/templates/")) {
      continue;
    }
    const source = readFileSafe(file);
    if (source === null || !source.includes("defineStore(")) continue;
    for (const match of source.matchAll(DEFINE_STORE_RE)) {
      stores.push({ exportName: match[1], id: match[2], file: rel });
    }
  }
  return stores.sort((a, b) => a.id.localeCompare(b.id));
}

export function renderStoreRegistry(stores: DiscoveredStore[]): string {
  const registryDir = path.posix.dirname(STORE_REGISTRY_FILE);
  const entries = stores.map((store) => {
    let spec = path.posix
      .relative(registryDir, store.file)
      .replace(/\.tsx?$/, ".js");
    if (!spec.startsWith(".")) spec = `./${spec}`;
    return `  [\n    "${store.id}",\n    () => import("${spec}").then((m) => m.${store.exportName}),\n  ],`;
  });
  return [
    "// Generated by scripts/gen-store-registry.ts from every `defineStore()` export.",
    "// Do not edit. Run `pnpm gen:store-registry` after adding or removing a store.",
    'import type { Store } from "./store-registry.js";',
    "",
    "export const FRAMEWORK_STORES: ReadonlyArray<",
    "  readonly [id: string, load: () => Promise<Store>]",
    "> = [",
    ...entries,
    "];",
    "",
  ].join("\n");
}

export function findDuplicateStoreIds(stores: DiscoveredStore[]): string[] {
  const seen = new Map<string, number>();
  for (const store of stores) seen.set(store.id, (seen.get(store.id) ?? 0) + 1);
  return [...seen].filter(([, count]) => count > 1).map(([id]) => id);
}

export function normalizeGenerated(source: string): string {
  return source.replace(/\s+/g, "").replace(/,([\])])/g, "$1");
}
