/** Frozen cryptographic suite identifiers and interoperability limits. */
export const E2EE_SUITE_ID = "anc/v1" as const;
export const E2EE_CANONICAL_ENCODING = "cbor-rfc8949-deterministic" as const;

export const E2EE_PRIMITIVES = Object.freeze({
  contentAead: "xchacha20-poly1305-ietf",
  streamAead: "secretstream-xchacha20-poly1305",
  signatures: "ed25519",
  endpointKeyAgreement: "x25519-xsalsa20-poly1305",
  hash: "blake2b-256",
  passwordHash: "argon2id",
});

export const E2EE_DOMAIN_TAGS = Object.freeze([
  "endpoint",
  "enrollment-offer",
  "endpoint-request-body",
  "endpoint-request",
  "epoch",
  "eek-wrap",
  "dek-wrap",
  "object-header",
  "chunk",
  "grant",
  "grant-revoke",
  "disclosure",
  "job",
  "result",
  "log-entry",
  "manifest",
  "recovery",
  "tombstone",
  "enrollment-key-proof",
  "enrollment-challenge",
  "enrollment-sas",
  "enrollment-authorization",
  "genesis-recovery-confirmation",
  "genesis-authorization",
  "genesis-bootstrap-transcript",
  "genesis-hosted-append-receipt",
  "recovery-wrap",
  "recovery-replacement-confirmation",
  "recovery-authorization",
  "recovery-authority",
  "ceremony-abort",
] as const);

export type E2EEDomainTag = (typeof E2EE_DOMAIN_TAGS)[number];

/** Integer CBOR keys are fixed per envelope type; unknown keys are rejected. */
export const E2EE_ENVELOPE_FIELDS = Object.freeze({
  common: Object.freeze({
    suite: 1,
    vaultId: 2,
    type: 3,
    createdAt: 4,
    envelopeId: 5,
  }),
  endpoint: Object.freeze({
    endpointId: 10,
    role: 11,
    unattended: 12,
    signingPublicKey: 13,
    keyAgreementPublicKey: 14,
    addedByEndpointId: 15,
    sasTranscriptHash: 16,
    signature: 17,
  }),
  enrollmentOffer: Object.freeze({
    endpointId: 160,
    ceremonyId: 161,
    membershipRole: 162,
    unattended: 163,
    signingPublicKey: 164,
    keyAgreementPublicKey: 165,
    enrollmentNonce: 166,
    expiresAt: 168,
  }),
  enrollmentChallenge: Object.freeze({
    offerHash: 170,
    candidateKeyProof: 171,
    authorizerEndpointId: 172,
    authorizerSigningPublicKey: 173,
    authorizerKeyAgreementPublicKey: 174,
    controlSequence: 175,
    controlHeadHash: 176,
    membershipHash: 177,
    targetMembershipRole: 178,
    sasTranscriptHash: 179,
    challengeNonce: 180,
    expiresAt: 181,
    signature: 182,
  }),
  enrollmentAuthorization: Object.freeze({
    offerHash: 300,
    challengeHash: 301,
    authorizerEndpointId: 302,
    targetMembershipRole: 303,
    previousControlSequence: 304,
    previousControlHeadHash: 305,
    previousMembershipHash: 306,
    endpointEnvelope: 307,
    eekWrapEnvelope: 308,
    signedMembershipCommit: 309,
    expiresAt: 310,
    signature: 311,
  }),
  enrollmentSas: Object.freeze({
    ceremonyId: 320,
    offerHash: 321,
    candidateEndpointId: 322,
    candidateSigningPublicKey: 323,
    candidateKeyAgreementPublicKey: 324,
    candidateKeyProof: 325,
    authorizerEndpointId: 326,
    authorizerSigningPublicKey: 327,
    authorizerKeyAgreementPublicKey: 328,
    controlSequence: 329,
    controlHeadHash: 330,
    membershipHash: 331,
    targetMembershipRole: 332,
    challengeNonce: 333,
    challengeEnvelopeId: 334,
    challengeCreatedAt: 335,
    challengeExpiresAt: 336,
  }),
  ceremonyAbortState: Object.freeze({
    ceremonyId: 340,
    ceremonyKind: 341,
    epoch: 342,
    expectedControlSequence: 343,
    expectedControlHeadHash: 344,
    completedSteps: 345,
    alertCode: 346,
    incompleteReason: 347,
    plaintextOutstanding: 348,
    abortReason: 349,
    signerEndpointId: 350,
  }),
  genesisRecoveryConfirmation: Object.freeze({
    ceremonyId: 360,
    endpointId: 361,
    recoveryId: 362,
    recoverySigningPublicKey: 363,
    recoveryKeyAgreementPublicKey: 364,
    recoveryWrapHash: 365,
    confirmedAt: 366,
    recoveryGeneration: 367,
  }),
  genesisAuthorization: Object.freeze({
    ceremonyId: 370,
    endpointId: 371,
    epoch: 372,
    endpointEnvelope: 373,
    recoveryConfirmation: 374,
    signedGenesisCommit: 375,
    signature: 376,
  }),
  genesisBootstrapTranscript: Object.freeze({
    ceremonyId: 380,
    endpointId: 381,
    endpointSigningPublicKey: 382,
    endpointKeyAgreementPublicKey: 383,
    enrollmentRef: 384,
    recoveryId: 385,
    recoverySigningPublicKey: 386,
    recoveryKeyAgreementPublicKey: 387,
    recoveryGeneration: 388,
    epoch: 389,
    recoveryWrapHash: 390,
    recoveryConfirmationHash: 391,
  }),
  recoveryWrap: Object.freeze({
    ceremonyId: 400,
    recoveryGeneration: 401,
    recoveryId: 402,
    recoveryKeyAgreementPublicKey: 403,
    epoch: 404,
    issuerEndpointId: 405,
    activationControlSequence: 406,
    activationPreviousHead: 407,
    activationPreviousMembershipHash: 408,
    nonce: 409,
    ciphertext: 410,
    signature: 411,
  }),
  recoveryReplacementConfirmation: Object.freeze({
    ceremonyId: 420,
    priorRecoveryGeneration: 421,
    priorRecoveryId: 422,
    replacementRecoveryGeneration: 423,
    replacementRecoveryId: 424,
    replacementRecoverySigningPublicKey: 425,
    replacementRecoveryKeyAgreementPublicKey: 426,
    replacementRecoveryWrapHash: 427,
    candidateEndpointId: 428,
    newEpoch: 429,
    confirmationNonce: 430,
    signature: 431,
  }),
  recoveryAuthorization: Object.freeze({
    ceremonyId: 440,
    consumedRecoveryGeneration: 441,
    consumedRecoveryId: 442,
    consumedRecoverySigningPublicKey: 443,
    consumedRecoveryKeyAgreementPublicKey: 444,
    currentSnapshotHash: 445,
    consumedRecoveryWrapHash: 446,
    candidateEndpointEnvelope: 447,
    replacementConfirmation: 448,
    replacementRecoveryWrap: 449,
    newEpoch: 450,
    expiresAt: 451,
    signature: 452,
  }),
  epoch: Object.freeze({
    epoch: 20,
    authorizedEndpointIds: 21,
    reason: 22,
    signature: 23,
  }),
  eekWrap: Object.freeze({
    epoch: 30,
    recipientEndpointId: 31,
    issuerEndpointId: 32,
    nonce: 33,
    ciphertext: 34,
    signature: 35,
  }),
  dekWrap: Object.freeze({
    objectId: 40,
    revision: 41,
    epoch: 42,
    nonce: 43,
    ciphertext: 44,
  }),
  objectHeader: Object.freeze({
    objectId: 50,
    revision: 51,
    epoch: 52,
    chunkCount: 53,
    plaintextLength: 54,
    contentType: 55,
    dekWrapRef: 56,
    writerEndpointId: 57,
    signature: 58,
  }),
  grant: Object.freeze({
    grantId: 60,
    issuerEndpointId: 61,
    subjectAccountId: 62,
    subjectEndpointId: 63,
    subjectAgentId: 64,
    resourceIds: 65,
    operations: 66,
    providers: 67,
    issuedAt: 68,
    expiresAt: 69,
    revocationRef: 70,
    signature: 71,
  }),
  grantRevoke: Object.freeze({
    grantRef: 72,
    revocationRef: 73,
    revokedAt: 74,
    reason: 75,
    issuerEndpointId: 76,
    signature: 77,
  }),
  disclosure: Object.freeze({
    grantRef: 80,
    providerId: 81,
    destination: 82,
    scopeHash: 83,
    issuedAt: 84,
    expiresAt: 85,
    signature: 86,
  }),
  job: Object.freeze({
    jobId: 90,
    grantRef: 91,
    issuedAt: 92,
    expiresAt: 93,
    recipientEndpointId: 94,
    ciphertext: 95,
    signature: 96,
  }),
  result: Object.freeze({
    jobId: 100,
    jobHash: 101,
    recipientEndpointId: 102,
    ciphertext: 103,
    signature: 104,
    state: 105,
  }),
  logEntry: Object.freeze({
    sequence: 110,
    previousHash: 111,
    innerEnvelope: 112,
    signerEndpointId: 113,
    signature: 114,
  }),
  controlMembership: Object.freeze({
    ceremonyId: 140,
    ceremonyKind: 141,
    epoch: 142,
    previousMembershipHash: 143,
    activeMembers: 144,
    removedEndpointIds: 145,
    rotationCompleted: 146,
    outstandingJobsResolved: 147,
    recoverySnapshotHash: 148,
    recoveryAuthorizationHash: 149,
    recoveryGeneration: 155,
    recoveryId: 156,
    recoverySigningPublicKey: 157,
    recoveryKeyAgreementPublicKey: 158,
    recoveryWrapHash: 159,
  }),
  controlContinuity: Object.freeze({
    membershipHash: 150,
  }),
  controlCeremonyAbort: Object.freeze({
    ceremonyId: 151,
    ceremonyKind: 152,
    ceremonyStateHash: 153,
    reasonCode: 154,
  }),
  controlGrantRevocation: Object.freeze({
    revocationEnvelope: 160,
  }),
  manifest: Object.freeze({
    sequence: 120,
    objectRevisions: 121,
    signerEndpointId: 122,
    signature: 123,
  }),
  chunk: Object.freeze({
    objectId: 130,
    revision: 131,
    chunkIndex: 132,
    chunkCount: 133,
    secretstreamHeader: 134,
    ciphertext: 135,
  }),
  recovery: Object.freeze({
    salt: 200,
    opsLimit: 201,
    memLimitBytes: 202,
    nonce: 203,
    ciphertext: 204,
    recoveryGeneration: 205,
    recoveryId: 206,
    snapshotHash: 207,
    authorizationHash: 208,
  }),
  recoverySnapshot: Object.freeze({
    sequence: 220,
    controlHeadHash: 221,
    membershipHash: 222,
    priorEndpointIds: 223,
  }),
});

/**
 * anc/v1 recovery-authority KDF parameters are suite constants, never envelope
 * input. `saltSource: "vaultId"` governs genesis and replacement authority
 * derivation, not the deprecated parallel sealed-EEK compatibility envelope.
 */
export const E2EE_RECOVERY_KDF = Object.freeze({
  algorithm: "argon2id",
  inputForm: "bip39-24-word-entropy",
  inputBytes: 32,
  saltSource: "vaultId",
  opsLimit: 2,
  memLimitBytes: 67_108_864,
  saltBytes: 16,
  outputBytes: 32,
});

export const E2EE_SIZE_LIMITS = Object.freeze({
  controlEnvelopeBytes: 64 * 1024,
  genesisBootstrapTranscriptBytes: 4 * 1024,
  objectHeaderBytes: 16 * 1024,
  chunkPlaintextBytes: 1024 * 1024,
  objectPlaintextBytes: 256 * 1024 * 1024,
  jobPayloadBytes: 16 * 1024 * 1024,
  resultPayloadBytes: 16 * 1024 * 1024,
  jobEnvelopeBytes: 16 * 1024 * 1024 + 64 * 1024,
  resultEnvelopeBytes: 16 * 1024 * 1024 + 64 * 1024,
  vaultLogEntryBytes: 64 * 1024,
  enrollmentAuthorizationBytes: 256 * 1024,
});

export const E2EE_LIFETIME_LIMITS_SECONDS = Object.freeze({
  internalGrantMaximum: 30 * 24 * 60 * 60,
  disclosureDefault: 24 * 60 * 60,
  disclosureMaximum: 7 * 24 * 60 * 60,
  brokerAuthorizationFreshness: 15 * 60,
});

export function e2eeDomainSeparationPrefix(tag: E2EEDomainTag): Uint8Array {
  return new TextEncoder().encode(`${E2EE_SUITE_ID}/${tag}\0`);
}
