/**
 * Auto-generates the search index from docs route files.
 *
 * Reads each docs.*.tsx route, extracts the page title from `meta`,
 * finds all h2/h3 headings with ids, and grabs the text content between
 * headings by stripping JSX tags.
 *
 * Used two ways:
 * 1. Vite plugin (vite.config.ts) — regenerates on dev server start and
 *    when any docs.*.tsx route file changes
 * 2. Standalone: npx tsx scripts/generate-search-index.ts
 */

import fs from "fs";
import path from "path";

interface SearchEntry {
  page: string;
  path: string;
  section: string;
  sectionId: string;
  text: string;
}

const ROUTES_DIR = path.join(import.meta.dirname, "../app/routes");
const OUTPUT = path.join(
  import.meta.dirname,
  "../app/components/searchIndex.ts",
);

// Files to skip (redirects, non-content pages)
const SKIP_FILES = new Set(["docs.database-adapters.tsx"]);

function getDocsRouteFiles(): string[] {
  return fs
    .readdirSync(ROUTES_DIR)
    .filter((f) => f.startsWith("docs.") && f.endsWith(".tsx"))
    .filter((f) => !SKIP_FILES.has(f))
    .sort();
}

function fileToPath(filename: string): string {
  const slug = filename.replace(/\.tsx$/, "").replace(/^docs\./, "");
  if (slug === "_index") return "/docs";
  return `/docs/${slug}`;
}

function extractPageTitle(source: string): string | null {
  const m = source.match(/title:\s*"([^"]+?)\s*(?:—|-)?\s*Agent-Native"/);
  if (m) return m[1].trim();

  const h1 = source.match(/<h1[^>]*>\s*([\s\S]*?)\s*<\/h1>/);
  if (h1) return stripJsx(h1[1]).trim();

  return null;
}

function stripJsx(text: string): string {
  return text
    .replace(/\{"\s*"\}/g, " ")
    .replace(/\{`[^`]*`\}/g, " ")
    .replace(/\{[^}]*\}/g, "")
    .replace(/<[^>]+>/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function extractSections(
  source: string,
  pagePath: string,
  pageTitle: string,
): SearchEntry[] {
  const entries: SearchEntry[] = [];

  const headingPattern =
    /<h([23])\s+[^>]*?id="([^"]+)"[^>]*>([\s\S]*?)<\/h\1>/g;
  const headings: { id: string; label: string; index: number }[] = [];

  let match;
  while ((match = headingPattern.exec(source)) !== null) {
    headings.push({
      id: match[2],
      label: stripJsx(match[3]),
      index: match.index + match[0].length,
    });
  }

  // Match custom components that render as headings (FAQ, SectionDivider)
  const componentPattern =
    /<(?:FAQ|SectionDivider)\s+[^>]*?id="([^"]+)"[^>]*?(?:question|label)="([^"]+)"[^>]*?\/?>/g;
  while ((match = componentPattern.exec(source)) !== null) {
    if (!headings.some((h) => h.id === match![1])) {
      headings.push({
        id: match[1],
        label: match[2],
        index: match.index + match[0].length,
      });
    }
  }

  headings.sort((a, b) => a.index - b.index);

  if (headings.length === 0) return entries;

  for (let i = 0; i < headings.length; i++) {
    const heading = headings[i];
    const start = heading.index;
    const end = i + 1 < headings.length ? headings[i + 1].index : source.length;
    const sectionSource = source.slice(start, end);

    let text = stripJsx(sectionSource);

    if (i + 1 < headings.length) {
      const nextLabel = headings[i + 1].label;
      if (text.endsWith(nextLabel)) {
        text = text.slice(0, -nextLabel.length).trim();
      }
    }

    if (text.length > 300) {
      text = text.slice(0, 300).replace(/\s\S*$/, "...");
    }

    if (text.length < 10) continue;

    entries.push({
      page: pageTitle,
      path: pagePath,
      section: heading.label,
      sectionId: heading.id,
      text,
    });
  }

  return entries;
}

export function generateSearchIndex(): number {
  const allEntries: SearchEntry[] = [];
  const files = getDocsRouteFiles();

  for (const file of files) {
    const source = fs.readFileSync(path.join(ROUTES_DIR, file), "utf-8");
    if (source.includes("return redirect(")) continue;

    const pagePath = fileToPath(file);
    const pageTitle = extractPageTitle(source);
    if (!pageTitle) continue;

    const entries = extractSections(source, pagePath, pageTitle);
    if (entries.length > 0) {
      allEntries.push(...entries);
    }
  }

  const output = `// Auto-generated by scripts/generate-search-index.ts — do not edit manually

export interface SearchEntry {
  page: string;
  path: string;
  section: string;
  sectionId: string;
  text: string;
}

export const searchIndex: SearchEntry[] = ${JSON.stringify(allEntries, null, 2)};
`;

  fs.writeFileSync(OUTPUT, output);
  return allEntries.length;
}

// Run standalone when executed directly
const isMain =
  process.argv[1]?.endsWith("generate-search-index.ts") ||
  process.argv[1]?.endsWith("generate-search-index");
if (isMain) {
  const count = generateSearchIndex();
  console.log(`Generated ${count} search entries`);
}
