import { MAX_UPLOAD_FILES_PER_REQUEST } from "../../shared/upload-limits.js";

export const MAX_UPLOAD_BYTES = 4 * 1024 * 1024;
export const MAX_UPLOAD_MB = MAX_UPLOAD_BYTES / 1024 / 1024;

export const MULTIPART_OVERHEAD_BYTES = 64 * 1024;
export const TOTAL_BODY_LIMIT = MAX_UPLOAD_BYTES + MULTIPART_OVERHEAD_BYTES;

export { MAX_UPLOAD_FILES_PER_REQUEST };
