[build]
  command = "pnpm install && NITRO_PRESET=netlify pnpm --filter slides build"
  publish = "templates/slides/dist"
  functions = "templates/slides/.netlify/functions-internal"

[build.environment]
  NITRO_PRESET = "netlify"
