import { track, type TrackingSource } from "@agent-native/core/tracking";

/**
 * A home-prompt deck is generated by an ordinary chat run, so no action owns
 * its completion and the editor tab that used to report it is often closed by
 * the time the run ends. The run that lands a generation deck's first slide is
 * recorded here and reported once, server-side, when that run finishes.
 */
export interface GenerationFirstOutput {
  deckId: string;
  generationAttemptId: string;
  targetSlideCount: number | null;
}

// ponytail: per-process map keyed by run id; tools and run completion share a
// process, and an entry only outlives its run if the process dies mid-run.
const MAX_TRACKED_RUNS = 500;
const firstOutputsByRun = new Map<string, GenerationFirstOutput[]>();

export function noteGenerationFirstOutput(
  runId: string | undefined,
  output: GenerationFirstOutput,
): void {
  if (!runId) return;
  if (
    !firstOutputsByRun.has(runId) &&
    firstOutputsByRun.size >= MAX_TRACKED_RUNS
  ) {
    const oldest = firstOutputsByRun.keys().next().value;
    if (oldest !== undefined) firstOutputsByRun.delete(oldest);
  }
  const outputs = firstOutputsByRun.get(runId) ?? [];
  if (outputs.some((entry) => entry.deckId === output.deckId)) return;
  firstOutputsByRun.set(runId, [...outputs, output]);
}

export async function trackGenerationCompletedForRun(
  run: { runId: string; threadId?: string; status: string },
  readSlideCount: (deckId: string) => Promise<number | null>,
  source?: TrackingSource,
): Promise<void> {
  const outputs = firstOutputsByRun.get(run.runId);
  if (!outputs) return;
  firstOutputsByRun.delete(run.runId);
  for (const output of outputs) {
    const slideCount = await readSlideCount(output.deckId);
    if (slideCount === null || slideCount === 0) continue;
    track(
      "generation_completed",
      {
        app_name: "slides",
        template_name: "slides",
        generation_attempt_id: output.generationAttemptId,
        output_id: output.deckId,
        output_type: "deck",
        slide_count: slideCount,
        ...(output.targetSlideCount !== null
          ? { target_slide_count: output.targetSlideCount }
          : {}),
        outcome:
          run.status === "completed" &&
          (output.targetSlideCount === null ||
            slideCount >= output.targetSlideCount)
            ? "completed"
            : "partial",
        run_status: run.status,
        run_id: run.runId,
        ...(run.threadId ? { thread_id: run.threadId } : {}),
        source: "agent_run",
      },
      source,
    );
  }
}
