import { resolveAccess } from "@agent-native/core/sharing";
import { track, type TrackingSource } from "@agent-native/core/tracking";

/**
 * A home-prompt deck is generated by an ordinary chat run, so no action owns
 * its completion and the editor tab that used to report it is often closed by
 * the time the run ends. The turn that lands a generation deck's first slide is
 * recorded here and reported once, server-side, when the turn finishes: a run
 * that errored or was stopped reports nothing, and a run that hands its turn
 * to a continuation run waits for it.
 */
export interface GenerationFirstOutput {
  deckId: string;
  generationAttemptId: string;
  targetSlideCount: number | null;
}

// ponytail: per-process map keyed by turn id. A continuation run keeps its
// turn id but gets a new run id, so a turn that resumes in another process
// never reports; that undercounts, it does not report a partial deck. Upgrade
// to a persisted marker if long chained generations need to be counted.
const MAX_TRACKED_TURNS = 500;
const firstOutputsByTurn = new Map<string, GenerationFirstOutput[]>();

export function noteGenerationFirstOutput(
  turnKey: string | undefined,
  output: GenerationFirstOutput,
): void {
  if (!turnKey) return;
  if (
    !firstOutputsByTurn.has(turnKey) &&
    firstOutputsByTurn.size >= MAX_TRACKED_TURNS
  ) {
    const oldest = firstOutputsByTurn.keys().next().value;
    if (oldest !== undefined) firstOutputsByTurn.delete(oldest);
  }
  const outputs = firstOutputsByTurn.get(turnKey) ?? [];
  if (outputs.some((entry) => entry.deckId === output.deckId)) return;
  firstOutputsByTurn.set(turnKey, [...outputs, output]);
}

export async function trackGenerationCompletedForRun(
  run: { runId: string; turnId?: string; threadId?: string; status: string },
  outcome: { turnContinues: boolean },
  readSlideCount: (deckId: string) => Promise<number | null>,
  source?: TrackingSource,
): Promise<void> {
  const turnKey = run.turnId || run.runId;
  const outputs = firstOutputsByTurn.get(turnKey);
  if (!outputs) return;
  if (outcome.turnContinues && run.status !== "aborted") return;
  firstOutputsByTurn.delete(turnKey);
  if (run.status !== "completed") return;
  for (const output of outputs) {
    const slideCount = await readSlideCount(output.deckId);
    if (slideCount === null || slideCount === 0) continue;
    track(
      "generation_completed",
      {
        app_name: "slides",
        template_name: "slides",
        generation_attempt_id: output.generationAttemptId,
        output_id: output.deckId,
        output_type: "deck",
        slide_count: slideCount,
        ...(output.targetSlideCount !== null
          ? { target_slide_count: output.targetSlideCount }
          : {}),
        outcome:
          output.targetSlideCount === null ||
          slideCount >= output.targetSlideCount
            ? "completed"
            : "partial",
        run_id: run.runId,
        ...(run.threadId ? { thread_id: run.threadId } : {}),
        source: "agent_run",
      },
      source,
    );
  }
}

/**
 * A deck deleted or unshared before its run ended resolves to null; any other
 * failure rejects, so an unreadable deck is never mistaken for a gone one.
 */
export async function readGeneratedDeckSlideCount(
  deckId: string,
): Promise<number | null> {
  const access = await resolveAccess("deck", deckId);
  if (!access) return null;
  const data = JSON.parse((access.resource as { data: string }).data) as {
    slides?: unknown;
  };
  return Array.isArray(data.slides) ? data.slides.length : 0;
}
