import type { EffectDefinition } from "./native-effects";

export const HISTORICAL_105_DEFINITION_IDENTITIES = [
  "an-native-ascii-print@1",
  "an-native-barrel-distortion@1",
  "an-native-bloom@2",
  "an-native-brushed-metal@1",
  "an-native-cellular-bloom@1",
  "an-native-chromatic-aberration@1",
  "an-native-color-grade@1",
  "an-native-crosshatch@1",
  "an-native-crt-display@1",
  "an-native-curl-streamlines@1",
  "an-native-dye-transport@1",
  "an-native-eddy-rings@1",
  "an-native-emboss@1",
  "an-native-film-grain@1",
  "an-native-firefly-drift@2",
  "an-native-flow-glass@1",
  "an-native-fractal-cloud@1",
  "an-native-frosted-refraction@1",
  "an-native-frosted-refraction@2",
  "an-native-frosted-refraction@3",
  "an-native-gaussian-blur@2",
  "an-native-gradient-field@1",
  "an-native-grain-gradient@1",
  "an-native-grain-gradient@2",
  "an-native-grain-gradient@3",
  "an-native-halftone@1",
  "an-native-halftone@2",
  "an-native-halftone@3",
  "an-native-hex-tiles@1",
  "an-native-ink-advection@1",
  "an-native-iridescent-surface@1",
  "an-native-kaleidoscope@1",
  "an-native-magnetic-filaments@1",
  "an-native-mandelbrot@1",
  "an-native-mesh-anchors@2",
  "an-native-metaball-field@2",
  "an-native-noise-displacement@1",
  "an-native-ordered-dither@1",
  "an-native-owned-anamorphic-streaks@2",
  "an-native-owned-aurora-curtains@2",
  "an-native-owned-bevel-light@1",
  "an-native-owned-braided-ribbons@2",
  "an-native-owned-chromatic-drift@1",
  "an-native-owned-contour-terrain@2",
  "an-native-owned-coral-polyps@2",
  "an-native-owned-crystal-lattice@2",
  "an-native-owned-detail-boost@1",
  "an-native-owned-directional-smear@1",
  "an-native-owned-edge-ink@1",
  "an-native-owned-edge-neon@1",
  "an-native-owned-ember-drift@2",
  "an-native-owned-emboss-light@1",
  "an-native-owned-etched-diffraction@2",
  "an-native-owned-fog-banks@2",
  "an-native-owned-folded-paper@2",
  "an-native-owned-fresnel-shells@2",
  "an-native-owned-glass-blocks@1",
  "an-native-owned-gyroid-slice@2",
  "an-native-owned-heat-haze@1",
  "an-native-owned-horizon-haze@2",
  "an-native-owned-ink-bleed@1",
  "an-native-owned-ink-blooms@2",
  "an-native-owned-knit-loops@2",
  "an-native-owned-lace-rosettes@2",
  "an-native-owned-leaf-venation@2",
  "an-native-owned-lens-pinch@1",
  "an-native-owned-lenticular-ribs@2",
  "an-native-owned-mycelium-trails@2",
  "an-native-owned-pixel-shift@1",
  "an-native-owned-prism-facets@2",
  "an-native-owned-prism-split@1",
  "an-native-owned-quilted-diamonds@2",
  "an-native-owned-radial-echo@1",
  "an-native-owned-ribbon-warp@1",
  "an-native-owned-sashiko-stitches@2",
  "an-native-owned-shadow-lift@1",
  "an-native-owned-soft-threshold@1",
  "an-native-owned-tide-pool-contours@2",
  "an-native-owned-tilt-focus@1",
  "an-native-owned-tone-ripple@1",
  "an-native-owned-volumetric-cones@2",
  "an-native-owned-water-ring@1",
  "an-native-owned-wire-dome@2",
  "an-native-palette-map@1",
  "an-native-particle-flow@1",
  "an-native-pixelate@1",
  "an-native-plasma-field@1",
  "an-native-plasma-sheets@1",
  "an-native-posterize@1",
  "an-native-reaction-field@1",
  "an-native-reaction-islands@1",
  "an-native-ripple-distortion@1",
  "an-native-sharpen@1",
  "an-native-sobel-edges@1",
  "an-native-starfield@3",
  "an-native-swirl@1",
  "an-native-threshold@1",
  "an-native-truchet-arcs@1",
  "an-native-vignette@1",
  "an-native-voronoi-cells@2",
  "an-native-wake-echo@1",
  "an-native-water-caustics@1",
  "an-native-wave-interference@1",
  "an-native-wave-memory@1",
  "an-native-woven-fabric@1",
] as const;

export function selectHistorical105Definitions(
  catalog: readonly EffectDefinition[],
): EffectDefinition[] {
  if (new Set(HISTORICAL_105_DEFINITION_IDENTITIES).size !== 105)
    throw new Error("Historical definition identity fixture is duplicated");
  return HISTORICAL_105_DEFINITION_IDENTITIES.map((identity) => {
    const matches = catalog.filter(
      (definition) => `${definition.id}@${definition.version}` === identity,
    );
    if (matches.length !== 1)
      throw new Error(
        `Historical definition ${identity} is ${matches.length === 0 ? "missing" : "duplicated"}`,
      );
    return matches[0]!;
  });
}
