import { NATIVE_EFFECT_DEFINITION_CATALOG } from "./native-effect-presets";
import { nativeEffectExecutionPayload } from "./native-effect-trust";
import type { EffectDefinition } from "./native-effects";

export type NativeEffectAnimationCapability = "animated" | "static" | "unknown";

// Exact reviewed versions only; absence stays unknown when the catalog grows.
// This display policy is outside EffectDefinition and does not change execution hashes.
const STATIC_BUILTIN_VERSIONS = new Set([
  "an-native-owned-p-environment-metal@1",
  "an-native-owned-p-density-heatmap@3",
  "an-native-owned-p-vector-field-displacement@2",
  "an-native-owned-o-angular-stops@2",
  "an-native-owned-o-studio-light-rig@1",
  "an-native-owned-o-inhibited-stipple@3",
  "an-native-owned-o-ghost-chain@1",
  "an-native-halftone@1",
  "an-native-halftone@2",
  "an-native-halftone@3",
  "an-native-color-grade@1",
  "an-native-palette-map@1",
  "an-native-posterize@1",
  "an-native-threshold@1",
  "an-native-ordered-dither@1",
  "an-native-sobel-edges@1",
  "an-native-emboss@1",
  "an-native-sharpen@1",
  "an-native-pixelate@1",
  "an-native-crt-display@1",
  "an-native-chromatic-aberration@1",
  "an-native-barrel-distortion@1",
  "an-native-swirl@1",
  "an-native-kaleidoscope@1",
  "an-native-vignette@1",
  "an-native-crosshatch@1",
  "an-native-ascii-print@1",
  "an-native-gaussian-blur@2",
  "an-native-bloom@2",
  "an-native-owned-directional-smear@1",
  "an-native-owned-radial-echo@1",
  "an-native-owned-tilt-focus@1",
  "an-native-owned-edge-ink@1",
  "an-native-owned-edge-neon@1",
  "an-native-owned-emboss-light@1",
  "an-native-owned-bevel-light@1",
  "an-native-owned-glass-blocks@1",
  "an-native-owned-chromatic-drift@1",
  "an-native-owned-prism-split@1",
  "an-native-owned-lens-pinch@1",
  "an-native-owned-ink-bleed@1",
  "an-native-owned-soft-threshold@1",
  "an-native-owned-detail-boost@1",
  "an-native-owned-shadow-lift@1",
  "an-native-owned-bilateral-surface@1",
  "an-native-owned-local-rank-contrast@1",
  "an-native-owned-alpha-pinhole-repair@1",
  "an-native-owned-luminance-split-tone@1",
  "an-native-owned-illuminant-adaptation@1",
  "an-native-owned-hue-sector-relight@1",
  "an-native-owned-guided-local-regression@1",
  "an-native-owned-cylindrical-reprojection@1",
  "an-native-owned-f-photoelastic-stress@1",
  "an-native-owned-f-advected-marble@3",
  "an-native-owned-f-superformula-bloom@1",
  "an-native-owned-f-circle-inversion-web@1",
  "an-native-owned-f-basketweave-parquet@3",
  "an-native-owned-f-spherical-harmonic-surface@1",
  "an-native-owned-i-structure-orientation@1",
  "an-native-owned-i-local-entropy@1",
  "an-native-owned-i-height-parallax@1",
  "an-native-owned-i-photo-sphere@1",
  "an-native-owned-i-triangle-facets@1",
  "an-native-owned-i-four-plate-overprint@1",
  "an-native-owned-j-photo-contour-relief@1",
  "an-native-owned-j-surround-reflectance@1",
  "an-native-owned-j-morphological-top-hat@1",
  "an-native-owned-j-harris-corner-marks@1",
  "an-native-owned-j-microlens-grid@1",
  "an-native-owned-j-waterline-mirror@1",
  "an-native-owned-k-koch-boundary@1",
  "an-native-owned-k-hilbert-trace@2",
  "an-native-owned-k-occluder-penumbra@1",
  "an-native-owned-k-triangle-mesh-warp@1",
  "an-native-owned-k-alpha-medial-ridge@2",
  "an-native-owned-k-gamut-shoulder@2",
  "an-native-owned-selective-vibrance@1",
  "an-native-owned-threshold-solarization@1",
  "an-native-owned-channel-radius-blur@1",
  "an-native-owned-three-point-tonal-map@1",
  "an-native-owned-film-halation@1",
  "an-native-owned-fluted-refraction@1",
  "an-native-owned-m-cell-dissolve@1",
  "an-native-owned-m-iris-aperture@1",
  "an-native-owned-m-page-fold@1",
  "an-native-owned-m-brush-liquify@1",
  "an-native-owned-m-watercolor-pooling@1",
  "an-native-owned-m-interference-edge-fringe@1",
  "an-native-owned-n-arc-path@1",
  "an-native-owned-n-rational-circle-canopy@2",
  "an-native-owned-log-polar-reprojection@1",
  "an-native-owned-julia-orbit-trap@1",
  "an-native-owned-torus-raymarch@1",
  "an-native-owned-recursive-partition-mosaic@1",
  "an-native-owned-patch-affinity-denoise@1",
  "an-native-owned-quadrant-variance-paint@1",
  "an-native-owned-chroma-hold@1",
  "an-native-owned-mosaic-sensor@1",
  "an-native-owned-haar-band-remix@1",
  "an-native-owned-cassini-field-atlas@1",
  "an-native-owned-leaf-venation@2",
  "an-native-owned-coral-polyps@2",
  "an-native-owned-knit-loops@2",
  "an-native-owned-quilted-diamonds@2",
  "an-native-owned-lace-rosettes@2",
  "an-native-owned-sashiko-stitches@2",
  "an-native-owned-prism-facets@2",
  "an-native-owned-lenticular-ribs@2",
  "an-native-owned-anamorphic-streaks@2",
  "an-native-owned-horizon-haze@2",
  "an-native-owned-wire-dome@2",
  "an-native-owned-folded-paper@2",
  "an-native-owned-crystal-lattice@2",
  "an-native-owned-c-wood-endgrain@2",
  "an-native-owned-c-basalt-vesicles@2",
  "an-native-owned-c-terrazzo-chips@2",
  "an-native-owned-c-mica-schist@2",
  "an-native-owned-c-salt-crust@2",
  "an-native-owned-c-parchment-fibrils@2",
  "an-native-owned-c-corduroy-ridges@2",
  "an-native-owned-c-ikat-warp@2",
  "an-native-owned-c-marled-yarn@2",
  "an-native-owned-c-crochet-chain@2",
  "an-native-owned-c-tartan-interlace@2",
  "an-native-owned-c-knotted-net@2",
  "an-native-owned-c-guilloche-rosettes@2",
  "an-native-owned-c-hypotrochoid-ink@2",
  "an-native-owned-c-logarithmic-spiral-lines@2",
  "an-native-owned-c-phyllotaxis-seeds@2",
  "an-native-owned-c-sinc-diffraction@2",
  "an-native-owned-c-twin-halo-arcs@2",
  "an-native-owned-c-superellipsoid@2",
  "an-native-owned-c-catenoid-shell@2",
  "an-native-owned-c-trefoil-tube@2",
  "an-native-owned-c-dodecahedron-facets@2",
  "an-native-owned-c-menger-cutaway@2",
  "an-native-owned-c-twisted-prism@2",
  "an-native-owned-leaf-venation@3",
  "an-native-owned-coral-polyps@3",
  "an-native-owned-knit-loops@3",
  "an-native-owned-quilted-diamonds@3",
  "an-native-owned-lace-rosettes@3",
  "an-native-owned-sashiko-stitches@3",
  "an-native-owned-prism-facets@3",
  "an-native-owned-lenticular-ribs@3",
  "an-native-owned-anamorphic-streaks@3",
  "an-native-owned-horizon-haze@3",
  "an-native-owned-wire-dome@3",
  "an-native-owned-folded-paper@3",
  "an-native-owned-crystal-lattice@3",
  "an-native-owned-next-median-speckle@1",
  "an-native-owned-next-anisotropic-diffusion@1",
  "an-native-owned-next-aperture-bokeh@1",
  "an-native-owned-next-dark-channel-dehaze@1",
  "an-native-owned-next-bounded-canny-contours@1",
  "an-native-owned-next-dog-ink@1",
  "an-native-owned-next-alpha-dilate@1",
  "an-native-owned-next-alpha-erode@1",
  "an-native-owned-corner-perspective@1",
  "an-native-owned-chroma-key@1",
  "an-native-owned-pointillist-brush@1",
  "an-native-owned-adaptive-threshold@1",
  "an-native-owned-breadth-perspective-floor-grid@1",
  "an-native-owned-breadth-hyperbolic-geodesics@1",
  "an-native-owned-breadth-isometric-voxel-field@1",
  "an-native-owned-breadth-masonry-bond@1",
  "an-native-owned-breadth-sand-ripple-bed@1",
  "an-native-owned-breadth-sierpinski-gasket@1",
  "an-native-owned-breadth-polarized-light-sheets@1",
  "an-native-owned-newton-basins@1",
  "an-native-owned-plate-nodal-lines@1",
]);

const ANIMATED_BUILTIN_VERSIONS = new Set([
  "an-native-owned-p-tape-tracking@3",
  "an-native-grain-gradient@1",
  "an-native-frosted-refraction@1",
  "an-native-grain-gradient@2",
  "an-native-frosted-refraction@2",
  "an-native-gradient-field@1",
  "an-native-mesh-anchors@2",
  "an-native-voronoi-cells@2",
  "an-native-truchet-arcs@1",
  "an-native-water-caustics@1",
  "an-native-mandelbrot@1",
  "an-native-starfield@3",
  "an-native-hex-tiles@1",
  "an-native-wave-interference@1",
  "an-native-iridescent-surface@1",
  "an-native-metaball-field@2",
  "an-native-fractal-cloud@1",
  "an-native-brushed-metal@1",
  "an-native-plasma-field@1",
  "an-native-woven-fabric@1",
  "an-native-ripple-distortion@1",
  "an-native-noise-displacement@1",
  "an-native-film-grain@1",
  "an-native-particle-flow@1",
  "an-native-owned-mycelium-trails@2",
  "an-native-owned-ink-blooms@2",
  "an-native-owned-tide-pool-contours@2",
  "an-native-owned-braided-ribbons@2",
  "an-native-owned-fresnel-shells@2",
  "an-native-owned-etched-diffraction@2",
  "an-native-owned-aurora-curtains@2",
  "an-native-owned-fog-banks@2",
  "an-native-owned-ember-drift@2",
  "an-native-owned-volumetric-cones@2",
  "an-native-owned-contour-terrain@2",
  "an-native-owned-gyroid-slice@2",
  "an-native-owned-heat-haze@1",
  "an-native-owned-water-ring@1",
  "an-native-owned-ribbon-warp@1",
  "an-native-owned-pixel-shift@1",
  "an-native-owned-tone-ripple@1",
  "an-native-curl-streamlines@1",
  "an-native-eddy-rings@1",
  "an-native-reaction-islands@1",
  "an-native-firefly-drift@2",
  "an-native-ink-advection@1",
  "an-native-magnetic-filaments@1",
  "an-native-cellular-bloom@1",
  "an-native-plasma-sheets@1",
  "an-native-flow-glass@1",
  "an-native-wake-echo@1",
  "an-native-dye-transport@1",
  "an-native-reaction-field@1",
  "an-native-wave-memory@1",
  "an-native-grain-gradient@3",
  "an-native-frosted-refraction@3",
  "an-native-owned-c-quasicrystal-bands@1",
  "an-native-owned-c-lissajous-weft@1",
  "an-native-owned-c-snow-squall@1",
  "an-native-owned-c-underwater-sediment@1",
  "an-native-owned-c-dust-storm@1",
  "an-native-owned-c-heat-inversion@1",
  "an-native-owned-breadth-dielectric-branching@1",
  "an-native-owned-orbital-lensing@1",
  "an-native-owned-harmonic-band-map@1",
  "an-native-owned-n-double-grating-moire@1",
  "an-native-owned-n-schlieren-knife-edge@1",
  "an-native-owned-n-doppler-wavefronts@1",
  "an-native-owned-n-kepler-area-sweep@2",
]);

const canonicalPayloadByVersion = new Map(
  NATIVE_EFFECT_DEFINITION_CATALOG.map((definition) => [
    `${definition.id}@${definition.version}`,
    JSON.stringify(nativeEffectExecutionPayload(definition)),
  ]),
);

export function nativeEffectAnimationCapability(
  definition: EffectDefinition,
): NativeEffectAnimationCapability {
  const key = `${definition.id}@${definition.version}`;
  const canonicalPayload = canonicalPayloadByVersion.get(key);
  if (
    canonicalPayload === undefined ||
    canonicalPayload !==
      JSON.stringify(nativeEffectExecutionPayload(definition))
  )
    return "unknown";
  const staticReviewed = STATIC_BUILTIN_VERSIONS.has(key);
  const animatedReviewed = ANIMATED_BUILTIN_VERSIONS.has(key);
  if (staticReviewed === animatedReviewed) return "unknown";
  return staticReviewed ? "static" : "animated";
}
