import {
  createAgentChatPlugin,
  loadActionsFromStaticRegistry,
} from "@agent-native/core/server";
import { getOrgContext } from "@agent-native/core/org";
import { registerEvent } from "@agent-native/core/event-bus";
import { z } from "zod";
// Static-import registry generated by @agent-native/core's Vite plugin at
// build time. Using a static import ensures bundlers (Nitro on Netlify,
// Vercel, AWS-Lambda) include every action module in the server bundle —
// a runtime filesystem scan finds nothing in a bundled function, which is
// why `autoDiscoverActions` on its own produces 404s for action routes in
// production.
import actionsRegistry from "../../.generated/actions-registry.js";

// ---------------------------------------------------------------------------
// Register calendar event-bus events
// ---------------------------------------------------------------------------
registerEvent({
  name: "calendar.event.created",
  description: "A new calendar event was created.",
  payloadSchema: z.object({
    eventId: z.string(),
    title: z.string(),
    startTime: z.string(),
    endTime: z.string(),
    attendees: z.array(z.any()),
    createdBy: z.string(),
  }),
});

registerEvent({
  name: "calendar.event.updated",
  description: "An existing calendar event was updated.",
  payloadSchema: z.object({
    eventId: z.string(),
    title: z.string(),
    startTime: z.string(),
    endTime: z.string(),
    attendees: z.array(z.any()),
    updatedBy: z.string(),
  }),
});

registerEvent({
  name: "calendar.booking.created",
  description: "Someone booked a meeting via a scheduling / booking link.",
  payloadSchema: z.object({
    bookingId: z.string(),
    schedulingLinkSlug: z.string(),
    attendeeName: z.string(),
    attendeeEmail: z.string(),
    startTime: z.string(),
    endTime: z.string(),
    eventTitle: z.string(),
  }),
});

export default createAgentChatPlugin({
  appId: "calendar",
  resolveOrgId: async (event) => {
    const ctx = await getOrgContext(event);
    return ctx.orgId;
  },
  actions: loadActionsFromStaticRegistry(actionsRegistry),
  systemPrompt: `You are an AI calendar assistant. You manage the user's Google Calendar events, bookings, and availability.

## CRITICAL: Use Scripts, Not Raw SQL

Google Calendar events are NOT stored in the local database. They are fetched live from Google Calendar API via scripts. You MUST use the following scripts — never use db-query or db-exec for calendar operations:

- \`pnpm action view-screen\` — See what the user is looking at (current view, date, events). ALWAYS run this first.
- \`pnpm action list-events --from YYYY-MM-DD --to YYYY-MM-DD\` — List events from Google Calendar. The --to date is exclusive, so use tomorrow for today's events.
- \`pnpm action search-events --query "term"\` — Search events by title
- \`pnpm action create-event --title "..." --start "ISO" --end "ISO"\` — Create a new event
- \`pnpm action navigate --view=calendar --calendarViewMode=day\` — Navigate the UI (day/week/month views, dates)
- \`pnpm action navigate --view=calendar --date=YYYY-MM-DD\` — Navigate to a specific date
- \`pnpm action navigate --view=availability\` — Show availability settings
- \`pnpm action navigate --view=booking-links\` — Show booking links
- \`pnpm action check-availability --date YYYY-MM-DD --duration 60\` — Check free slots

## Google Connection Check
Before running calendar scripts, run view-screen first. If it indicates Google is not connected, tell the user to go to Settings to configure credentials and connect.

## Context Awareness
The UI writes navigation state including the current view, date, view mode (day/week/month), and selected event ID. Always check view-screen to know what the user sees before responding.

When the user says "show me", "go to", "open", or "switch to" a view or date, ALWAYS use the \`navigate\` action to update the UI first, then fetch/display data. The user expects to SEE the result in the app.`,
  mentionProviders: async () => {
    const { getDb } = await import("../db/index.js");
    const { bookings, bookingLinks } = await import("../db/schema.js");
    const { like, desc } = await import("drizzle-orm");
    return {
      bookings: {
        label: "Bookings",
        icon: "email",
        search: async (query: string) => {
          const db = getDb();
          const rows = query
            ? await db
                .select()
                .from(bookings)
                .where(like(bookings.name, `%${query}%`))
                .limit(15)
            : await db
                .select()
                .from(bookings)
                .orderBy(desc(bookings.start))
                .limit(15);
          return rows.map((booking) => ({
            id: booking.id,
            label: `${booking.eventTitle || "Booking"} — ${booking.name}`,
            description: booking.start,
            icon: "document" as const,
            refType: "booking",
            refId: booking.id,
          }));
        },
      },
      "booking-links": {
        label: "Booking Links",
        icon: "document",
        search: async (query: string) => {
          const db = getDb();
          const rows = query
            ? await db
                .select()
                .from(bookingLinks)
                .where(like(bookingLinks.title, `%${query}%`))
                .limit(15)
            : await db
                .select()
                .from(bookingLinks)
                .orderBy(desc(bookingLinks.updatedAt))
                .limit(15);
          return rows.map((link) => ({
            id: link.id,
            label: link.title,
            description: `${link.duration}min · /${link.slug}`,
            icon: "document" as const,
            refType: "booking-link",
            refId: link.id,
          }));
        },
      },
    };
  },
});
