import {
  ensureAdditiveColumns,
  getDbExec,
  runMigrations,
} from "@agent-native/core/db";

import * as schema from "../db/schema.js";

function ownableTable(name: string, columns: string): string {
  return `CREATE TABLE IF NOT EXISTS ${name} (
${columns},
  owner_email TEXT NOT NULL DEFAULT 'local@localhost',
  org_id TEXT,
  visibility TEXT NOT NULL DEFAULT 'private'
)`;
}

function sharesTable(name: string): string {
  return `CREATE TABLE IF NOT EXISTS ${name} (
  id TEXT PRIMARY KEY,
  resource_id TEXT NOT NULL,
  principal_type TEXT NOT NULL,
  principal_id TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'viewer',
  created_by TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now'))
)`;
}

const initialSchema = [
  ownableTable(
    "crm_connections",
    `  id TEXT PRIMARY KEY,
  provider TEXT NOT NULL,
  workspace_connection_id TEXT,
  label TEXT NOT NULL,
  account_id TEXT,
  mode TEXT NOT NULL DEFAULT 'connected',
  status TEXT NOT NULL DEFAULT 'connected',
  selected_pipelines_json TEXT NOT NULL DEFAULT '[]',
  selected_object_types_json TEXT NOT NULL DEFAULT '[]',
  access_scope_key TEXT NOT NULL,
  access_scope_json TEXT NOT NULL DEFAULT '{}',
  last_synced_at TEXT,
  last_error TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))`,
  ),
  sharesTable("crm_connection_shares"),
  ownableTable(
    "crm_objects",
    `  id TEXT PRIMARY KEY,
  connection_id TEXT NOT NULL,
  provider TEXT NOT NULL,
  object_type TEXT NOT NULL,
  kind TEXT NOT NULL,
  label TEXT NOT NULL,
  plural_label TEXT NOT NULL,
  custom INTEGER NOT NULL DEFAULT 0,
  queryable INTEGER NOT NULL DEFAULT 1,
  searchable INTEGER NOT NULL DEFAULT 1,
  createable INTEGER NOT NULL DEFAULT 0,
  updateable INTEGER NOT NULL DEFAULT 0,
  deleteable INTEGER NOT NULL DEFAULT 0,
  capabilities_json TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))`,
  ),
  sharesTable("crm_object_shares"),
  ownableTable(
    "crm_field_policies",
    `  id TEXT PRIMARY KEY,
  connection_id TEXT NOT NULL,
  object_type TEXT NOT NULL,
  field_name TEXT NOT NULL,
  label TEXT NOT NULL,
  value_type TEXT NOT NULL,
  storage_policy TEXT NOT NULL DEFAULT 'remote-only',
  sensitive INTEGER NOT NULL DEFAULT 0,
  readable INTEGER NOT NULL DEFAULT 1,
  createable INTEGER NOT NULL DEFAULT 0,
  updateable INTEGER NOT NULL DEFAULT 0,
  required INTEGER NOT NULL DEFAULT 0,
  metadata_json TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))`,
  ),
  sharesTable("crm_field_policy_shares"),
  ownableTable(
    "crm_records",
    `  id TEXT PRIMARY KEY,
  connection_id TEXT NOT NULL,
  provider TEXT NOT NULL,
  object_type TEXT NOT NULL,
  kind TEXT NOT NULL,
  remote_id TEXT NOT NULL,
  display_name TEXT NOT NULL,
  primary_email TEXT,
  domain TEXT,
  stage TEXT,
  pipeline_id TEXT,
  pipeline_name TEXT,
  owner_remote_id TEXT,
  owner_name TEXT,
  amount REAL,
  currency_code TEXT,
  close_date TEXT,
  desired_cadence_days INTEGER,
  last_meaningful_interaction_at TEXT,
  next_contact_at TEXT,
  remote_revision TEXT,
  remote_updated_at TEXT,
  last_synced_at TEXT,
  access_scope_key TEXT NOT NULL,
  access_scope_json TEXT NOT NULL DEFAULT '{}',
  tombstone INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))`,
  ),
  sharesTable("crm_record_shares"),
  ownableTable(
    "crm_record_fields",
    `  id TEXT PRIMARY KEY,
  record_id TEXT NOT NULL,
  field_policy_id TEXT,
  field_name TEXT NOT NULL,
  value_type TEXT NOT NULL,
  storage_policy TEXT NOT NULL,
  string_value TEXT,
  number_value REAL,
  boolean_value INTEGER,
  json_value TEXT,
  provenance_json TEXT NOT NULL DEFAULT '[]',
  remote_revision TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))`,
  ),
  sharesTable("crm_record_field_shares"),
  ownableTable(
    "crm_relationships",
    `  id TEXT PRIMARY KEY,
  connection_id TEXT NOT NULL,
  from_record_id TEXT NOT NULL,
  to_record_id TEXT NOT NULL,
  relationship_type TEXT NOT NULL,
  label TEXT,
  inverse_label TEXT,
  source_field TEXT,
  remote_relationship_id TEXT,
  remote_revision TEXT,
  tombstone INTEGER NOT NULL DEFAULT 0,
  last_synced_at TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))`,
  ),
  sharesTable("crm_relationship_shares"),
  ownableTable(
    "crm_interactions",
    `  id TEXT PRIMARY KEY,
  record_id TEXT NOT NULL,
  connection_id TEXT,
  kind TEXT NOT NULL,
  direction TEXT NOT NULL DEFAULT 'unknown',
  title TEXT NOT NULL,
  summary TEXT NOT NULL DEFAULT '',
  occurred_at TEXT NOT NULL,
  meaningful INTEGER NOT NULL DEFAULT 1,
  provider_object_type TEXT,
  provider_remote_id TEXT,
  source_app TEXT,
  source_url TEXT,
  participants_json TEXT NOT NULL DEFAULT '[]',
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))`,
  ),
  sharesTable("crm_interaction_shares"),
  ownableTable(
    "crm_call_evidence",
    `  id TEXT PRIMARY KEY,
  interaction_id TEXT,
  record_id TEXT NOT NULL,
  source_app TEXT NOT NULL DEFAULT 'clips',
  artifact_type TEXT NOT NULL DEFAULT 'call-evidence',
  artifact_id TEXT NOT NULL,
  source_url TEXT NOT NULL,
  quote TEXT NOT NULL DEFAULT '',
  speaker TEXT,
  start_seconds REAL,
  end_seconds REAL,
  summary TEXT NOT NULL DEFAULT '',
  captured_at TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))`,
  ),
  sharesTable("crm_call_evidence_shares"),
  ownableTable(
    "crm_tasks",
    `  id TEXT PRIMARY KEY,
  record_id TEXT,
  title TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'open',
  due_at TEXT,
  assigned_to TEXT,
  authority TEXT NOT NULL DEFAULT 'local',
  connection_id TEXT,
  provider_object_type TEXT,
  provider_remote_id TEXT,
  remote_revision TEXT,
  completed_at TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))`,
  ),
  sharesTable("crm_task_shares"),
  ownableTable(
    "crm_saved_views",
    `  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  kind TEXT,
  filters_json TEXT NOT NULL DEFAULT '{}',
  columns_json TEXT NOT NULL DEFAULT '[]',
  sort_json TEXT NOT NULL DEFAULT '[]',
  data_program_id TEXT,
  pinned INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))`,
  ),
  sharesTable("crm_saved_view_shares"),
  ownableTable(
    "crm_mutations",
    `  id TEXT PRIMARY KEY,
  record_id TEXT,
  connection_id TEXT,
  operation TEXT NOT NULL,
  initiated_by TEXT NOT NULL,
  target TEXT NOT NULL,
  policy_decision TEXT NOT NULL,
  risk TEXT NOT NULL DEFAULT 'routine',
  status TEXT NOT NULL DEFAULT 'pending',
  patch_json TEXT NOT NULL DEFAULT '{}',
  before_json TEXT NOT NULL DEFAULT '{}',
  after_json TEXT NOT NULL DEFAULT '{}',
  idempotency_key TEXT NOT NULL,
  expected_remote_revision TEXT,
  provider_remote_revision TEXT,
  approved_by TEXT,
  approved_at TEXT,
  applied_at TEXT,
  error TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))`,
  ),
  sharesTable("crm_mutation_shares"),
  ownableTable(
    "crm_sync_runs",
    `  id TEXT PRIMARY KEY,
  connection_id TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'running',
  scope_json TEXT NOT NULL DEFAULT '{}',
  cursor TEXT,
  records_upserted INTEGER NOT NULL DEFAULT 0,
  tombstones_applied INTEGER NOT NULL DEFAULT 0,
  relationships_upserted INTEGER NOT NULL DEFAULT 0,
  error TEXT,
  started_at TEXT NOT NULL,
  completed_at TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now'))`,
  ),
  sharesTable("crm_sync_run_shares"),
  `CREATE UNIQUE INDEX IF NOT EXISTS crm_connections_workspace_idx ON crm_connections (workspace_connection_id)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS crm_objects_connection_type_idx ON crm_objects (connection_id, object_type)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS crm_field_policies_connection_field_idx ON crm_field_policies (connection_id, object_type, field_name)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS crm_records_remote_identity_idx ON crm_records (connection_id, object_type, remote_id)`,
  `CREATE INDEX IF NOT EXISTS crm_records_owner_updated_idx ON crm_records (owner_email, org_id, updated_at)`,
  `CREATE INDEX IF NOT EXISTS crm_records_kind_scope_idx ON crm_records (connection_id, kind, tombstone)`,
  `CREATE INDEX IF NOT EXISTS crm_records_email_idx ON crm_records (primary_email)`,
  `CREATE INDEX IF NOT EXISTS crm_records_domain_idx ON crm_records (domain)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS crm_record_fields_record_name_idx ON crm_record_fields (record_id, field_name)`,
  `CREATE INDEX IF NOT EXISTS crm_relationships_from_idx ON crm_relationships (from_record_id, tombstone)`,
  `CREATE INDEX IF NOT EXISTS crm_relationships_to_idx ON crm_relationships (to_record_id, tombstone)`,
  `CREATE INDEX IF NOT EXISTS crm_interactions_record_occurred_idx ON crm_interactions (record_id, occurred_at)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS crm_call_evidence_artifact_idx ON crm_call_evidence (source_app, artifact_id, record_id)`,
  `CREATE INDEX IF NOT EXISTS crm_call_evidence_record_idx ON crm_call_evidence (record_id, captured_at)`,
  `CREATE INDEX IF NOT EXISTS crm_tasks_owner_status_idx ON crm_tasks (owner_email, org_id, status, due_at)`,
  `CREATE INDEX IF NOT EXISTS crm_tasks_record_status_idx ON crm_tasks (record_id, status)`,
  `CREATE INDEX IF NOT EXISTS crm_saved_views_owner_pinned_idx ON crm_saved_views (owner_email, org_id, pinned, updated_at)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS crm_mutations_idempotency_idx ON crm_mutations (idempotency_key)`,
  `CREATE INDEX IF NOT EXISTS crm_mutations_owner_status_idx ON crm_mutations (owner_email, org_id, status, created_at)`,
  `CREATE INDEX IF NOT EXISTS crm_sync_runs_connection_started_idx ON crm_sync_runs (connection_id, started_at)`,
  ...[
    "crm_connection_shares",
    "crm_object_shares",
    "crm_field_policy_shares",
    "crm_record_shares",
    "crm_record_field_shares",
    "crm_relationship_shares",
    "crm_interaction_shares",
    "crm_call_evidence_shares",
    "crm_task_shares",
    "crm_saved_view_shares",
    "crm_mutation_shares",
    "crm_sync_run_shares",
  ].map(
    (name) =>
      `CREATE INDEX IF NOT EXISTS ${name}_principal_idx ON ${name} (resource_id, principal_type, principal_id)`,
  ),
].join(";\n");

const runCrmMigrations = runMigrations(
  [{ version: 1, name: "crm-initial-thin-mirror-schema", sql: initialSchema }],
  { table: "crm_migrations" },
);

function isDrizzleTable(value: unknown): value is object {
  return (
    !!value &&
    typeof value === "object" &&
    Object.getOwnPropertySymbols(value).some((symbol) =>
      symbol.toString().includes("drizzle"),
    )
  );
}

const schemaTables = Object.values(schema).filter(isDrizzleTable);

export default async (nitroApp: unknown): Promise<void> => {
  await runCrmMigrations(nitroApp);
  try {
    const result = await ensureAdditiveColumns({
      db: getDbExec(),
      tables: schemaTables,
    });
    if (result.errors.length > 0) {
      console.warn(
        "[crm/db] additive schema check reported errors",
        result.errors,
      );
    }
  } catch (error) {
    console.warn(
      "[crm/db] additive schema check failed",
      error instanceof Error ? error.message : error,
    );
  }
};
