/**
 * Vite plugin that generates end-to-end type-safe action types AND a runtime
 * registry of static imports so bundlers (Nitro on Netlify/Vercel/AWS-Lambda,
 * Rolldown, etc.) include every action file in the server bundle.
 *
 * Watches the `actions/` directory and emits:
 *   - `.generated/action-types.d.ts` — type-only module that augments the
 *     `ActionRegistry` interface in `@agent-native/core/client`, giving
 *     `useActionQuery`/`useActionMutation` full inference.
 *   - `.generated/actions-registry.ts` — runtime registry keyed by action
 *     name, with static `import` statements for every action. Templates
 *     import this file from their `server/plugins/agent-chat.ts` so Nitro
 *     bundles the actions into the server function; without it the runtime
 *     `fs.readdirSync` inside `autoDiscoverActions` finds nothing in a
 *     bundled serverless function and every action route 404s.
 */
import path from "path";
import fs from "fs";
import type { Plugin } from "vite";

/** Files to skip during discovery (matches action-discovery.ts). */
const SKIP_FILES = new Set([
  "helpers",
  "run",
  "db-connect",
  "db-status",
  "registry",
]);

function scanActionFiles(actionsDir: string): string[] {
  let files: string[];
  try {
    files = fs.readdirSync(actionsDir);
  } catch {
    return [];
  }
  return files.filter((f) => {
    if (!f.endsWith(".ts") && !f.endsWith(".js")) return false;
    const name = f.replace(/\.(ts|js)$/, "");
    if (name.startsWith("_")) return false;
    if (SKIP_FILES.has(name)) return false;
    return true;
  });
}

function toIdent(name: string): string {
  return "a_" + name.replace(/[^a-zA-Z0-9_]/g, "_");
}

function writeIfChanged(outFile: string, content: string): void {
  const existing = fs.existsSync(outFile)
    ? fs.readFileSync(outFile, "utf-8")
    : "";
  if (existing !== content) {
    fs.mkdirSync(path.dirname(outFile), { recursive: true });
    fs.writeFileSync(outFile, content);
  }
}

/**
 * Scan the actions directory and emit the types + runtime registry files.
 * Only writes files whose content has changed, to avoid triggering rebuilds.
 */
function generateActionArtifacts(
  actionsDir: string,
  projectRoot: string,
): void {
  const outDir = path.resolve(projectRoot, ".generated");
  const relActionsDir = path.relative(outDir, actionsDir).replace(/\\/g, "/");

  const actionFiles = scanActionFiles(actionsDir);

  // --- types file ---------------------------------------------------------
  const typeEntries = actionFiles.map((f) => {
    const name = f.replace(/\.(ts|js)$/, "");
    const relPath = `${relActionsDir}/${name}`;
    return `    "${name}": ActionEntry<typeof import("${relPath}")>;`;
  });

  const typesContent = `// AUTO-GENERATED by @agent-native/core — do not edit manually.
// Regenerated when files in actions/ change.
// This file augments the ActionRegistry interface so that useActionQuery and
// useActionMutation infer the correct types from your action definitions.

/** Extract the return type and parameter type from a defineAction module. */
type ActionEntry<T> = T extends { default: { run: (...args: infer A) => infer R } }
  ? {
      result: Awaited<R>;
      params: A extends [infer P, ...any[]] ? P : Record<string, any>;
    }
  : { result: any; params: Record<string, any> };

declare module "@agent-native/core/client" {
  interface ActionRegistry {
${typeEntries.join("\n")}
  }
}

export {};
`;

  writeIfChanged(path.join(outDir, "action-types.d.ts"), typesContent);

  // --- runtime registry ---------------------------------------------------
  // Static imports of each action's default export so bundlers see every
  // action and include it in the server bundle. Normalization matches
  // `loadActionsIntoRegistry` in server/action-discovery.ts.
  const imports: string[] = [];
  const entries: string[] = [];
  for (const f of actionFiles) {
    const name = f.replace(/\.(ts|js)$/, "");
    const ident = toIdent(name);
    const relPath = `${relActionsDir}/${name}`;
    imports.push(`import * as ${ident} from "${relPath}";`);
    entries.push(`  ${JSON.stringify(name)}: ${ident},`);
  }

  const registryContent = `// AUTO-GENERATED by @agent-native/core — do not edit manually.
// Static-import registry of every action file. Bundlers (Nitro, Rolldown)
// see these imports and include the action modules in the server bundle.
// The agent-chat plugin normalizes each module into an ActionEntry shape.
${imports.join("\n")}

const modules: Record<string, unknown> = {
${entries.join("\n")}
};

export default modules;
`;

  writeIfChanged(
    path.join(outDir, "actions-registry.ts"),
    actionFiles.length === 0
      ? `// AUTO-GENERATED by @agent-native/core — no actions/ files found.
const modules: Record<string, unknown> = {};
export default modules;
`
      : registryContent,
  );

  // Ensure .generated/ is in .gitignore
  const gitignorePath = path.join(projectRoot, ".gitignore");
  if (fs.existsSync(gitignorePath)) {
    const gitignore = fs.readFileSync(gitignorePath, "utf-8");
    if (!gitignore.includes(".generated")) {
      fs.appendFileSync(gitignorePath, "\n.generated/\n");
    }
  }
}

/**
 * Vite plugin that watches `actions/` and generates type-safe action types.
 *
 * Add to your Vite config (auto-included by `defineConfig` from `@agent-native/core`):
 *
 * ```ts
 * import { actionTypesPlugin } from "@agent-native/core/vite/action-types-plugin";
 * plugins: [actionTypesPlugin()]
 * ```
 */
export function actionTypesPlugin(): Plugin {
  let projectRoot = "";
  let actionsDir = "";

  return {
    name: "agent-native-action-types",
    configResolved(config) {
      projectRoot = config.root;
      actionsDir = path.resolve(projectRoot, "actions");
    },
    buildStart() {
      generateActionArtifacts(actionsDir, projectRoot);
    },
    configureServer(server) {
      // Generate on startup
      generateActionArtifacts(actionsDir, projectRoot);

      // Watch for changes in actions/
      const watcher = server.watcher;
      const handleChange = (file: string) => {
        if (file.startsWith(actionsDir) && /\.(ts|js)$/.test(file)) {
          generateActionArtifacts(actionsDir, projectRoot);
        }
      };
      watcher.add(actionsDir);
      watcher.on("add", handleChange);
      watcher.on("unlink", handleChange);
      // Don't regenerate on content changes — only file additions/removals
      // affect the registry. Return type changes are picked up by TypeScript
      // from the source files via typeof import().
    },
  };
}

/**
 * Public helper to regenerate the types + registry from a non-Vite context
 * (e.g. the Nitro deploy build, where Vite plugins don't run).
 */
export function generateActionRegistryForProject(projectRoot: string): void {
  const actionsDir = path.resolve(projectRoot, "actions");
  generateActionArtifacts(actionsDir, projectRoot);
}
