/**
 * Vite plugin that generates end-to-end type-safe action types.
 *
 * Watches the `actions/` directory and emits `.generated/action-types.d.ts`,
 * which augments the `ActionRegistry` interface in `@agent-native/core/client`.
 * This gives `useActionQuery` and `useActionMutation` full type inference
 * for action names, parameters, and return types — similar to tRPC.
 *
 * The generated file uses `typeof import()` to reference action source files,
 * so TypeScript resolves the actual types at type-check time without any
 * runtime cost or complex AST parsing.
 */
import path from "path";
import fs from "fs";
import type { Plugin } from "vite";

/** Files to skip during discovery (matches action-discovery.ts). */
const SKIP_FILES = new Set([
  "helpers",
  "run",
  "db-connect",
  "db-status",
  "registry",
]);

/**
 * Scan the actions directory and emit a `.generated/action-types.d.ts` file.
 * Only writes if the content has changed, to avoid triggering unnecessary rebuilds.
 */
function generateActionTypes(actionsDir: string, projectRoot: string): void {
  let files: string[];
  try {
    files = fs.readdirSync(actionsDir);
  } catch {
    return; // No actions directory — nothing to generate
  }

  const actionFiles = files.filter((f) => {
    if (!f.endsWith(".ts") && !f.endsWith(".js")) return false;
    const name = f.replace(/\.(ts|js)$/, "");
    if (name.startsWith("_")) return false;
    if (SKIP_FILES.has(name)) return false;
    return true;
  });

  // Compute relative path from .generated/ to actions/
  const outDir = path.resolve(projectRoot, ".generated");
  const relActionsDir = path.relative(outDir, actionsDir).replace(/\\/g, "/");

  const entries = actionFiles.map((f) => {
    const name = f.replace(/\.(ts|js)$/, "");
    const relPath = `${relActionsDir}/${name}`;
    return `    "${name}": ActionEntry<typeof import("${relPath}")>;`;
  });

  const content = `// AUTO-GENERATED by @agent-native/core — do not edit manually.
// Regenerated when files in actions/ change.
// This file augments the ActionRegistry interface so that useActionQuery and
// useActionMutation infer the correct types from your action definitions.

/** Extract the return type and parameter type from a defineAction module. */
type ActionEntry<T> = T extends { default: { run: (...args: infer A) => infer R } }
  ? {
      result: Awaited<R>;
      params: A extends [infer P, ...any[]] ? P : Record<string, any>;
    }
  : { result: any; params: Record<string, any> };

declare module "@agent-native/core/client" {
  interface ActionRegistry {
${entries.join("\n")}
  }
}

export {};
`;

  fs.mkdirSync(outDir, { recursive: true });

  const outFile = path.join(outDir, "action-types.d.ts");
  const existing = fs.existsSync(outFile)
    ? fs.readFileSync(outFile, "utf-8")
    : "";
  if (existing !== content) {
    fs.writeFileSync(outFile, content);
  }

  // Ensure .generated/ is in .gitignore
  const gitignorePath = path.join(projectRoot, ".gitignore");
  if (fs.existsSync(gitignorePath)) {
    const gitignore = fs.readFileSync(gitignorePath, "utf-8");
    if (!gitignore.includes(".generated")) {
      fs.appendFileSync(gitignorePath, "\n.generated/\n");
    }
  }
}

/**
 * Vite plugin that watches `actions/` and generates type-safe action types.
 *
 * Add to your Vite config (auto-included by `defineConfig` from `@agent-native/core`):
 *
 * ```ts
 * import { actionTypesPlugin } from "@agent-native/core/vite/action-types-plugin";
 * plugins: [actionTypesPlugin()]
 * ```
 */
export function actionTypesPlugin(): Plugin {
  let projectRoot = "";
  let actionsDir = "";

  return {
    name: "agent-native-action-types",
    configResolved(config) {
      projectRoot = config.root;
      actionsDir = path.resolve(projectRoot, "actions");
    },
    buildStart() {
      generateActionTypes(actionsDir, projectRoot);
    },
    configureServer(server) {
      // Generate on startup
      generateActionTypes(actionsDir, projectRoot);

      // Watch for changes in actions/
      const watcher = server.watcher;
      const handleChange = (file: string) => {
        if (file.startsWith(actionsDir) && /\.(ts|js)$/.test(file)) {
          generateActionTypes(actionsDir, projectRoot);
        }
      };
      watcher.add(actionsDir);
      watcher.on("add", handleChange);
      watcher.on("unlink", handleChange);
      // Don't regenerate on content changes — only file additions/removals
      // affect the registry. Return type changes are picked up by TypeScript
      // from the source files via typeof import().
    },
  };
}
