/**
 * Vite plugin that resolves `virtual:agents-bundle` to a statically-inlined
 * ES module containing the template's AGENTS.md + .agents/skills/ content.
 *
 * This is how the framework's agent gets its instructions and skills into the
 * system prompt on EVERY deployment target — Node, Netlify Functions, Vercel
 * serverless, and Cloudflare Workers. The content is baked into the server
 * bundle at build time, so nothing needs to exist on the runtime filesystem.
 *
 * In dev mode, the plugin re-reads from disk on each import and triggers HMR
 * when any AGENTS.md or SKILL.md file changes, so edits show up instantly
 * without restarting the server.
 */
import path from "path";
import fs from "fs";
import type { Plugin } from "vite";
import { readAgentsBundleFromFs } from "../server/agents-bundle.js";

const VIRTUAL_ID = "virtual:agents-bundle";
const RESOLVED_ID = "\0" + VIRTUAL_ID;

function emitBundleModule(projectRoot: string): string {
  const bundle = readAgentsBundleFromFs(projectRoot);
  // Serialize as JSON and wrap in `export default` — this produces a valid
  // ES module that any bundler (Rollup, esbuild, Rolldown) can statically
  // analyze and tree-shake if nothing imports it.
  return `// AUTO-GENERATED by @agent-native/core/vite/agents-bundle-plugin
// Contains the inlined AGENTS.md + .agents/skills/ content from the template.
const bundle = ${JSON.stringify(bundle)};
export default bundle;
`;
}

export function agentsBundlePlugin(): Plugin {
  let projectRoot = "";

  return {
    name: "agent-native-agents-bundle",

    configResolved(config) {
      projectRoot = config.root;
    },

    resolveId(id) {
      if (id === VIRTUAL_ID) return RESOLVED_ID;
      return null;
    },

    load(id) {
      if (id !== RESOLVED_ID) return null;
      if (!projectRoot) projectRoot = process.cwd();
      return emitBundleModule(projectRoot);
    },

    configureServer(server) {
      // Watch AGENTS.md + any SKILL.md changes and invalidate the virtual
      // module so the next request picks up fresh content.
      const watcher = server.watcher;

      const shouldInvalidate = (file: string): boolean => {
        const rel = path.relative(projectRoot, file);
        if (rel.startsWith("..")) return false;
        if (rel === "AGENTS.md") return true;
        if (
          rel.startsWith(".agents" + path.sep + "skills") &&
          rel.endsWith("SKILL.md")
        )
          return true;
        return false;
      };

      const invalidate = (file: string) => {
        if (!shouldInvalidate(file)) return;
        const mod = server.moduleGraph.getModuleById(RESOLVED_ID);
        if (mod) {
          server.moduleGraph.invalidateModule(mod);
          server.ws.send({ type: "full-reload" });
        }
      };

      // Also explicitly watch AGENTS.md and the skills directory so edits to
      // files outside the normal Vite watch set still trigger invalidation.
      const agentsMdPath = path.join(projectRoot, "AGENTS.md");
      const skillsDir = path.join(projectRoot, ".agents", "skills");
      if (fs.existsSync(agentsMdPath)) watcher.add(agentsMdPath);
      if (fs.existsSync(skillsDir)) watcher.add(skillsDir);

      watcher.on("change", invalidate);
      watcher.on("add", invalidate);
      watcher.on("unlink", invalidate);
    },
  };
}
