import type { VideoProvider } from "./types.js";

export const googleMeetProvider: VideoProvider = {
  kind: "google_meet",
  label: "Google Meet",
  async createMeeting({ booking }) {
    // Meeting URL is generated by Google Calendar. If the consumer calls this
    return {
      meetingUrl: "",
      meetingId: `meet_${booking.uid}`,
    };
  },
};
