// Auto-generated by scripts/generate-search-index.ts — do not edit manually

export interface SearchEntry {
  page: string;
  path: string;
  section: string;
  sectionId: string;
  text: string;
}

export const searchIndex: SearchEntry[] = [
  {
    "page": "Getting Started",
    "path": "/docs",
    "section": "Create Your App",
    "sectionId": "create-your-app",
    "text": "The CLI walks you through picking a template — or starting blank. Then run it: That's it — you have a full app running locally with an AI agent built in. Open the agent panel, ask it to do something, and watch it work. From here, use your AI coding tool (Claude Code, Cursor, Windsurf, etc.) to..."
  },
  {
    "page": "Getting Started",
    "path": "/docs",
    "section": "Templates",
    "sectionId": "templates",
    "text": "Each template is a complete app with UI, agent actions, database schema, and AI instructions ready to go: Template Replaces > ))} Browse the template gallery for live demos and detailed feature lists."
  },
  {
    "page": "Getting Started",
    "path": "/docs",
    "section": "Project Structure",
    "sectionId": "project-structure",
    "text": "Every agent-native app — whether from a template or from scratch — follows the same structure: Templates add domain-specific code on top of this: database schemas in server/db/ , API routes in server/routes/api/ , and actions in actions/ ."
  },
  {
    "page": "Getting Started",
    "path": "/docs",
    "section": "Configuration",
    "sectionId": "configuration",
    "text": "Templates come pre-configured. If you're starting from scratch, here are the config files:"
  },
  {
    "page": "Getting Started",
    "path": "/docs",
    "section": "Architecture Principles",
    "sectionId": "architecture-principles",
    "text": "These principles apply to all agent-native apps. Understanding them helps you customize templates or build from scratch: Agent + UI are equal partners — Everything the UI can do, the agent can do, and vice versa. They share the same database and always stay in sync. You don't think about \"the..."
  },
  {
    "page": "A2A Protocol",
    "path": "/docs/a2a-protocol",
    "section": "Overview",
    "sectionId": "overview",
    "text": "A2A (agent-to-agent) is a JSON-RPC protocol for inter-agent communication. A mail agent can ask an analytics agent to run a query. A calendar agent can search issues in a project management agent. Each agent exposes its capabilities via an agent card and accepts work via a standard JSON-RPC..."
  },
  {
    "page": "A2A Protocol",
    "path": "/docs/a2a-protocol",
    "section": "Server setup",
    "sectionId": "server-setup",
    "text": "Call mountA2A() in a server plugin to expose the A2A endpoints: This mounts two endpoints: GET /.well-known/agent-card.json (public, no auth) and POST /a2a (authenticated JSON-RPC)."
  },
  {
    "page": "A2A Protocol",
    "path": "/docs/a2a-protocol",
    "section": "Agent card",
    "sectionId": "agent-card",
    "text": "The agent card is auto-generated from your config and served at /.well-known/agent-card.json . Other agents fetch it to discover your agent's skills."
  },
  {
    "page": "A2A Protocol",
    "path": "/docs/a2a-protocol",
    "section": "JSON-RPC methods",
    "sectionId": "json-rpc-methods",
    "text": "All methods are called via POST /a2a with JSON-RPC 2.0 format: Method Description Key params > ))} Messages contain typed parts:"
  },
  {
    "page": "A2A Protocol",
    "path": "/docs/a2a-protocol",
    "section": "Client",
    "sectionId": "client",
    "text": "The A2AClient class handles discovery, messaging, and streaming:"
  },
  {
    "page": "A2A Protocol",
    "path": "/docs/a2a-protocol",
    "section": "Convenience helper",
    "sectionId": "convenience-helper",
    "text": "For simple text-in/text-out calls, use callAgent() :"
  },
  {
    "page": "A2A Protocol",
    "path": "/docs/a2a-protocol",
    "section": "Task lifecycle",
    "sectionId": "task-lifecycle",
    "text": "Each message creates a task that moves through these states: submitted &rarr; working &rarr; completed | failed | canceled State Meaning > ))} Tasks persist in the a2a_tasks SQL table and can be retrieved later via tasks/get ."
  },
  {
    "page": "A2A Protocol",
    "path": "/docs/a2a-protocol",
    "section": "Security",
    "sectionId": "security",
    "text": "Set apiKeyEnv in your config to the name of an environment variable containing the expected bearer token: The agent card endpoint is always public (no auth) so other agents can discover capabilities. The /a2a JSON-RPC endpoint requires a valid bearer token when apiKeyEnv is set. In dev mode (no env..."
  },
  {
    "page": "A2A Protocol",
    "path": "/docs/a2a-protocol",
    "section": "Agent mentions",
    "sectionId": "agent-mentions",
    "text": "You can @ -mention agents directly in the chat composer. When you mention an agent, the server makes an A2A call to that agent and weaves the response into your conversation context. This is the easiest way to use A2A — no code required, just type @ and select an agent. See Agent Mentions for..."
  },
  {
    "page": "A2A Protocol",
    "path": "/docs/a2a-protocol",
    "section": "Messaging integrations",
    "sectionId": "messaging-integrations",
    "text": "Agents can also be reached from external messaging platforms like Slack, Telegram, and WhatsApp. Users send messages on those platforms and the agent responds in the same thread, using the same tools and actions as the web chat. See Integrations for setup details on each platform."
  },
  {
    "page": "A2A Protocol",
    "path": "/docs/a2a-protocol",
    "section": "Example: cross-agent query",
    "sectionId": "example",
    "text": "A mail agent needs analytics data. The analytics agent exposes a \"run-query\" skill via A2A: The analytics agent receives the message, runs the query via its handler, and returns the result. The mail agent's script gets the text response back. No shared database, no direct API calls — just..."
  },
  {
    "page": "Actions",
    "path": "/docs/actions",
    "section": "Action Dispatcher",
    "sectionId": "action-dispatcher",
    "text": "The action system lets you create actions that agents can invoke via pnpm action &lt;name&gt; . Each action is a TypeScript file that exports a default async function."
  },
  {
    "page": "Actions",
    "path": "/docs/actions",
    "section": "parseArgs(args)",
    "sectionId": "parseargs",
    "text": "Parse CLI arguments in --key value or --key=value format:"
  },
  {
    "page": "Actions",
    "path": "/docs/actions",
    "section": "Standard actions",
    "sectionId": "standard-actions",
    "text": "Every template should include these two actions for context awareness :"
  },
  {
    "page": "Actions",
    "path": "/docs/actions",
    "section": "view-screen",
    "sectionId": "view-screen",
    "text": "Reads the current navigation state, fetches contextual data, and returns a snapshot of what the user sees. The agent should always call this before acting."
  },
  {
    "page": "Actions",
    "path": "/docs/actions",
    "section": "navigate",
    "sectionId": "navigate",
    "text": "Writes a one-shot navigation command to application-state. The UI reads it, navigates, and deletes the entry."
  },
  {
    "page": "Actions",
    "path": "/docs/actions",
    "section": "Shared Agent Chat",
    "sectionId": "shared-agent-chat",
    "text": "@agent-native/core provides an isomorphic chat bridge that works in both browser and Node.js: In the browser, messages are sent via window.postMessage() . In Node.js (actions), they use the BUILDER_PARENT_MESSAGE: stdout format that the Electron host translates to postMessage."
  },
  {
    "page": "Actions",
    "path": "/docs/actions",
    "section": "Utility Functions",
    "sectionId": "utility-functions",
    "text": "Function Returns Description > ))} ); }"
  },
  {
    "page": "Agent Mentions",
    "path": "/docs/agent-mentions",
    "section": "Overview",
    "sectionId": "overview",
    "text": "The @ -mention system connects the chat composer to the broader agent ecosystem. When you type @ , a popover appears listing available agents, codebase files, and resources. Selecting an agent sends a cross-agent request via the A2A protocol , and the response is embedded directly in the..."
  },
  {
    "page": "Agent Mentions",
    "path": "/docs/agent-mentions",
    "section": "Mentioning agents",
    "sectionId": "mentioning-agents",
    "text": "To mention an agent in the chat composer: Type @ to open the mention popover Browse or search the list of available agents Select an agent — it appears as a tag in your message Send the message — the server calls the mentioned agent via A2A and includes its response in the conversation context The..."
  },
  {
    "page": "Agent Mentions",
    "path": "/docs/agent-mentions",
    "section": "How it works",
    "sectionId": "how-it-works",
    "text": "When a message containing an @ -mention is sent, the following happens on the server: The server extracts mention references from the message For each mentioned agent, an A2A call is made to that agent's endpoint The agent's response is wrapped in an &lt;agent-response&gt; XML block and injected..."
  },
  {
    "page": "Agent Mentions",
    "path": "/docs/agent-mentions",
    "section": "Adding agents",
    "sectionId": "adding-agents",
    "text": "Agents become available for mentioning through several mechanisms: Auto-discovery — the framework automatically discovers agents running on known ports or configured URLs Resources panel — add agent manifests as agents/*.json files in the resources panel Environment variables — configure agent URLs..."
  },
  {
    "page": "Agent Mentions",
    "path": "/docs/agent-mentions",
    "section": "Custom mention providers",
    "sectionId": "custom-mention-providers",
    "text": "Templates can register custom mention providers to add domain-specific mentionable items beyond agents and files. A mention provider implements the MentionProvider interface: ()); }, // Resolve a mention into context for the agent async resolve(id: string) ); return (\\$)\\`, }; }, };`} /> Register..."
  },
  {
    "page": "Agent Mentions",
    "path": "/docs/agent-mentions",
    "section": "Referencing files",
    "sectionId": "referencing-files",
    "text": "The @ popover is not limited to agents. You can also reference: Codebase files — type @ and search for a filename. The file contents are included in the agent's context so it can read, analyze, or modify the file. Resources — reference resources defined in the resources panel. These can be data..."
  },
  {
    "page": "Authentication",
    "path": "/docs/authentication",
    "section": "Overview",
    "sectionId": "overview",
    "text": "Auth is configured automatically via autoMountAuth(app) in the auth server plugin. The behavior depends on your environment: Default: Better Auth with email/password + social providers. Onboarding page shown on first visit. AUTH_MODE=local : No auth. Solo local development with local@localhost..."
  },
  {
    "page": "Authentication",
    "path": "/docs/authentication",
    "section": "Better Auth (Default)",
    "sectionId": "better-auth",
    "text": "When no ACCESS_TOKEN or AUTH_MODE=local is set, Better Auth powers authentication. It provides: Email/password registration and login Social providers (Google, GitHub, and 35+ others) Organizations with roles and invitations JWT tokens for API and A2A access Bearer token support for programmatic..."
  },
  {
    "page": "Authentication",
    "path": "/docs/authentication",
    "section": "Local Mode",
    "sectionId": "local-mode",
    "text": "For solo local development without auth, set AUTH_MODE=local in your .env file. This returns for all requests. You can also enable local mode from the onboarding page by clicking \"Use locally without an account\". This writes AUTH_MODE=local to your .env automatically. Local mode works in any..."
  },
  {
    "page": "Authentication",
    "path": "/docs/authentication",
    "section": "Social Providers",
    "sectionId": "social-providers",
    "text": "Set environment variables to enable social login. Better Auth auto-detects them: Templates that use createGoogleAuthPlugin() show a \"Sign in with Google\" page. The Google OAuth callback handles mobile deep linking for native apps automatically."
  },
  {
    "page": "Authentication",
    "path": "/docs/authentication",
    "section": "Organizations",
    "sectionId": "organizations",
    "text": "Better Auth's organization plugin is built into the framework. Every app supports: Creating organizations Inviting members with roles ( owner , admin , member ) Switching active organization Per-org data scoping via org_id columns The active organization flows automatically through the system:..."
  },
  {
    "page": "Authentication",
    "path": "/docs/authentication",
    "section": "Access Tokens",
    "sectionId": "access-tokens",
    "text": "For simple deployments, set ACCESS_TOKEN (single) or ACCESS_TOKENS (comma-separated) as environment variables: When access tokens are configured, users see a token login page. Sessions are cookie-based with 30-day expiry."
  },
  {
    "page": "Authentication",
    "path": "/docs/authentication",
    "section": "Bring Your Own Auth",
    "sectionId": "byoa",
    "text": "Pass a custom getSession callback to use any auth provider (Clerk, Auth0, Firebase, etc.):"
  },
  {
    "page": "Authentication",
    "path": "/docs/authentication",
    "section": "Session API",
    "sectionId": "session-api",
    "text": "The session object returned by getSession(event) has this shape: On the client, use the useSession() hook:"
  },
  {
    "page": "Authentication",
    "path": "/docs/authentication",
    "section": "Environment Variables",
    "sectionId": "environment-variables",
    "text": "Variable Purpose AUTH_MODE Set to local to disable auth BETTER_AUTH_SECRET Signing key for Better Auth (auto-generated if not set) GOOGLE_CLIENT_ID Enable Google OAuth GOOGLE_CLIENT_SECRET Google OAuth secret GITHUB_CLIENT_ID Enable GitHub OAuth GITHUB_CLIENT_SECRET GitHub OAuth secret ACCESS_TOKEN..."
  },
  {
    "page": "CLI Adapters",
    "path": "/docs/cli-adapters",
    "section": "Overview",
    "sectionId": "overview",
    "text": "Agents are great at running CLI commands. But without structure, every script reinvents how to invoke a CLI, check if it's installed, and parse its output. CLI adapters solve this with a small interface. Each adapter wraps a single CLI ( gh , ffmpeg , stripe , aws ) and provides: Discovery — the..."
  },
  {
    "page": "CLI Adapters",
    "path": "/docs/cli-adapters",
    "section": "The interface",
    "sectionId": "the-interface",
    "text": "Every CLI adapter implements CliAdapter :"
  },
  {
    "page": "CLI Adapters",
    "path": "/docs/cli-adapters",
    "section": "ShellCliAdapter",
    "sectionId": "shell-adapter",
    "text": "For most CLIs, you don't need a custom class. ShellCliAdapter wraps any CLI binary with sensible defaults:"
  },
  {
    "page": "CLI Adapters",
    "path": "/docs/cli-adapters",
    "section": "Options",
    "sectionId": "shell-adapter-options",
    "text": "Option Type Description command string Binary name or path (required) description string What the CLI does — shown to the agent (required) name string Display name (defaults to command ) env Record Extra environment variables merged with process.env cwd string Working directory (defaults to..."
  },
  {
    "page": "CLI Adapters",
    "path": "/docs/cli-adapters",
    "section": "Registry",
    "sectionId": "registry",
    "text": "The CliRegistry collects adapters so the agent can discover what's available at runtime:"
  },
  {
    "page": "CLI Adapters",
    "path": "/docs/cli-adapters",
    "section": "Custom adapters",
    "sectionId": "custom-adapter",
    "text": "When you need more than ShellCliAdapter provides — custom auth, output parsing, or pre/post processing — implement CliAdapter directly:"
  },
  {
    "page": "CLI Adapters",
    "path": "/docs/cli-adapters",
    "section": "Server route",
    "sectionId": "server-route",
    "text": "Expose the registry to the UI via an API route so actions and components can discover and invoke CLIs:"
  },
  {
    "page": "CLI Adapters",
    "path": "/docs/cli-adapters",
    "section": "Using from actions",
    "sectionId": "from-actions",
    "text": "Actions can use CLI adapters directly for structured access: [ , , ]; const gh = new ShellCliAdapter(); export default async function listPrs() const result = await gh.execute([ \"pr\", \"list\", \"--json\", \"title,url,state\", \"--limit\", \"10\" ]); if (result.exitCode !== 0) const prs =..."
  },
  {
    "page": "Context Awareness",
    "path": "/docs/context-awareness",
    "section": "Overview",
    "sectionId": "overview",
    "text": "Without context awareness, the agent is blind. It asks \"which email?\" when the user is staring at one. It cannot act on the current selection, cannot provide relevant suggestions, and cannot modify what the user sees. Three patterns solve this: Navigation state — the UI writes a navigation key to..."
  },
  {
    "page": "Context Awareness",
    "path": "/docs/context-awareness",
    "section": "Navigation state",
    "sectionId": "navigation-state",
    "text": "The UI writes a navigation key to application-state on every route change. This tells the agent what view the user is on and what item is selected. What to include in navigation state: view — the current page/section (e.g., \"inbox\", \"form-builder\", \"dashboard\") Item IDs — the selected/open item..."
  },
  {
    "page": "Context Awareness",
    "path": "/docs/context-awareness",
    "section": "The view-screen action",
    "sectionId": "view-screen-action",
    "text": "Every template should have a view-screen action. It reads navigation state, fetches the relevant data, and returns a snapshot of what the user sees. This is the agent's eyes. The agent should always call pnpm action view-screen before acting. This is a hard convention across all templates. When..."
  },
  {
    "page": "Context Awareness",
    "path": "/docs/context-awareness",
    "section": "The navigate action",
    "sectionId": "navigate-action",
    "text": "The agent writes a one-shot navigate command to application-state. The UI reads it, performs the navigation, and deletes the entry. The UI polls for this command and navigates when it appears: The navigation key belongs to the UI — the agent should never write to it directly. Instead, the agent..."
  },
  {
    "page": "Context Awareness",
    "path": "/docs/context-awareness",
    "section": "useNavigationState hook",
    "sectionId": "use-navigation-state",
    "text": "The use-navigation-state.ts hook syncs routes to application-state on every navigation: The deriveNavigationState() function is template-specific — it parses the URL path and extracts the view, item IDs, and filters relevant to your app."
  },
  {
    "page": "Context Awareness",
    "path": "/docs/context-awareness",
    "section": "Jitter prevention",
    "sectionId": "jitter-prevention",
    "text": "When the agent writes to application-state, the polling system might cause the UI to refetch data it just wrote. This creates jitter. The solution is source tagging: How it works: Agent writes are tagged with (the action helpers do this automatically) UI writes include the tab's unique ID via..."
  },
  {
    "page": "Creating Templates",
    "path": "/docs/creating-templates",
    "section": "Overview",
    "sectionId": "overview",
    "text": "Templates are complete, forkable agent-native apps that solve a specific use case. The analytics, content, slides, and video templates that ship with Agent-Native are all built this way. Anyone can create a template and share it with the community. A good template: Solves a real workflow end-to-end..."
  },
  {
    "page": "Creating Templates",
    "path": "/docs/creating-templates",
    "section": "Start from the starter",
    "sectionId": "start-from-starter",
    "text": "The fastest way to start is with the built-in starter template: This scaffolds a minimal agent-native app with the standard directory structure, a working dev server, file watching, SSE, and an example action. Build your template on top of this."
  },
  {
    "page": "Creating Templates",
    "path": "/docs/creating-templates",
    "section": "Project structure",
    "sectionId": "project-structure",
    "text": "Every template follows the same convention:"
  },
  {
    "page": "Creating Templates",
    "path": "/docs/creating-templates",
    "section": "Build your client",
    "sectionId": "build-your-client",
    "text": "The client uses React Router v7 framework mode with file-based routing. Pages go in app/routes/ , global providers live in app/root.tsx , and React Query handles data fetching. Routes are auto-discovered from app/routes/ via flatRoutes() . Create a file to add a page: The useDbSync hook (formerly..."
  },
  {
    "page": "Creating Templates",
    "path": "/docs/creating-templates",
    "section": "Add API routes",
    "sectionId": "add-api-routes",
    "text": "API routes serve data from files and handle mutations. They go in server/routes/ as file-based routes: Each route file exports a default defineEventHandler . Both the UI and the agent can create items — the UI via POST /api/items , the agent by writing directly to data/items/ . The SSE watcher..."
  },
  {
    "page": "Creating Templates",
    "path": "/docs/creating-templates",
    "section": "Add actions",
    "sectionId": "add-actions",
    "text": "Actions are the agent's toolbox. Each action handles one operation — fetching data from an API, generating content, processing files, etc: [ , , ]; export default async function importData(args: string[]) = parseArgs(args); if (!url) const res = await fetch(url); const data = await res.json();..."
  },
  {
    "page": "Creating Templates",
    "path": "/docs/creating-templates",
    "section": "Add data models",
    "sectionId": "add-data-models",
    "text": "Seed your template with example data so it works immediately. Put JSON files in data/ matching the structure your API routes expect: Keep your data models simple — flat JSON files, one per entity. The agent can grep, read, and modify them. Deeply nested structures or binary formats make it harder..."
  },
  {
    "page": "Creating Templates",
    "path": "/docs/creating-templates",
    "section": "Write AGENTS.md",
    "sectionId": "write-agents-md",
    "text": "This is the most important file in your template. AGENTS.md tells the AI agent how your app works, what it can and can't do, and how to make changes: Be specific about your data models, available actions, and key patterns. The better your AGENTS.md , the better the agent will work with your..."
  },
  {
    "page": "Creating Templates",
    "path": "/docs/creating-templates",
    "section": "Add skills",
    "sectionId": "add-skills",
    "text": "For complex topics that don't fit in AGENTS.md , create skills in .agents/skills/ . Each skill is a Markdown file with detailed guidance for a specific topic: Skills let you give the agent deep domain knowledge for specific integrations or patterns without bloating your main AGENTS.md ."
  },
  {
    "page": "Creating Templates",
    "path": "/docs/creating-templates",
    "section": "Onboarding & API keys",
    "sectionId": "onboarding",
    "text": "If your template needs API keys or external service configuration, document them in a .env.example file: When users fork your template, they copy .env.example to .env and fill in their own values. Keep the number of required keys minimal — the template should work with example data before any keys..."
  },
  {
    "page": "Creating Templates",
    "path": "/docs/creating-templates",
    "section": "Publishing",
    "sectionId": "publishing",
    "text": "To share your template: Push your template to a public GitHub repo Make sure it works with pnpm install && pnpm dev Include seed data in data/ so it works without API keys Write a clear README explaining what the template does and how to configure it Community templates can be shared via GitHub...."
  },
  {
    "page": "Deployment",
    "path": "/docs/deployment",
    "section": "How It Works",
    "sectionId": "how-it-works",
    "text": "When you run agent-native build , Nitro builds both the client SPA and the server API into .output/ : The output is self-contained — copy .output/ to any environment and run it."
  },
  {
    "page": "Deployment",
    "path": "/docs/deployment",
    "section": "Setting the Preset",
    "sectionId": "setting-the-preset",
    "text": "By default, Nitro builds for Node.js. To target a different platform, set the preset in your vite.config.ts : Or use the NITRO_PRESET environment variable at build time:"
  },
  {
    "page": "Deployment",
    "path": "/docs/deployment",
    "section": "Node.js (Default)",
    "sectionId": "nodejs",
    "text": "The default preset. Build and run: Set PORT to configure the listen port (default: 3000 )."
  },
  {
    "page": "Deployment",
    "path": "/docs/deployment",
    "section": "Vercel",
    "sectionId": "vercel",
    "text": "Deploy via the Vercel CLI or git push:"
  },
  {
    "page": "Deployment",
    "path": "/docs/deployment",
    "section": "Netlify",
    "sectionId": "netlify",
    "text": "Deploy via the Netlify CLI or git push:"
  },
  {
    "page": "Deployment",
    "path": "/docs/deployment",
    "section": "Environment Variables",
    "sectionId": "environment-variables",
    "text": "Variable Description > ))} ); }"
  },
  {
    "page": "FAQ",
    "path": "/docs/faq",
    "section": "What is agent-native?",
    "sectionId": "what-is-agent-native",
    "text": "Agent-native is a framework for building apps where the AI agent and the UI are equal partners. They share the same database, the same state, and they always stay in sync. Everything the UI can do, the agent can do — and vice versa. See What Is Agent-Native? for the full explanation."
  },
  {
    "page": "FAQ",
    "path": "/docs/faq",
    "section": "How is this different from adding AI to an existing app?",
    "sectionId": "how-is-this-different",
    "text": "Most apps bolt AI on as an afterthought — an autocomplete here, a chat sidebar there. The AI can't actually do things in the app. In an agent-native app, the agent is a first-class citizen. It can create emails, schedule events, build forms, generate slides, and modify the app's own code. The..."
  },
  {
    "page": "FAQ",
    "path": "/docs/faq",
    "section": "Do I need to know AI/ML?",
    "sectionId": "do-i-need-to-know-ai",
    "text": "No. You don't train models, fine-tune, or deal with embeddings. You build a regular web app with React, TypeScript, and SQL. The framework handles the agent integration — routing messages, running actions, syncing state. You write standard web code and the agent just works."
  },
  {
    "page": "FAQ",
    "path": "/docs/faq",
    "section": "Is this open source?",
    "sectionId": "is-this-open-source",
    "text": "Yes. The framework and all templates are open source. You can run everything locally, self-host, or use Builder.io's cloud for managed hosting, collaboration, and team features."
  },
  {
    "page": "FAQ",
    "path": "/docs/faq",
    "section": "Which AI coding tools work with agent-native?",
    "sectionId": "which-ai-tools-work",
    "text": "Any AI coding tool that reads project instructions. The framework uses AGENTS.md as the universal standard and auto-creates symlinks for specific tools: Claude Code — reads CLAUDE.md (symlinked from AGENTS.md) Cursor — reads .cursorrules (symlinked from AGENTS.md) Windsurf — reads .windsurfrules..."
  },
  {
    "page": "FAQ",
    "path": "/docs/faq",
    "section": "Can I use my own database?",
    "sectionId": "can-i-use-my-own-database",
    "text": "Yes. Set DATABASE_URL and the framework auto-detects your database. Supported databases include SQLite, Postgres (Neon, Supabase, plain), Turso (libSQL), and Cloudflare D1. All SQL is dialect-agnostic via Drizzle ORM — the same code works everywhere."
  },
  {
    "page": "FAQ",
    "path": "/docs/faq",
    "section": "Where can I deploy?",
    "sectionId": "where-can-i-deploy",
    "text": "Anywhere. The server runs on Nitro, which compiles to any deployment target: Node.js, Cloudflare Workers/Pages, Netlify, Vercel, Deno Deploy, AWS Lambda, and Bun. You can also use Builder.io's hosting for managed deployments. See the Deployment guide ."
  },
  {
    "page": "FAQ",
    "path": "/docs/faq",
    "section": "Can I migrate an existing app to agent-native?",
    "sectionId": "can-i-use-existing-code",
    "text": "You can, but agent-native works best when built from the ground up. The architecture — shared database, polling sync, actions, application state — needs to be integrated throughout. Starting from a template and customizing it is the recommended path. Think of it like the shift from desktop-first to..."
  },
  {
    "page": "FAQ",
    "path": "/docs/faq",
    "section": "Why polling instead of WebSockets?",
    "sectionId": "why-polling-not-websockets",
    "text": "Polling works in every deployment environment — including serverless, edge, and container platforms where persistent connections aren't available. The framework polls every 2 seconds using a lightweight version counter. When changes are detected, React Query caches are invalidated and components..."
  },
  {
    "page": "FAQ",
    "path": "/docs/faq",
    "section": "Why can't the UI call an LLM directly?",
    "sectionId": "why-no-inline-llm-calls",
    "text": "AI is non-deterministic — you need conversation flow to give feedback and iterate, not one-shot buttons. The agent has your full codebase, instructions, skills, and conversation history. An inline LLM call has none of that. Plus, routing everything through the agent means the app can be driven from..."
  },
  {
    "page": "FAQ",
    "path": "/docs/faq",
    "section": "Why single-tenant?",
    "sectionId": "why-single-tenant",
    "text": "Because the agent can modify code. In a multi-tenant SaaS, you can't let one customer's agent change the source code — it would affect everyone. With single-tenant, each organization gets their own fork. The agent can safely evolve the code, add integrations, and customize the app because it's your..."
  },
  {
    "page": "FAQ",
    "path": "/docs/faq",
    "section": "Why is this a framework and not a library?",
    "sectionId": "why-framework-not-library",
    "text": "The shared database, polling sync, actions system, and application state all need to work together as a cohesive architecture. A library could give you pieces, but agent-native requires that the agent and UI are wired together from the ground up. Multiple agents need to be able to communicate, the..."
  },
  {
    "page": "FAQ",
    "path": "/docs/faq",
    "section": "Can the agent really modify the app's own code?",
    "sectionId": "can-the-agent-modify-code",
    "text": "Yes, and it's a feature. Because every agent-native app is single-tenant — your team's own fork — the agent can safely edit components, routes, styles, and actions. There's no shared codebase to break. You ask \"add a cohort analysis chart\" and the agent builds it. You ask \"connect to our Stripe..."
  },
  {
    "page": "FAQ",
    "path": "/docs/faq",
    "section": "Can agents talk to each other?",
    "sectionId": "can-agents-talk-to-each-other",
    "text": "Yes, via the A2A (Agent-to-Agent) protocol . Every agent-native app automatically gets an A2A endpoint. From the mail app, you can tag the analytics agent to query data. An agent discovers what other agents are available, calls them over the protocol, and shows results in the UI. No configuration..."
  },
  {
    "page": "FAQ",
    "path": "/docs/faq",
    "section": "What can the agent see in the app?",
    "sectionId": "what-can-the-agent-see",
    "text": "The agent always knows what the user is currently viewing. The UI writes navigation state to the database on every route change — which view is open, which item is selected. The agent reads this via the view-screen action before taking action. If an email is open, the agent knows which email. If a..."
  },
  {
    "page": "FAQ",
    "path": "/docs/faq",
    "section": "What templates are available?",
    "sectionId": "what-templates-are-available",
    "text": "The framework ships with production-ready templates that you can use as daily drivers: Mail — full-featured email client (like Superhuman) Calendar — Google Calendar + Calendly-style meeting links Content — Notion-style documents Slides — presentation builder Video — video composition with Remotion..."
  },
  {
    "page": "FAQ",
    "path": "/docs/faq",
    "section": "Can I customize templates?",
    "sectionId": "can-i-customize-templates",
    "text": "That's the whole point. Fork a template and customize it by asking the agent. \"Add a priority field to forms.\" \"Connect to our Salesforce instance.\" \"Change the color scheme to match our brand.\" The agent modifies the code, and your app evolves over time."
  },
  {
    "page": "FAQ",
    "path": "/docs/faq",
    "section": "Can I build from scratch without a template?",
    "sectionId": "can-i-build-from-scratch",
    "text": "Yes. Run npx @agent-native/core create my-app without the --template flag. You get the framework scaffolding — React frontend, Nitro backend, agent panel, database — but no domain-specific code. See Getting Started . ); }"
  },
  {
    "page": "Frames",
    "path": "/docs/frames",
    "section": "Embedded Agent Panel",
    "sectionId": "embedded-agent",
    "text": "Ships with @agent-native/core — no separate package needed Agent panel embedded directly in your app with chat and optional CLI terminal Supports multiple AI coding CLIs — switch between them from the settings panel Toggle between production mode (app tools only) and development mode (full..."
  },
  {
    "page": "Frames",
    "path": "/docs/frames",
    "section": "Supported CLIs",
    "sectionId": "supported-clis",
    "text": "CLI Command Key Flags > ))} Switch between CLIs at any time from the agent panel settings. The terminal restarts with the selected CLI."
  },
  {
    "page": "Frames",
    "path": "/docs/frames",
    "section": "Builder.io Cloud",
    "sectionId": "cloud-frame",
    "text": "Runs in the cloud Real-time collaboration — multiple users can watch/interact simultaneously Visual editing, roles and permissions Parallel agent execution for faster iteration Great for team use"
  },
  {
    "page": "Frames",
    "path": "/docs/frames",
    "section": "How It Works",
    "sectionId": "how-it-works",
    "text": "The framework provides type-safe APIs so you never deal with raw messaging: Agent chat — use sendToAgentChat() to send messages to the agent Generation state — use useAgentChatGenerating() to track when the agent is running File watching — SSE endpoint keeps UI in sync when the agent modifies files..."
  },
  {
    "page": "Integrations",
    "path": "/docs/integrations",
    "section": "Overview",
    "sectionId": "overview",
    "text": "Messaging integrations let users talk to their agent from the platforms they already use. Instead of opening the web UI, you send a message in Slack or Telegram and the agent responds right there. It has access to the same actions, the same database, and the same conversation history as the web..."
  },
  {
    "page": "Integrations",
    "path": "/docs/integrations",
    "section": "How it works",
    "sectionId": "how-it-works",
    "text": "The flow for every platform follows the same pattern: A user sends a message on the external platform (Slack, Telegram, etc.) The platform delivers the message to your app via a webhook at /_agent-native/integrations/&lt;platform&gt;/webhook The integrations plugin validates the request, extracts..."
  },
  {
    "page": "Integrations",
    "path": "/docs/integrations",
    "section": "Setup",
    "sectionId": "setup",
    "text": "The integrations plugin auto-mounts when no custom version exists in your template. To customize it, create a plugin file: The plugin registers webhook routes for each enabled platform under /_agent-native/integrations/ . Which platforms are active depends on which environment variables are..."
  },
  {
    "page": "Integrations",
    "path": "/docs/integrations",
    "section": "Slack",
    "sectionId": "slack",
    "text": "1. Create a Slack app Go to api.slack.com/apps and create a new app. Under OAuth &amp; Permissions , add the following bot token scopes: chat:write — send messages app_mentions:read — receive @-mentions (optional) 2. Enable Event Subscriptions Under Event Subscriptions , set the Request URL to:..."
  },
  {
    "page": "Integrations",
    "path": "/docs/integrations",
    "section": "Telegram",
    "sectionId": "telegram",
    "text": "1. Create a bot Message @BotFather on Telegram and use the /newbot command. You will receive a bot token. 2. Set environment variables 3. Register the webhook After deploying your app, call the setup endpoint to register the webhook with Telegram: You can also register the webhook manually using..."
  },
  {
    "page": "Integrations",
    "path": "/docs/integrations",
    "section": "WhatsApp",
    "sectionId": "whatsapp",
    "text": "1. Set up the WhatsApp Cloud API Go to the Meta Developer Portal , create an app, and enable the WhatsApp product. Configure a phone number for your business. 2. Set environment variables The verify token is a string you choose — Meta uses it during webhook verification. The access token and phone..."
  },
  {
    "page": "Integrations",
    "path": "/docs/integrations",
    "section": "Configuration",
    "sectionId": "configuration",
    "text": "Integrations can be managed from the settings UI in the sidebar. Each platform shows its connection status and webhook URL. You can enable/disable individual integrations without removing environment variables. The webhook URLs follow a consistent pattern:"
  },
  {
    "page": "Integrations",
    "path": "/docs/integrations",
    "section": "Thread continuity",
    "sectionId": "thread-continuity",
    "text": "Conversations from external platforms are mapped to internal threads. Each Slack DM, Telegram chat, or WhatsApp conversation becomes a persistent thread in the agent-native database. This means: The agent retains context across messages in the same external conversation External conversations..."
  },
  {
    "page": "Integrations",
    "path": "/docs/integrations",
    "section": "Custom adapters",
    "sectionId": "custom-adapters",
    "text": "To add support for a new messaging platform, implement the PlatformAdapter interface: Register your adapter in the integrations plugin config:"
  },
  {
    "page": "Integrations",
    "path": "/docs/integrations",
    "section": "Security",
    "sectionId": "security",
    "text": "Every incoming webhook is verified before processing: Slack — HMAC-SHA256 signature verification using SLACK_SIGNING_SECRET . The X-Slack-Signature header is checked against the request body. Telegram — requests are validated by checking the secret token set during webhook registration via the..."
  },
  {
    "page": "Key Concepts",
    "path": "/docs/key-concepts",
    "section": "Why agent-native",
    "sectionId": "why-agent-native",
    "text": "Teams today have four options for AI-powered work, and none of them are ideal: Chat apps (Claude Projects, ChatGPT) — accessible but not built for structured workflows. No persistent UI, no dashboards, no team collaboration. Raw agent interfaces (Claude Code, Cursor) — powerful but inaccessible to..."
  },
  {
    "page": "Key Concepts",
    "path": "/docs/key-concepts",
    "section": "The architecture",
    "sectionId": "the-architecture",
    "text": "Every agent-native app is three things working together: Agent Autonomous AI that reads data, writes data, runs actions, and modifies code. Customizable with skills and instructions. Application Full React UI with dashboards, flows, and visualizations. Guided experiences your team can use. Computer..."
  },
  {
    "page": "Key Concepts",
    "path": "/docs/key-concepts",
    "section": "The four-area checklist",
    "sectionId": "four-area-checklist",
    "text": "Every new feature must update all four areas. Skipping any one breaks the agent-native contract. className=\"bg-[var(--bg)] p-4\"> ))} A feature with only UI is invisible to the agent. A feature with only actions is invisible to the user. A feature without app-state means the agent is blind to what..."
  },
  {
    "page": "Key Concepts",
    "path": "/docs/key-concepts",
    "section": "Data in SQL",
    "sectionId": "data-in-sql",
    "text": "All application state lives in a SQL database via Drizzle ORM. The framework supports multiple databases — SQLite, Postgres (Neon, Supabase), Turso, Cloudflare D1. Users configure DATABASE_URL to choose their database. Core SQL stores are auto-created and available in every template:..."
  },
  {
    "page": "Key Concepts",
    "path": "/docs/key-concepts",
    "section": "Agent chat bridge",
    "sectionId": "agent-chat-bridge",
    "text": "The UI never calls an LLM directly. When a user clicks \"Generate chart\" or \"Write summary\", the UI sends a message to the agent via postMessage . The agent does the work — with full conversation history, skills, instructions, and the ability to iterate. Why not call an LLM inline? AI is..."
  },
  {
    "page": "Key Concepts",
    "path": "/docs/key-concepts",
    "section": "Actions system",
    "sectionId": "actions-system",
    "text": "When the agent needs to do something complex — call an API, process data, query the database — it runs an action. Actions are TypeScript files in actions/ that export a default async function: This means anything the UI can do, the agent can do — and vice versa. The UI calls POST /api/fetch-data ,..."
  },
  {
    "page": "Key Concepts",
    "path": "/docs/key-concepts",
    "section": "Polling sync",
    "sectionId": "polling-sync",
    "text": "Database changes are synced to the UI via lightweight polling. When the agent writes to the database (application state, settings, or domain data), a version counter increments. The client useDbSync() hook (formerly useFileWatcher ) polls /_agent-native/poll every 2 seconds and invalidates React..."
  },
  {
    "page": "Key Concepts",
    "path": "/docs/key-concepts",
    "section": "Frames",
    "sectionId": "frames",
    "text": "Agent-native apps include an embedded agent panel that provides the AI agent alongside the app UI. This is what makes the architecture work: the agent needs a computer (database, browser, code execution), and the app needs the agent for AI work. Embedded Agent Panel Chat and optional CLI terminal..."
  },
  {
    "page": "Key Concepts",
    "path": "/docs/key-concepts",
    "section": "Context awareness",
    "sectionId": "context-awareness",
    "text": "The agent always knows what the user is looking at. The UI writes a navigation key to application-state on every route change. The agent reads it via the view-screen action before acting. See Context Awareness for the full pattern: navigation state, view-screen, navigate commands, and jitter..."
  },
  {
    "page": "Key Concepts",
    "path": "/docs/key-concepts",
    "section": "APIs & CLIs, not MCPs",
    "sectionId": "apis-and-clis",
    "text": "Agent-native apps can work with MCP servers, but the architecture leans heavily on something more standard: regular APIs and CLIs accessed through code execution . Agents are great at writing code that calls fetch() or runs a CLI command — no special protocol needed. No wrapper layer. Call APIs..."
  },
  {
    "page": "Key Concepts",
    "path": "/docs/key-concepts",
    "section": "Agent modifies code",
    "sectionId": "agent-modifies-code",
    "text": "This is a feature, not a bug. Because every agent-native app is single-tenant — your team's own fork — the agent can safely edit the app's source code: components, routes, styles, actions. There's no shared codebase to break. You own the app, and the agent evolves it for you over time: Fork a..."
  },
  {
    "page": "Key Concepts",
    "path": "/docs/key-concepts",
    "section": "Database agnostic",
    "sectionId": "database-agnostic",
    "text": "The framework supports every Drizzle-supported database. Never write SQL that only works on one dialect. SQLite — local dev fallback when DATABASE_URL is unset Neon Postgres — common in both dev and production Turso (libSQL) — edge-friendly SQLite-compatible Supabase Postgres Cloudflare D1 Plain..."
  },
  {
    "page": "Key Concepts",
    "path": "/docs/key-concepts",
    "section": "Hosting agnostic",
    "sectionId": "hosting-agnostic",
    "text": "The server runs on Nitro, which compiles to any deployment target: Node.js — local dev, traditional servers Cloudflare Workers/Pages Netlify Functions/Edge Vercel Serverless/Edge Deno Deploy AWS Lambda Bun Never use Node-specific APIs ( fs , child_process , path ) in server routes or plugins. These..."
  },
  {
    "page": "Key Concepts",
    "path": "/docs/key-concepts",
    "section": "Deep dives",
    "sectionId": "deep-dives",
    "text": "For detailed guidance on specific patterns: What Is Agent-Native? — the vision and philosophy Context Awareness — navigation state, view-screen, navigate commands Skills Guide — framework skills, domain skills, creating custom skills A2A Protocol — agent-to-agent communication ); }"
  },
  {
    "page": "Real-Time Collaboration",
    "path": "/docs/real-time-collaboration",
    "section": "Overview",
    "sectionId": "overview",
    "text": "The framework provides a Yjs-based collaborative editing system in @agent-native/core/collab . Multiple users can edit the same document simultaneously with live cursor positions, and the AI agent can make surgical edits that appear in real-time without disrupting the user's cursor, selection, or..."
  },
  {
    "page": "Real-Time Collaboration",
    "path": "/docs/real-time-collaboration",
    "section": "How it works",
    "sectionId": "how-it-works",
    "text": "The collaboration system has three layers: Yjs Y.Doc — stores the document as a Y.XmlFragment (ProseMirror node tree). This is the CRDT that enables conflict-free merging of concurrent edits. TipTap Collaboration extension — binds the editor to the Y.XmlFragment via ySyncPlugin . Remote changes are..."
  },
  {
    "page": "Real-Time Collaboration",
    "path": "/docs/real-time-collaboration",
    "section": "Agent + human collaboration",
    "sectionId": "agent-human-collab",
    "text": "The agent and human users are equal participants in collaborative editing. The key insight is that both produce Yjs operations that merge cleanly: Human edits flow through TipTap → ySyncPlugin → Y.XmlFragment → server via HTTP Agent edits flow through the edit-document action → server..."
  },
  {
    "page": "Real-Time Collaboration",
    "path": "/docs/real-time-collaboration",
    "section": "Enabling collaboration",
    "sectionId": "enabling-collab",
    "text": "Templates opt into collaboration with five steps: 1. Install dependencies 2. Add Vite optimizeDeps Prevents Vite from re-bundling TipTap in incompatible ways during dev: 3. Add the collab server plugin 4. Use the client hook 5. Add TipTap extensions"
  },
  {
    "page": "Real-Time Collaboration",
    "path": "/docs/real-time-collaboration",
    "section": "Live cursors & presence",
    "sectionId": "live-cursors",
    "text": "The CollaborationCaret extension renders colored cursor lines with user name labels for each connected user. The useCollaborativeDoc hook provides an activeUsers array that can be used to render a presence bar with user avatars. User identity is derived from the session email. The framework..."
  },
  {
    "page": "Real-Time Collaboration",
    "path": "/docs/real-time-collaboration",
    "section": "Comments",
    "sectionId": "comments",
    "text": "Templates can add a comments system with threaded discussions on documents. The content template includes a full implementation with: document_comments SQL table (threads, replies, resolved status) CRUD API routes at /api/comments Comments sidebar with threaded view and reply UI Resolve/unresolve..."
  },
  {
    "page": "Real-Time Collaboration",
    "path": "/docs/real-time-collaboration",
    "section": "Collab routes",
    "sectionId": "collab-routes",
    "text": "All collab routes are auto-mounted under /_agent-native/collab/ by the collab plugin: Route Purpose GET /:docId/state Fetch full Y.Doc state (base64) POST /:docId/update Apply client Yjs update POST /:docId/text Apply full text replacement (diff-based) POST /:docId/search-replace Surgical..."
  },
  {
    "page": "Real-Time Collaboration",
    "path": "/docs/real-time-collaboration",
    "section": "Agent edit action",
    "sectionId": "edit-document",
    "text": "The edit-document action is the primary way agents make changes to documents in collaborative mode: When collab state exists for the document, the action calls the server's search-replace endpoint via HTTP (not the collab module directly, since actions run in a separate process). The server walks..."
  },
  {
    "page": "Real-Time Collaboration",
    "path": "/docs/real-time-collaboration",
    "section": "Common pitfalls",
    "sectionId": "pitfalls",
    "text": "TipTap version mismatch — All @tiptap/* packages must be the same version. The Collaboration extension requires editor.utils which was added in v3.22.2. Add @tiptap/core as an explicit dependency. Empty editor on first load — The Collaboration extension does NOT auto-seed from the content prop...."
  },
  {
    "page": "Resources & Skills",
    "path": "/docs/resources",
    "section": "Overview",
    "sectionId": "overview",
    "text": "Every agent-native app has a built-in resource system. Resources are SQL-backed files that persist across sessions and deployments. Unlike code files, resources live in the database — not the filesystem — so they work in serverless environments, edge runtimes, and production deploys without any..."
  },
  {
    "page": "Resources & Skills",
    "path": "/docs/resources",
    "section": "Resources Panel",
    "sectionId": "resources-panel",
    "text": "The agent panel includes a Resources tab alongside Chat and CLI. This panel lets users browse, create, edit, and delete resources. It displays a tree view of all resources organized by folder path. Resources can be any text file — Markdown, JSON, YAML, plain text. The panel includes an inline..."
  },
  {
    "page": "Resources & Skills",
    "path": "/docs/resources",
    "section": "How the Agent Uses Resources",
    "sectionId": "how-the-agent-uses-resources",
    "text": "The agent has built-in tools for managing resources: resource-list , resource-read , resource-write , and resource-delete . These are available in both dev and production modes. At the start of every conversation, the agent automatically reads:"
  },
  {
    "page": "Resources & Skills",
    "path": "/docs/resources",
    "section": "AGENTS.md",
    "sectionId": "agents-md",
    "text": "A shared resource seeded by default. It contains custom instructions, preferences, and skill references. Edit this to change how the agent behaves for all users — tone, rules, domain context, and which skills to use."
  },
  {
    "page": "Resources & Skills",
    "path": "/docs/resources",
    "section": "learnings.md",
    "sectionId": "learnings-md",
    "text": "A personal resource where the agent records corrections, preferences, and patterns it learns from each user. When the agent makes a mistake and the user corrects it, the agent updates learnings.md so it doesn't repeat the error."
  },
  {
    "page": "Resources & Skills",
    "path": "/docs/resources",
    "section": "Skills",
    "sectionId": "skills",
    "text": "Skills are Markdown resource files that give the agent deep domain knowledge for specific tasks. They live under the skills/ path prefix in resources (e.g. skills/data-analysis.md , skills/code-review.md ). When the agent encounters a task that matches a skill, it reads the skill file and follows..."
  },
  {
    "page": "Resources & Skills",
    "path": "/docs/resources",
    "section": "Creating Skills",
    "sectionId": "creating-skills",
    "text": "There are two ways to add skills: Via Resources panel — Create a new resource with a path like skills/my-skill.md . This works in both dev and production. Via code (dev only) — Add a Markdown file to .agents/skills/ in your project. These are available when the app runs in dev mode."
  },
  {
    "page": "Resources & Skills",
    "path": "/docs/resources",
    "section": "Skill Format",
    "sectionId": "skill-format",
    "text": "Skills are Markdown files with optional YAML frontmatter for metadata:"
  },
  {
    "page": "Resources & Skills",
    "path": "/docs/resources",
    "section": "@ File Tagging",
    "sectionId": "at-file-tagging",
    "text": "Type @ in the chat input to reference files. A dropdown appears at the cursor showing matching files. Use arrow keys to navigate and Enter to select. The selected file appears as an inline chip in the input. When you send a message with file references, the agent receives the file paths as context..."
  },
  {
    "page": "Resources & Skills",
    "path": "/docs/resources",
    "section": "/ Slash Commands",
    "sectionId": "slash-commands",
    "text": "Type / at the start of a line to invoke a skill. A dropdown shows available skills with their names and descriptions. Selecting a skill adds it as an inline chip, and its content is included as context when the message is sent. What shows up depends on the mode: Dev mode — Skills from..."
  },
  {
    "page": "Resources & Skills",
    "path": "/docs/resources",
    "section": "Dev vs Production Mode",
    "sectionId": "dev-vs-prod",
    "text": "The resource system works identically in both modes. The difference is what additional sources are available for @ tagging and / commands: Feature Dev Mode Production > ))}"
  },
  {
    "page": "Resources & Skills",
    "path": "/docs/resources",
    "section": "Resource API",
    "sectionId": "resource-api",
    "text": "Resources can be managed from server code, actions, or the REST API."
  },
  {
    "page": "Resources & Skills",
    "path": "/docs/resources",
    "section": "Server API",
    "sectionId": "server-api",
    "text": "REST endpoints mounted automatically: Method Endpoint Description > ))}"
  },
  {
    "page": "Resources & Skills",
    "path": "/docs/resources",
    "section": "Action API",
    "sectionId": "action-api",
    "text": "The agent uses these built-in actions. You can also call them from your own actions: ); }"
  },
  {
    "page": "Security &amp; Data Scoping",
    "path": "/docs/security",
    "section": "Data Scoping",
    "sectionId": "data-scoping",
    "text": "Data scoping ensures each user only sees their own data. It works by creating temporary SQL views that filter tables before the agent's query runs. Two scoping dimensions are supported: owner_email &mdash; per-user data isolation (required for all user-facing tables) org_id &mdash; per-organization..."
  },
  {
    "page": "Security &amp; Data Scoping",
    "path": "/docs/security",
    "section": "Per-User Scoping",
    "sectionId": "per-user-scoping",
    "text": "Every table with user-specific data must have an owner_email text column: The current user's email comes from AGENT_USER_EMAIL , which is automatically set from the auth session before any agent script runs."
  },
  {
    "page": "Security &amp; Data Scoping",
    "path": "/docs/security",
    "section": "Per-Org Scoping",
    "sectionId": "per-org-scoping",
    "text": "For apps where teams share data within an organization, add an org_id column: When both columns are present, queries are scoped by both : WHERE owner_email = ? AND org_id = ? . The org_id is automatically resolved from the user's active organization in Better Auth. Templates can override this with..."
  },
  {
    "page": "Security &amp; Data Scoping",
    "path": "/docs/security",
    "section": "How Scoping Works",
    "sectionId": "how-scoping-works",
    "text": "When an agent runs db-query or db-exec in production mode: The framework discovers all tables and their columns via schema introspection For each table with owner_email and/or org_id , a temporary view is created: The agent's query runs against the views (not the real tables) Views are dropped..."
  },
  {
    "page": "Security &amp; Data Scoping",
    "path": "/docs/security",
    "section": "INSERT Auto-Injection",
    "sectionId": "insert-auto-injection",
    "text": "When an agent runs an INSERT via db-exec , the framework automatically injects ownership columns: This only happens when the columns aren't already present in the INSERT statement."
  },
  {
    "page": "Security &amp; Data Scoping",
    "path": "/docs/security",
    "section": "A2A Identity Verification",
    "sectionId": "a2a-identity",
    "text": "When apps call each other via the A2A protocol, they can verify the caller's identity using JWT tokens signed with a shared secret: How it works: App A signs a JWT with A2A_SECRET containing sub: \"steve@example.com\" App B receives the call and verifies the JWT signature with the same secret App B..."
  },
  {
    "page": "Security &amp; Data Scoping",
    "path": "/docs/security",
    "section": "Schema Validation",
    "sectionId": "validation",
    "text": "Run the scoping check to verify all tables have proper ownership columns: Tables without scoping columns are flagged. Core framework tables ( settings , application_state , sessions ) use their own scoping mechanisms and are excluded from the check."
  },
  {
    "page": "Security &amp; Data Scoping",
    "path": "/docs/security",
    "section": "Production Checklist",
    "sectionId": "production-checklist",
    "text": "Every user-facing table has owner_email Multi-user tables also have org_id BETTER_AUTH_SECRET is set to a random 32+ character string A2A_SECRET is set on all apps that call each other AUTH_MODE is not set to local in production Run pnpm action db-check-scoping to validate schema Test with two user..."
  },
  {
    "page": "Skills Guide",
    "path": "/docs/skills-guide",
    "section": "What are skills",
    "sectionId": "what-are-skills",
    "text": "Skills live at .agents/skills/&lt;name&gt;/SKILL.md and contain detailed guidance for the agent. Each skill focuses on one concern — how to store data, how to sync state, how to delegate work to the agent chat. The agent reads skills when it needs to follow a specific pattern. Skills are referenced..."
  },
  {
    "page": "Skills Guide",
    "path": "/docs/skills-guide",
    "section": "Framework skills",
    "sectionId": "framework-skills",
    "text": "These skills ship with the framework and apply to all agent-native apps: Skill When to use > ))}"
  },
  {
    "page": "Skills Guide",
    "path": "/docs/skills-guide",
    "section": "Domain skills",
    "sectionId": "domain-skills",
    "text": "Templates include skills specific to their domain. These live in the same .agents/skills/ directory but cover template-specific patterns: Mail template — email-drafts, thread-management, label-system Forms template — form-building, field-types, submission-handling Analytics template — chart-types,..."
  },
  {
    "page": "Skills Guide",
    "path": "/docs/skills-guide",
    "section": "Creating custom skills",
    "sectionId": "creating-skills",
    "text": "Create a skill when: There's a pattern the agent should follow repeatedly A workflow needs step-by-step guidance You want to scaffold files from a template Don't create a skill when: The guidance already exists in another skill — extend it instead The guidance is a one-off — put it in AGENTS.md or..."
  },
  {
    "page": "Skills Guide",
    "path": "/docs/skills-guide",
    "section": "Skill format",
    "sectionId": "skill-format",
    "text": "Each skill is a Markdown file with YAML frontmatter: The frontmatter name and description are used by the agent's tool system for skill discovery. The description should state when the skill triggers — be specific about the situations. Save the file at .agents/skills/my-skill/SKILL.md . The..."
  },
  {
    "page": "Skills Guide",
    "path": "/docs/skills-guide",
    "section": "Skills vs AGENTS.md",
    "sectionId": "skills-vs-agents-md",
    "text": "AGENTS.md The overview. Lists all scripts, describes the data model, explains the app architecture. The agent reads this first to understand the app. Skills Deep dives. Each skill focuses on one pattern with detailed rules, code examples, and do/don't lists. The agent reads these when it needs to..."
  },
  {
    "page": "What Is Agent-Native?",
    "path": "/docs/what-is-agent-native",
    "section": "What is an agent-native app?",
    "sectionId": "what-is-an-agent-native-app",
    "text": "Think of agent-native apps as a layer on top of AI agents. An agent has skills, instructions, and tools. It can be autonomous and general purpose. The application sits on top of that and gives it structure. Importantly, agent-native does not mean \"app that calls an LLM.\" That's the anti-pattern. A..."
  },
  {
    "page": "What Is Agent-Native?",
    "path": "/docs/what-is-agent-native",
    "section": "Not just a chatbot",
    "sectionId": "not-just-a-chatbot",
    "text": "A chat interface alone isn't enough. When you're building tools for people to actually use, you need more than a box for them to type a prompt into: Discoverability — users need to know what the app can do without guessing prompts Workflows — structured flows for common tasks like composing emails,..."
  },
  {
    "page": "What Is Agent-Native?",
    "path": "/docs/what-is-agent-native",
    "section": "Agent + UI parity",
    "sectionId": "agent-ui-parity",
    "text": "This is the defining principle. Any application functionality should be able to be done by the agent or the UI: From the UI Click buttons, fill forms, navigate views. The UI writes to the database and the agent can see the results. From the agent Natural language, other agents via A2A, Slack,..."
  },
  {
    "page": "What Is Agent-Native?",
    "path": "/docs/what-is-agent-native",
    "section": "What makes it different",
    "sectionId": "what-makes-it-different",
    "text": "Every agent ultimately needs a management interface. At the minimum, you need to understand what it's doing, inspect the data it's creating, and debug when things go wrong. That's just called an application. className=\"bg-[var(--bg)] p-4\"> ))} The argument is simple: make your agents composable,..."
  },
  {
    "page": "What Is Agent-Native?",
    "path": "/docs/what-is-agent-native",
    "section": "What is agent-native development?",
    "sectionId": "what-is-agent-native-development",
    "text": "Agent-native development means building with agents first. You build projects that work great when prompted from AI coding tools like Claude Code, Codex, Cursor, Windsurf, and Builder.io. The idea is that you build instructions and skills into the project as prerequisites. The agent will tend to do..."
  },
  {
    "page": "What Is Agent-Native?",
    "path": "/docs/what-is-agent-native",
    "section": "Agents as first-class developers",
    "sectionId": "agents-as-first-class-developers",
    "text": "In an agent-native project: AGENTS.md gives every AI coding tool the same instructions — Claude Code, Cursor, Windsurf, and others all read the same file Skills teach the agent patterns for specific tasks — adding features, storing data, wiring real-time sync Agent PR reviewers can validate that..."
  },
  {
    "page": "What Is Agent-Native?",
    "path": "/docs/what-is-agent-native",
    "section": "Whole-team development",
    "sectionId": "whole-team-development",
    "text": "Agent-native development isn't just for developers. The goal is actual agent-native development as a team: Designers can update designs directly in the code through the agent Product managers can update functionalities and requirements QA can test and prompt for fixes Anyone on the team can..."
  },
  {
    "page": "What Is Agent-Native?",
    "path": "/docs/what-is-agent-native",
    "section": "Fork and customize",
    "sectionId": "fork-and-customize",
    "text": "Agent-native apps follow a single-tenant, fork-and-customize model. You start from a template — mail, calendar, analytics, slides — and make it yours: Pick a template on agentnative.com Start using it immediately as a hosted app (e.g. mail.agentnative.com) Fork it when you want to customize —..."
  },
  {
    "page": "What Is Agent-Native?",
    "path": "/docs/what-is-agent-native",
    "section": "Composable agents",
    "sectionId": "composable-agents",
    "text": "Agent-native apps can communicate with each other using the A2A protocol . From the mail app, you can tag the analytics agent to query data and include results in a draft. An agent discovers what other agents are available, calls them over the protocol, and shows results in the UI. This is why..."
  }
];
