[build]
  command = "export DATABASE_URL=${NETLIFY_DATABASE_URL:-$DATABASE_URL} && pnpm install && pnpm --filter mail exec drizzle-kit push --force && NITRO_PRESET=netlify pnpm --filter mail build"
  publish = "templates/mail/dist"
  functions = "templates/mail/.netlify/functions-internal"

[build.environment]
  NITRO_PRESET = "netlify"
