[build]
  command = "pnpm install && NITRO_PRESET=netlify pnpm --filter mail build"
  publish = "templates/mail/dist"
  functions = "templates/mail/.netlify/functions-internal"

[build.environment]
  NITRO_PRESET = "netlify"
