// Generated by scripts/gen-store-registry.ts from every `defineStore()` export.
// Do not edit. Run `pnpm gen:store-registry` after adding or removing a store.
import type { Store } from "./store-registry.js";

export const FRAMEWORK_STORES: ReadonlyArray<
  readonly [id: string, load: () => Promise<Store>]
> = [
  [
    "a2a_continuations",
    () =>
      import("../integrations/a2a-continuations-store.js").then(
        (m) => m.a2aContinuationsStore,
      ),
  ],
  [
    "a2a_tasks",
    () => import("../a2a/task-store.js").then((m) => m.a2aTasksStore),
  ],
  [
    "agent_harness_sessions",
    () =>
      import("../agent/harness/store.js").then(
        (m) => m.agentHarnessSessionsStore,
      ),
  ],
  [
    "agent_runs",
    () => import("../agent/run-store.js").then((m) => m.agentRunsStore),
  ],
  [
    "agent_team_run_queue",
    () =>
      import("../server/agent-teams-run-queue.js").then(
        (m) => m.agentTeamRunQueueStore,
      ),
  ],
  [
    "agent_tool_approval_policies",
    () =>
      import("../agent/tool-approval-store.js").then(
        (m) => m.agentToolApprovalPoliciesStore,
      ),
  ],
  [
    "agent_tool_approvals",
    () =>
      import("../agent/tool-approval-store.js").then(
        (m) => m.agentToolApprovalsStore,
      ),
  ],
  [
    "app_secrets",
    () => import("../secrets/storage.js").then((m) => m.appSecretsStore),
  ],
  [
    "application_state",
    () =>
      import("../application-state/store.js").then(
        (m) => m.applicationStateStore,
      ),
  ],
  ["audit", () => import("../audit/store.js").then((m) => m.auditStore)],
  [
    "auth_sessions",
    () => import("../server/auth.js").then((m) => m.authSessionsStore),
  ],
  [
    "automation_run_history",
    () =>
      import("../jobs/run-history.js").then((m) => m.automationRunHistoryStore),
  ],
  [
    "automation_webhook_tokens",
    () =>
      import("../triggers/webhook-store.js").then(
        (m) => m.automationWebhookTokensStore,
      ),
  ],
  [
    "awaiting_inputs",
    () =>
      import("../integrations/awaiting-input-store.js").then(
        (m) => m.awaitingInputsStore,
      ),
  ],
  [
    "browser_sessions",
    () =>
      import("../browser-sessions/store.js").then(
        (m) => m.browserSessionsStore,
      ),
  ],
  [
    "chat_threads",
    () => import("../chat-threads/store.js").then((m) => m.chatThreadsStore),
  ],
  [
    "checkpoints",
    () => import("../checkpoints/store.js").then((m) => m.checkpointsStore),
  ],
  [
    "collab_awareness",
    () =>
      import("../collab/awareness-store.js").then(
        (m) => m.collabAwarenessStore,
      ),
  ],
  [
    "collab_docs",
    () => import("../collab/storage.js").then((m) => m.collabDocsStore),
  ],
  [
    "computer_approvals",
    () =>
      import("../integrations/computer-supervision-store.js").then(
        (m) => m.computerApprovalsStore,
      ),
  ],
  [
    "conversation_scopes",
    () =>
      import("../integrations/scope-store.js").then(
        (m) => m.conversationScopesStore,
      ),
  ],
  [
    "custom_api_providers",
    () =>
      import("../provider-api/custom-registry.js").then(
        (m) => m.customApiProvidersStore,
      ),
  ],
  [
    "data_programs",
    () => import("../data-programs/store.js").then((m) => m.dataProgramsStore),
  ],
  [
    "email_log",
    () => import("../email-catalog/log.js").then((m) => m.emailLogStore),
  ],
  [
    "embed_sessions",
    () =>
      import("../server/embed-session.js").then((m) => m.embedSessionsStore),
  ],
  [
    "extension_slots",
    () =>
      import("../extensions/slots/store.js").then((m) => m.extensionSlotsStore),
  ],
  [
    "extensions",
    () => import("../extensions/store.js").then((m) => m.extensionsStore),
  ],
  [
    "identity_links",
    () =>
      import("../integrations/identity-links-store.js").then(
        (m) => m.identityLinksStore,
      ),
  ],
  [
    "identity_sso",
    () =>
      import("../server/identity-sso-store.js").then((m) => m.identitySsoStore),
  ],
  [
    "integration_campaigns",
    () =>
      import("../integrations/integration-campaigns-store.js").then(
        (m) => m.integrationCampaignsStore,
      ),
  ],
  [
    "integration_configs",
    () =>
      import("../integrations/config-store.js").then(
        (m) => m.integrationConfigsStore,
      ),
  ],
  [
    "integration_controls",
    () =>
      import("../integrations/controls-store.js").then(
        (m) => m.integrationControlsStore,
      ),
  ],
  [
    "integration_installations",
    () =>
      import("../integrations/installations-store.js").then(
        (m) => m.installationsStore,
      ),
  ],
  [
    "mcp_approvals",
    () => import("../mcp/approval-store.js").then((m) => m.mcpApprovalsStore),
  ],
  [
    "mcp_connect",
    () => import("../mcp/connect-store.js").then((m) => m.mcpConnectStore),
  ],
  [
    "mcp_oauth",
    () => import("../mcp/oauth-store.js").then((m) => m.mcpOauthStore),
  ],
  [
    "notifications",
    () => import("../notifications/store.js").then((m) => m.notificationsStore),
  ],
  [
    "oauth_tokens",
    () => import("../oauth-tokens/store.js").then((m) => m.oauthTokensStore),
  ],
  [
    "observability",
    () => import("../observability/store.js").then((m) => m.observabilityStore),
  ],
  [
    "observational_memory",
    () =>
      import("../agent/observational-memory/store.js").then(
        (m) => m.observationalMemoryStore,
      ),
  ],
  [
    "pending_tasks",
    () =>
      import("../integrations/pending-tasks-store.js").then(
        (m) => m.pendingTasksStore,
      ),
  ],
  [
    "progress",
    () => import("../progress/store.js").then((m) => m.progressStore),
  ],
  [
    "provider_corpus_jobs",
    () =>
      import("../provider-api/corpus-jobs-store.js").then(
        (m) => m.providerCorpusJobsStore,
      ),
  ],
  [
    "provider_quota_cooldowns",
    () =>
      import("../provider-api/quota-governor.js").then(
        (m) => m.providerQuotaCooldownsStore,
      ),
  ],
  [
    "recap_images",
    () =>
      import("../server/recap-image-store.js").then((m) => m.recapImagesStore),
  ],
  [
    "remote_commands",
    () =>
      import("../integrations/remote-commands-store.js").then(
        (m) => m.remoteCommandsStore,
      ),
  ],
  [
    "remote_devices",
    () =>
      import("../integrations/remote-devices-store.js").then(
        (m) => m.remoteDevicesStore,
      ),
  ],
  [
    "remote_push",
    () =>
      import("../integrations/remote-push-store.js").then(
        (m) => m.remotePushStore,
      ),
  ],
  [
    "remote_run_events",
    () =>
      import("../integrations/remote-run-events-store.js").then(
        (m) => m.remoteRunEventsStore,
      ),
  ],
  [
    "resource_versions",
    () => import("../history/store.js").then((m) => m.resourceVersionsStore),
  ],
  [
    "resources",
    () => import("../resources/store.js").then((m) => m.resourcesStore),
  ],
  ["review", () => import("../review/store.js").then((m) => m.reviewStore)],
  [
    "review_suggestions",
    () =>
      import("../review/suggestions/store.js").then(
        (m) => m.reviewSuggestionsStore,
      ),
  ],
  [
    "sandbox_executions",
    () =>
      import("../coding-tools/sandbox/executions-store.js").then(
        (m) => m.sandboxExecutionsStore,
      ),
  ],
  [
    "scheduler_health",
    () =>
      import("../jobs/scheduler-health.js").then((m) => m.schedulerHealthStore),
  ],
  [
    "settings",
    () => import("../settings/store.js").then((m) => m.settingsStore),
  ],
  [
    "staged_datasets",
    () =>
      import("../provider-api/staged-datasets-store.js").then(
        (m) => m.stagedDatasetsStore,
      ),
  ],
  [
    "sync_events",
    () => import("../server/poll.js").then((m) => m.syncEventsStore),
  ],
  [
    "thread_mappings",
    () =>
      import("../integrations/thread-mapping-store.js").then(
        (m) => m.threadMappingsStore,
      ),
  ],
  ["usage", () => import("../usage/store.js").then((m) => m.usageStore)],
  [
    "usage_alerts",
    () => import("../usage/alerts-store.js").then((m) => m.usageAlertsStore),
  ],
  [
    "usage_budgets",
    () =>
      import("../integrations/usage-budget-store.js").then(
        (m) => m.usageBudgetsStore,
      ),
  ],
  [
    "workspace_connections",
    () =>
      import("../workspace-connections/store.js").then(
        (m) => m.workspaceConnectionsStore,
      ),
  ],
  [
    "workspace_user_groups",
    () =>
      import("../workspace-connections/groups.js").then(
        (m) => m.workspaceUserGroupsStore,
      ),
  ],
];
